### ISSUE TITLE
Row height and window size changes while choosing themes in lxqt-config

### ISSUE THREAD

**Issue by chimak111** [lxqt/lxqt#1540] opened 2018-08-09 10:35 UTC
**Provide a general summary of the issue in the Title above** 

I'm trying out Lubuntu 18.10 (LXQt).

##### Expected Behavior
When I select widget styles listed in LXQt Appearance Configuration, I expect the window dimensions to remain unchanged and the row height to remain unchanged.

##### Current Behavior
Instead, when I click on on `bb10dark` or on `bb10bright`,  the row height for all widget styles increase as does the window size. This should not happen.

Note that the adjacent simplescreenrecorder window, while reflecting the chosen widget size, is otherwise normal and doesn't resize.

##### Steps to Reproduce (for bugs)
Already filed https://bugs.launchpad.net/ubuntu/+source/qtstyleplugins-src/+bug/1785401

##### System Information

* Distribution & Version: Lubuntu 18.10 fully updated
* Kernel: 4.17.0-6-generic x86_64
* Qt Version: Qt 4.8.7
* liblxqt Version: liblxqt0 version: 0.13.0
* Package version: lxqt-config version: 0.13.0

![lxqt1](https://user-images.githubusercontent.com/42237881/43893716-881de7f4-9bed-11e8-87d7-96c27fe254d3.png)
![lxqt2](https://user-images.githubusercontent.com/42237881/43893953-48eb5dea-9bee-11e8-8d72-65c262f0ac33.png)
![lxqt3](https://user-images.githubusercontent.com/42237881/43893964-535b40ec-9bee-11e8-940a-69cd4a456333.png)

**Comment by agaida** [comment] 2018-08-09 15:29
duplicate of #1532

And again: lxqt-config-appearance work like as expected - one can test it on a blackberry (that what the extra qt style is for). Two choices: ignore it  or purge qt5 -style-plugins.

**Closed by agaida** 2018-08-09 15:29 UTC
Labels: downstream, wontfix

**Comment by tsujan** [comment] 2018-08-09 16:38
The expectation ("This should not happen") is totally wrong. As a matter of fact, if it didn't happen, `lxqt-config-appearance` would have a bug.

**Comment by tsimonq2** [comment] 2018-08-09 18:50
Yeah, to prevent these bugs I'm going to remove that package from the metapackages...

Thanks for the quick response time @agaida and @tsujan.

**Comment by tsujan** [comment] 2018-08-09 19:02
@tsimonq2 I think users should be free to use bb10 and see what it is. As @agaida correctly said (elsewhere), it's for Blackberry but, today, I learned something valuable from bb10 (after it caused a freeze -- it *is* buggy): "kinetic scrolling" can be enabled in the widget style and I'll add an option for it to a future version of Kvantum.

**Comment by tsimonq2** [comment] 2018-08-09 19:16
@tsujan I don't disagree that users should have the ability to use it, but I won't ship a broken theme __by default__ in my distribution.

**Comment by agaida** [comment] 2018-08-09 19:31
>Unix was not designed to stop you from doing stupid things, because that would also stop you from doing clever things.

_Doug Gwyn, in Introducing Regular Expressions (2012) by Michael Fitzgerald_
