### ISSUE TITLE
[pcmanfm-qt ?] drag-and-drop problem

### ISSUE THREAD

**Issue by Esclapion** [lxqt/lxqt#688] opened 2015-06-12 18:45 UTC
Can not do a drag-and-drop an image from my desktop into chromium (for a search) .

**Comment by paulolieuthier** [comment] 2015-06-12 18:48
What version of Qt? DND is broken in Qt 5.4.0 IIRC.

**Comment by pmattern** [comment] 2015-06-12 19:04
Indeed: lxde/pcmanfm-qt#100, lxde/lxqt#458 and upstream https://bugreports.qt.io/browse/QTBUG-44201

**Comment by paulolieuthier** [comment] 2015-06-12 19:06
Thanks, @pmattern. :smile:

**Comment by Esclapion** [comment] 2015-06-12 19:31
5.4.1.9. Does it work for you ?

**Comment by paulolieuthier** [comment] 2015-06-12 19:33
Qt 5.4.2 here and it's working. @pmattern you have Qt 5.4.2 as well, right? @palinek what version of Qt do you have installed?

**Comment by pmattern** [comment] 2015-06-12 20:01
@Esclapion 
Which distro are you using and how / from which repos are you installing Qt and LXQt?

@paulolieuthier 
Yes, Qt 5.4.2 on Arch Linux. (palined is afaik on Debian testing and hence Qt 5.3.2.)

**Comment by Esclapion** [comment] 2015-06-12 20:39
Manjaro, and I use their repo, coming from those of Arch (stable).

**Comment by pmattern** [comment] 2015-06-12 20:44
Had another look in the meantime: drag & drop is working flawlessly here from PCManFM-Qt to JuffEd or Audacious both on Arch Linux (Qt 5.4.2) and Lubuntu 15.05 (Qt 5.4.1).

@Esclapion Could you
* try and verify the findings regarding Audacious and JuffEd
* tell what exactly the failing drag & drop action into Chromium is supposed to look like

**Comment by Esclapion** [comment] 2015-06-12 20:53
I install now audacious and juffed : it works for both, from desktop or from pcmanfm-qt.

Note : audacious is gtk2, and, i don't know why, but the look of juffed is horrible with my current theme.

**Comment by pmattern** [comment] 2015-06-12 21:37
"GTK 2" → edited my previous post.

What about drag & drop to Chromium (see my previous post)?

Also, my crystal ball, that damn thing, just wouldn't tell me the theme you're using. Thus I can't try to reproduce.

**Comment by Esclapion** [comment] 2015-06-12 21:51
What about ? (i edited my message too) I drop a picture on google image and nothing happens.

With a Manjaro xfce at the same level than my Manjaro lxqt, it works.

**Comment by Esclapion** [comment] 2015-06-12 22:12
Update now, and now 5.4.2. Always not working.

**Comment by pmattern** [comment] 2015-06-13 20:25
Confirmed.
Drag & Drop to Google image doesn't work with PCManFM-Qt. The typical dialog asking to "Drop image here" comes up but dropping the image into it doesn't work. Same procedure does work running e. g. Thunar on the very same system.

Yet this means your primary assumption drag & drop from PCManFM-Qt wouldn't work at all was pretty much narrowed down and I suggest you change the title accordingly.
You may want to confirm the additional finding regarding File Roller as stated above before.

**Comment by Esclapion** [comment] 2015-06-13 20:47
I removed this sentence in the OP, the title seems right ;)

But what I would say also is that for example if you do a drag-and-drop of a folder to the address bar of a browser, chromium at least, thunar opens the corresponding arbo in the browser. With lxqt, not.

**Comment by pmattern** [comment] 2015-06-13 20:57
Confirmed as well.
But please try and describe all relevant findings precisely and at once next time instead of dropping one after the other.
We want to use the limited time we have reasonably and aren't searching Easter eggs here.

**Comment by Esclapion** [comment] 2015-06-13 21:13
For me, it's the same problem.

**Comment by q4a** [comment] 2015-12-13 01:06
Still no solution? Just installed old pcmanfm (not qt) and drag-and-drop works fine when moving file to google chome.

**Comment by PCMan** [comment] 2015-12-13 18:28
Confirmed, but after some debugging, I think it's a bug in Qt 5.4.
The file dialog of Qt itself also has broken DND.
In Qt 4, you can drag a file from the file dialog to the browser and the browser can open that file.
With Qt 5.4, this no longer works.
Apparently, there's something wrong in the DND handling of Qt 5.4.
Need to do more tests and file a upstream Qt bug later.

**Comment by PCMan** [comment] 2015-12-13 18:29
I have checked my code for several times but unfortunately everything looks correct.
So, I highly suspect that it's a Qt bug.

**Comment by PCMan** [comment] 2015-12-14 12:20
I'm quite sure it's not our bug. Already report this to Qt developers.
https://bugreports.qt.io/browse/QTBUG-49947
Please keep an eye on it. Before it's fixed in upstream, there's not much we can do.

**Comment by q4a** [comment] 2015-12-14 14:55
Voted to QTBUG-49947. Hope somebody will fix it soon.

**Comment by PCMan** [comment] 2015-12-15 04:15
Found a related bug reported in August.
https://bugreports.qt.io/browse/QTBUG-47981
Please keep an eye on it as well.
Hope that it can be fixed soon. :-(

**Comment by q4a** [comment] 2015-12-15 11:28
Chromium has same issue: https://code.google.com/p/chromium/issues/detail?id=543940
But there is patch to Qt-5.5.1. Can somebody test it?

**Comment by palinek** [comment] 2015-12-15 12:15
Also dragging files from pcmanfm-qt to pcmanfm doesn't work, but it works vice-versa.

**Comment by tsujan** [comment] 2015-12-15 13:17
> Also dragging files from pcmanfm-qt to pcmanfm doesn't work, but it works vice-versa.

So, it's a general Qt5-GTK2 problem caused by Qt5. I think they'll fix it soon. If not, we might be able to devise a workaround later (as is the case with https://bugreports.qt.io/browse/QTBUG-42074)

**Comment by pmattern** [comment] 2015-12-21 22:01
Did some more tests. Firefox both compiled against GTK 2 or GTK 3, all Qt file managers compiled against Qt 5.5.1 unless otherwise noted, + → d&d works, - → d&d doesn't work.

| filemanager ("source" of d&d) | Firefox | Chromium | PCManFM |
| :--- | :--- | :--- | :--- |
| PCManFM-Qt | + | - | - |
| Dolphin | + | - | - |
| qtFM | + | - | - |
| qtFM (compiled against Qt 4.8.7) | + | + | - |
| Thunar | + | + | + 1) |

1) d&d moves objects instead of copying

So the problem addressed in this issue does not seem to affect GTK 2 in general as d&d works to Firefox compiled against GTK 2 or GTK 3.
It definitely seems to be due to some Qt 5 version.
The failure to drag & drop from PCManFM-Qt to PCManFM rather looks like a different problem as it doesn't work with qtFM compiled against Qt 4 either.

**Comment by PCMan** [comment] 2016-01-15 07:03
Since I'm the man of workarounds, I can't wait for the upstream.
Luckily, I found some possible ways to workaround this bug and it's a work in progress. :-)

**Comment by PCMan** [comment] 2016-01-15 16:03
Here is a PR to workaround the Qt bug.
https://github.com/lxde/pcmanfm-qt/pull/295#issuecomment-171997517

**Comment by PCMan** [comment] 2016-01-19 04:02
Already merged the workaround into pcmanfm-qt.
However, leave this issue open until the upstream Qt 5 bug is fifxed.

**Comment by pmattern** [comment] 2016-04-08 12:23
[QTBUG-45812](https://bugreports.qt.io/browse/QTBUG-45812) is another upstream bug involved. The other upstream bugs discussed here so far are mentioned, too.

**Comment by pmattern** [comment] 2016-04-26 11:21
Just to avoid eventual confusion: As of 2016-04-26 the commit fixing the problem was patched into the current stable release of `qtbase` on Arch Linux, see https://bugs.archlinux.org/task/48785.

**Closed** 2018-07-15 12:23 UTC
Labels: pcmanfm-qt, upstream
