### ISSUE TITLE
[pcmanfm-qt] Dropping dragged files on the places view or tabs does not work

### ISSUE THREAD

**Issue by theredbaron1834** [lxqt/lxqt#446] opened 2015-01-21 08:54 UTC
Pcmanfm-qt is missing the ability to drag and drop files to move/copy files/folders to anything except in the same folder. Such as dragging a file from ~/Downloads to a USB device via dragging said file to the device on the places menu. Or dragging said file to a new tab. Right now you have to copy and paste, and then delete the original file (or drop to CLI).

**Comment by paulolieuthier** [comment] 2015-01-21 10:00
This one is more urgent.

**Comment by PCMan** [comment] 2015-01-21 18:52
To be more specific, DND of files in the folder views works correctly.
It does not work when you drop the files on a place view item or a tab.

**Comment by paulolieuthier** [comment] 2015-01-21 19:08
Ops, sorry. I thought it was about dropping on another application's window.

**Comment by pmattern** [comment] 2015-01-24 20:20
@PCMan
> To be more specific, DND of files in the folder views works correctly.

This isn't quite right, I fear. d&d in Directory Tree view only works within the right pane. But dragging objects from the right pane to the left one, e. g. into a folder, or the other way around doesn't work either.

Also, I'd like to mention https://github.com/lxde/pcmanfm-qt/issues/100. It is about d&d to other applications but may be related to this one somehow.

**Comment by jleclanche** [comment] 2015-02-08 20:31
I'm just going to assume this is the 5.4 upstream issue.

**Comment by pmattern** [comment] 2015-02-09 11:41
All findings described here are the same if latest Git versions of LXQt including PCManFM-Qt get compiled against Qt 5.3.2 on Arch Linux (system as a whole at status just before regular repos were updated to Qt 5.4 to avoid artifacts).

So no, this does not belong to those Qt 5.4 woes and the issue has to be re-opened.

**Comment by pmattern** [comment] 2015-11-22 12:47
If I'm not mistaken another problem due to this is the failure to d&d objects from plugin-mainmenu to the desktop.
Drag & drop from `/usr/share/applications` opened in PCManFM-Qt itself works as expected, but trying to drag & drop from the main menu fails.
Problem had already been addressed in #381 which got closed a bit prematurely (but nevertheless does not need to get reopened as the underlying problem is discussed here now).

**Comment by tsujan** [comment] 2015-11-22 13:00
> ... trying to drag & drop from the main menu fails

Oh, it not only fails but, in my case, wants to copy the whole root directory (`'/'`) on desktop!! I hadn't tried it before.

**Comment by tsujan** [comment] 2015-11-22 13:12
In addition, the "move" menu-item should be disabled for dragging from a non-user directory.

**Comment by tsujan** [comment] 2015-11-22 13:52
Does anybody dare to try to drag a menu-item from the main menu to Desktop and click "Copy here"? If you get the same result I did, please give a high-priority label to this issue!

**Comment by tsujan** [comment] 2015-11-23 23:53
First of all, I don't want to cause panic.

Today I checked the DND code in pcmanfm-qt and found nothing wrong. Then I dared to drag an item from the main menu and drop it on Desktop again but this time, I canceled DND. A few hours later, a series of strange things, that I had never encountered before, happened. First Skype stopped working, then pcmanfm-qt crashed (and restarted), then I saw that all my home folders belong to root, and yet the real story began when I rebooted: the boot process stopped, telling that the root partition couldn’t be mounted due to a corrupted orphan linked list. I manually ran fsck and it found several inconsistencies. Fortunately, everything became OK after that.

Now, I'm absolutely not sure that the DND was the cause. However, the first time I did the DND in question, it started to copy the root directory and, after the second time, the above problem happened. This deserves an examination by PCMan, IMHO.

**Comment by pmattern** [comment] 2015-11-24 14:37
Running recent VCS checkouts on Arch Linux the findings are somewhat different.
First there's a dialog displaying possible actions
![dnd_initial-dialog](https://cloud.githubusercontent.com/assets/9860801/11366834/0c52b4e0-92b0-11e5-8070-5bc06c574bc9.png)
If any except "Cancel" is chosen another dialog informs about the action that's performed
![dnd_dialog-copy-files](https://cloud.githubusercontent.com/assets/9860801/11366839/15f93c58-92b0-11e5-8b63-a04214ccff1a.png)
which ends in a failure which is nor surprise as it's always the root directory that gets copied.
![dnd_dialog-error](https://cloud.githubusercontent.com/assets/9860801/11366844/1d0cb39e-92b0-11e5-8a1a-1a59206e3f01.png)
This message comes up after quite a while when the first attempt to copy etc. is made but at once the following times.
But in fact nothing gets copied in the desktop folder's directory or somewhere else in `/home/<user>`.

Maybe some incompatibility issue on your system? What OS is it and how did you install LXQt?

**Comment by tsujan** [comment] 2015-11-24 14:54
@pmattern 
In fact, that was exactly what happened to me the first time but I was too cautious to let it continue: I rebooted, systemd waited 90s for a process to end, and the boot was OK. It's definitely a bug because we chose a menu-item, not the root directory.

What about my second observation (clicking on Cancel)? I don't recommend you try it on your work computer though.

BTW, I always compile LXQT from Github.

**Comment by pmattern** [comment] 2015-11-24 18:34
Hm, whatever I try I can only reproduce the findings stated in my previous post, not those really grave ones you depict. This includes hitting `Cancel` while copying etc. is running which I hadn't done before.
Getting objects in $HOME owned by root for sure is something that shouldn't happen. Could this eventually be due to some remnants of tests regarding PCManFM-Qt vs. sudo / lxsu[do] and friends as e.g. discussed in https://github.com/lxde/lxqt/issues/874?

> BTW, I always compile LXQT from Github.

On?

**Comment by tsujan** [comment] 2015-11-24 19:33
> Getting objects in $HOME owned by root for sure is something that shouldn't happen.

Oh, that was just what file managers *showed* due to a grave inconsistency the partition got afterward. A simple fsck-ing fixed everything. I think, after hitting Cancel, some process continued to make "a corrupted orphan linked list", as the boot message said. However, I can't be sure.

I emphasize that all this is only about dragging from the main menu and dropping on the desktop. DND works OK *inside* pcmanfm-qt.

> On?

I grab the latest sources once in a while and make deb packages for my personal use offline. My distro is Debian Testing/Unstable and, as you may know, it usually doesn't provide bleeding-edge packages (which is OK to me because of stability).

**Comment by agaida** [comment] 2015-11-24 20:17
You are serious about the things you wrote? Really?

**Comment by tsujan** [comment] 2015-11-24 21:15
> You are serious about the things you wrote? Really?

What happened last night seemed *very serious* to me but (1) fortunately it was fixed easily and (2) I AM NOT SURE IT WAS PCMANFM-QT'S FAULT. I felt it would be helpful to tell the story.

**Comment by agaida** [comment] 2015-11-24 21:21
hmm - i'm not so experienced with debian, especially with unstable - long story short, i wrote the most of the packages from the scratch and never ever had any of such issues in nearly 4 years of debian/sid. a hint may be that the filesystem was already corrupted and the things got worse.

**Comment by tsujan** [comment] 2015-11-24 21:36
> never ever had any of such issues in nearly 4 years of debian/sid.

I've never had such an issue in the last 12 years ;) It was my first time.

> a hint may be that the filesystem was already corrupted and the things got worse.

That's possible. But I'll never drag a menu-item to the desktop until I completely understand why the whole root partition is seen as the DND source by pcmanfm-qt. In fact, in my last night experiments with the code, pcmanfm-qt saw the correct source (I used qDebug) and I thought there might be a deeper problem in libfm.

**Comment by agaida** [comment] 2015-11-25 22:24
ok - from this point of view - understandable :). It would be nice to know if there is a deeper problem with libfm-qt - or if one can force this behaviour reproducable.

**Comment by tsujan** [comment] 2015-11-25 23:59
@agaida  Oh, I admire your work at siduction -- now I know they were *your* clean packages I'd installed under Debian to have my first glance at LXQT about 8 months ago.

I would gladly work with you if it weren't for Kvantum (many feature requests, many good ideas by users, etc.), some personal projects (that may be uploaded someday), three icon themes, and now, LXQT's code (especially pcmanfm-qt's) -- they take most of my free time and more. However, thank you very much for the offer!

I hope you'll succeed in making bleeding-edge LXQT deb packages, usable under both siduction and Debian -- and, perhaps, Ubuntu and Mint too. Debian sid is always behind Arch in this respect, so I don't think the sid packages could replace yours.

**Comment by tsujan** [comment] 2015-11-26 12:05
@ everyone
I need your opinion about this if you're familiar with DND:

As far as I know, in the case of `Qt::IgnoreAction` (hitting Cancel after DND), the drop will be ignored *only if* `dropMimeData()` returns true, while `FolderModel::dropMimeData()` (in foldermodel.cpp) returns false on this occasion, which means the the action is *not* ignored.

**Comment by palinek** [comment] 2015-11-26 12:27
I may be lost... but you will not get into `FolderModel::dropMimeData()` if you hit cancel from the drop menu.  Because `FolderModel::supportedDropActions()` doesn't return `Qt::IgnoreAction` flag.

**Comment by tsujan** [comment] 2015-11-26 12:45
@palinek
> Because `FolderModel::supportedDropActions()` doesn't return `Qt::IgnoreAction` flag.

Thanks for the hint! I'll consult the Qt5 source to know what actually happens.

**Comment by palinek** [comment] 2015-11-26 12:46
Tried to drop an menu entry from panel to pcmanfm-qt (with some debuging) and I believe following issues are worth to think of:
- [here](https://github.com/lxde/pcmanfm-qt/blob/master/libfm-qt/foldermodel.cpp#L410) is no break... is it intentional? I think not and `dropMimeData` should return true in such case
- does plugin-mainmenu correcly create the URL? It should probably do something like following:
```diff
diff --git a/plugin-mainmenu/xdgcachedmenu.cpp b/plugin-mainmenu/xdgcachedmenu.cpp
index 11ac97b..32b15cb 100644
--- a/plugin-mainmenu/xdgcachedmenu.cpp
+++ b/plugin-mainmenu/xdgcachedmenu.cpp
@@ -161,7 +161,7 @@ void XdgCachedMenu::handleMouseMoveEvent(QMouseEvent *event)
 
     QList<QUrl> urls;
     char* desktop_file = menu_cache_item_get_file_path(a->item());
-    urls << QUrl(desktop_file);
+    urls << QUrl(QString("file://%1").arg(desktop_file));
     g_free(desktop_file);
 
     QMimeData *mimeData = new QMimeData();
```
-  if the DND is originated in plugin-mainmenu (QMenu) after the drop anything can be selected, but the action is always `Qt::CopyAction` in `dropMimeData()`

**Comment by palinek** [comment] 2015-11-26 12:54
I've just saw the `/` copying... and it is definitely caused by the wrong URL assembly in plugin-mainmenu. I'll commit the fix into lxqt-panel. But pcmanfm-qt/libfm-qt should be updated too to deny handling of malformed URLs.

**Comment by palinek** [comment] 2015-11-26 12:59
FYI: lxde/lxqt-panel@15ab453

**Comment by tsujan** [comment] 2015-11-26 14:19
This time, I may be totally lost but supportedDropActions() seems to be called only by supportedDragActions(), which in the case of dragging a menuitem from the main menu, isn't called by pcmanfm-qt.

I think a line like `if(action == Qt::IgnoreAction) return true;` doesn't do any harm.

**Comment by palinek** [comment] 2015-11-26 14:26
> I think a line like if(action == Qt::IgnoreAction) return true; doesn't do any harm.

IMO `FolderModel::dropMimeData()` is never called with action == Qt::IgnoreAction

**Comment by tsujan** [comment] 2015-11-26 19:15
> IMO `FolderModel::dropMimeData()` is never called with action == Qt::IgnoreAction

Apparently you're right and I should admit that I've got a "dragophobia" after my last experience ;)

**Comment by palinek** [comment] 2015-11-26 19:18
@tsujan are you going to have a look on the misbehaviour for case when dropped mime data has malformed URL ?

**Comment by tsujan** [comment] 2015-11-26 19:48
@palinek 
Oh, yes! As for `Qt::LinkAction`, I agree with you too. Let's wait until pcmanfm-qt and libfm-qt are completely separated from each other.

**Comment by palinek** [comment] 2015-11-26 20:03
> Oh, yes! As for Qt::LinkAction, I agree with you too. Let's wait until pcmanfm-qt and libfm-qt are completely separated from each other.

OK. But I meant the misinterpretation of URL in form `/some/path/to/file` as the `/` (while the form `file:///some/path/to/file` is interpreted correctly)

**Comment by tsujan** [comment] 2015-11-26 20:50
Yes. It needs a more thorough examination. Sometimes pcmanfm-qt doesn't correctly interpret paths with special characters in them either. If it weren't for libfm's dependency on glib, everything would be more straightforward.

**Comment by palinek** [comment] 2015-11-26 22:40
[here](https://github.com/lxde/libfm-qt/blob/master/src/foldermodel.cpp#L401) we probably need to check if any of the the parsed path is "root" as pathListFromQUrls -> fm_path_new_for_uri returns root in case it is unable to parse the URL.

**Comment by tsujan** [comment] 2015-11-26 23:00
pathListFromQUrls() is the junction between pcmanfm-qt and libfm. Like you, I think the problem is here. I should first gain a thorough understanding of libfm to know what happens when a QUrl is translated into an FmPath and why that translation is incorrect sometimes.

**Comment by tsujan** [comment] 2015-11-26 23:01
In other words, the problem may be in libfm.

**Comment by palinek** [comment] 2015-11-27 05:50
Based on libfm comments/doc it is a desired behaviour to return "root" when the URL is malformed.

**Comment by tsujan** [comment] 2015-11-27 12:10
@palinek 
What if we check all QUrls in `data->urls()` with `QUrl::scheme()`, remove those that have empty schemes and only then, feed them to `pathListFromQUrls()`?

**Comment by tsujan** [comment] 2015-11-27 14:59
I think the issue in question exists because, on the one hand, , QUrl works in `QUrl::TolerantMode` by default and, on the other hand, the static function `_fm_path_new_uri_root()` in `fm-path.c` (belonging to libfm) isn't so tolerant.

Therefore, testing QUrls against both `QUrl::isValid()` and `QUrl::scheme()` could be a solution if we don't want touch libfm.

**Comment by palinek** [comment] 2015-11-30 07:40
> Therefore, testing QUrls against both `QUrl::isValid()` and `QUrl::scheme()` could be a solution if we don't want to touch libfm.

I'm with you...but @PCMan does have a better knowledge about the `libfm` part and we may be missing something.

**Comment by tsujan** [comment] 2018-09-04 14:07
> Pcmanfm-qt is missing the ability to drag and drop files to move/copy files/folders to anything except in the same folder.

Not the case anymore and for a long time. As for the side-pane, there are open issues: https://github.com/lxqt/pcmanfm-qt/issues/566 https://github.com/lxqt/pcmanfm-qt/issues/299 https://github.com/lxqt/pcmanfm-qt/issues/631

**Closed by tsujan** 2018-09-04 14:07 UTC
Labels: upstream
