### ISSUE TITLE
plugin-mainmenu not focussed if opened by keyboard shortcut

### ISSUE THREAD

**Issue by Schwefelsaeure** [lxqt/lxqt#401] opened 2014-12-02 20:30 UTC
When opening the main menu with default shortcut "Alt + F1", the arrow keys cannot be used to navigate through the menu.

When opening the main menu with mouse, arrow keys work as expected. I guess the main menu does not get the focus when opened by shortcut "Alt + F1". This behavior was noticed in LXQt 0.8.0 with Qt 5.3.2 running Arch Linux.

**Comment by PCMan** [comment] 2015-01-30 12:22
@paulolieuthier if I revert your previous fix, I can reproduce this bug again.

**Comment by paulolieuthier** [comment] 2015-01-30 12:32
I can't get Qt to activate/focus the menu when triggering it through the shortcut. If I turn the menu to a dialog it works. Looks like a bug in Qt.

**Comment by paulolieuthier** [comment] 2015-01-30 12:35
Even when I connect the shortcut's signal to the button's click slot instead of to the `showHideMenu` slot. It appears to me to be a bug related to the panel's focus, as you said [here](https://github.com/lxde/lxqt-panel/blob/master/panel/lxqtpanel.cpp#L130).

**Comment by PCMan** [comment] 2015-01-31 21:58
A new PR for it.
https://github.com/lxde/lxqt-panel/pull/131
@paulolieuthier please help review.
Thanks!

**Comment by PCMan** [comment] 2015-02-03 20:00
fixed in git.

**Comment by pmattern** [comment] 2015-07-26 13:40
Findings exactly as described in first comment can be made again running latest VCS checkouts of all LXQt components on Arch Linux i686 or x86_64.
In addition hitting `Esc` doesn't close the menu either if it was opened by keyboard shortcut which is probably due to the same underlying problem.

**Comment by palinek** [comment] 2015-07-27 05:14
This problem is not seen here (debian testing + siduction)... maybe another QT fixup/regression?

**Comment by pmattern** [comment] 2015-07-27 15:32
The problem can also be seen on Lubuntu 15.04 running LXQt from ppa:lubuntu-dev/lubuntu-daily and Siduction running LXQt from their repos here. On the latter it didn't exist when I logged in for the first time today but could be seen constantly afterwards for whatever reason.
It doesn't exist running LXQt 0.9.0 on Arch Linux but I'm not sure whether this is too meaningful as those packages are still the ones compiled against Qt 5.4 while 5.5 is used by the distribution in the meantime.
Your findings on Debian testing seem strange to me: I can't get LXQt from the Siduction repos running on it since some weeks. The sessions always start but later I'm thrown back to display manager or virtual terminals receiving messages like these http://paste.siduction.org/20150722180918. Problem was already discussed with @agaida who was assuming some dependency issues as reason. But I suppose your system is up-to-date, isn't it?

**Comment by palinek** [comment] 2015-07-27 15:48
> But I suppose your system is up-to-date, isn't it?

Yes, it is. It's realy strange for me to heare that every other system has such problem, just me not :)

**Comment by pmattern** [comment] 2015-07-27 15:53
> Yes, it is. It's realy strange for me to hear that every other system has such problem, just mine not :)

Sure. Of course I was wondering whether I may have screwed something here but didn't get aware of anything. Also, I'm seeing it on three different distributions two of which are testing systems where I normally configure just nothing.
Weird...

**Comment by paulolieuthier** [comment] 2015-09-11 14:21
I'm no longer able to reproduce it, using both KWin and Openbox. @pmattern can you still reproduce it?

**Comment by pmattern** [comment] 2015-09-11 18:51
@paulolieuthier 
Yes, but it doesn't always happen.
It can be seen if the keyboard shortcut to open the menu is hit (i) on a virtual desktop that doesn't contain a window at all (ii) on a virtual desktop which does contain windows which are all minimized (iii) right after typing in another application e. g. type in QTerminal and hit the shortcut right thereafter.
It's affecting Openbox and KWin here while Xfwm isn't affected.

**Comment by paulolieuthier** [comment] 2015-09-11 19:19
Still can't.

**Comment by pmattern** [comment] 2015-09-12 21:51
@paulolieuthier 
Unfortunately I still can reproduce it as stated in my previous post. Even tried on a new user profile and made the same findings. No clue what's going on here.

**Comment by palinek** [comment] 2015-10-22 09:00
> It can be seen if the keyboard shortcut to open the menu is hit (i) on a virtual desktop that doesn't contain a window at all (ii) on a virtual desktop which does contain windows which are all minimized (iii) right after typing in another application e. g. type in QTerminal and hit the shortcut right thereafter.
It's affecting Openbox and KWin here while Xfwm isn't affected.

I can't reproduce it either.

**Comment by tsujan** [comment] 2020-01-25 21:35
Why is this still open?

**Comment by stefonarch** [comment] 2020-01-25 21:42
Cannot reproduce in debian buster either, works perfectly without mouse only keyboard.

**Comment by tsujan** [comment] 2020-01-26 12:09
OK, I succeeded in reproducing this problem while scrolling in pcmanfm-qt's icon view:

 1. I chose a folder with many files.
 2. I scrolled it by turning the mouse wheel fast inside the icon view.
 3. I quickly pressed `Alt+F1`.

Then the main menu did NOT have focus.

Since this was a problem since 2014, there may be a fundamental mistake in the code.

**Comment by tsujan** [comment] 2020-01-26 12:14
OK, I can also reproduce it while Falkon is open and mouse wheel is rotated inside its view -- as in the case of pcmanfm-qt.  With FeatherPad, it's a little harder but it can be seen in the same way.

**Comment by stefonarch** [comment] 2020-01-26 17:03
Yep, here also just by clicking  in any  window and then alt+f1 and arrows, the arrows will action in the window.

**Comment by tsujan** [comment] 2020-01-26 17:16
The bad thing about it is that it's random. Although I can see it whenever Falkon is under the cursor, it sometimes happen with pcmanfm-qt, sometimes not. So, most probably, it may happen to some users more than others.

Tomorrow I'll take a look at the code.

**Comment by stefonarch** [comment] 2020-01-26 17:19
Here it's not random at all,   it doesn't steal the focus, only with new windows opened and never clicked in them.

**Comment by tsujan** [comment] 2020-01-26 17:27
> it doesn't steal the focus

Good point. It doesn't here either.

Sometimes, the problem gets more serious because when I click somewhere outside the menu, it won't be closed. That's very bad; may be an old Qt bug, for which we need a workaround...

**Comment by tsujan** [comment] 2020-01-26 19:46
I played with the code for one boring hour and reached the obvious conclusion: this is a nasty Qt bug. If, for whatever reason, the menu loses its property of being the active window, it shouldn't remain visible because it's a menu.

I tried to find a clean workaround by experimenting with various codes to no avail — from requesting the active state for the window handle to grabbing the keyboard on showing the menu (I didn't try to grab mouse because that's very dangerous but it wouldn't be successful either).

The only workaround that worked was already in the code: increasing the time-out. Time-out workarounds are "dirty" but I'm afraid we might have no other option. We could increase 200 in this line and do tests: https://github.com/lxqt/lxqt-panel/blob/0977d45560a97160b8f09fdabade17d824088b78/plugin-mainmenu/lxqtmainmenu.cpp#L76

@palinek ?

**Comment by tsujan** [comment] 2020-01-27 16:02
Just for the fun of it:

A real screenshot that shows two separate Qt menus belonging to 2 different apps, shown simultaneously:

![2_menus](https://user-images.githubusercontent.com/981076/73190676-95c7da00-413b-11ea-8602-4f9978e4f58a.png)

Here, it's very easy to take such a screenshot: I click inside pcmanfm-qt immediately after pressing `Atlt+F1`; then, I can open any menu in pcmanfm-qt without cloning LXQt's main menu.

**Comment by tsujan** [comment] 2020-01-28 12:41
UPDATE:

I attacked the problem again and found a clean workaround (that doesn't involve a time-out). Will make a PR after some tests.

**Comment by stefonarch** [comment] 2020-12-18 18:59
Is this still valid? A fast test resulted in no issue with shortcut and arrow key navigation here.

**Comment by tsujan** [comment] 2020-12-18 19:11
Yes, it's valid. Qt's handling of menus is terrible, whether under X11 or Wayland. I know that firsthand (https://github.com/tsujan/Kvantum/blob/07c0aeb7f1c4dbfdce98b7004528fb94d2dcb7a4/Kvantum/style/drag/windowmanager.cpp#L266).

I changed the label to "qt5".

**Comment by tsujan** [comment] 2020-12-18 19:23
Because it's a Qt issue, it can be closed; can't it?

**Comment by stefonarch** [comment] 2020-12-18 21:06
Fun fact: on debian it works as I said, on arch not. 
+1 for closing.

**Comment by tsujan** [comment] 2020-12-18 21:13
It isn't about distro. I'm 100% sure that this is Qt bug because I've encountered lots of unfocused, simple menus in other places. They happen rarely (although I know how to "invite" them), under X11 and Wayland alike, but not under usual circumstances. However, they shouldn't happen if Qt didn't have bugs.

**Closed by tsujan** 2020-12-18 21:13 UTC
Labels: bug, qt5
