### ISSUE TITLE
Osmo don't work with our systemtray

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1469] opened 2018-03-27 20:08 UTC
##### Expected Behavior

osmo should start minimized in tray or as normal window with a tray icon

##### Current Behavior

osmo starts, but don't create a running tray icon - only a short blinking - so there is nothing like closing the applicatiion and have it running in the tray

##### Possible Solution

fix that?

##### Steps to Reproduce (for bugs)

1. install osmo, start osmo 
2. an trayicon should be created
3. go to settings and remove and set the enable systemtray hook - an icon is shown

##### Context

i can't run osmo as tray app - that make the whole application senseless

##### System Information
current sid, current git, Qt 5.9.2

**Comment by tsujan** [comment] 2018-03-27 20:13
Does it work with KDE's tray?

**Comment by agaida** [comment] 2018-03-27 20:18
yes - without flaws, just tested

**Comment by tsujan** [comment] 2018-03-27 20:22
Interesting! So, either our tray has a problem or KDE's tray has a workaround.

**Comment by tsujan** [comment] 2018-03-27 20:34
Osmo uses the old tray and the problem is there. Here, the needed space is given to its tray icon for a moment but, immediately after that, the space is removed and the icon isn't added.

**Comment by tsujan** [comment] 2020-06-24 19:42
The tray icon is shown after https://github.com/lxqt/lxqt-panel/pull/1428 (which reverses an old workaround) but its behavior is problematic. I close this because System Tray is obsolete. Osmo should either start to use AppIndicator through `ibappindicator-gtk2` or be forgotten.

**Closed by tsujan** 2020-06-24 19:42 UTC
Labels: lxqt-panel
