### ISSUE TITLE
Add proper mimetype handling 

### ISSUE THREAD

**Issue by hawkeyed** [lxqt/lxqt#35] opened 2014-03-25 20:09 UTC
Hello, I really appreciate what you're doing here.When I click "Open Directory" or "Open containing folder" and such thing in other programs,it opens my web-browser Qupzilla not pcmanfm-qt.It could be related to lxqt-config-file-associations.inode/directory option was already set to pcmanfm.There is no file:// association under the uri category.I hope you can fix it.

**Comment by tsujan** [comment] 2016-08-07 09:57
Today I installed LXQt from the latest github sources on a newly installed Manjaro (because of migration from Debian) and encountered exactly the issue that @hawkeyed mentioned. Of course, I can make pcmanfm-qt the defualt file manager but, although the problem will be fixed under LXQt, folders will be opened by pcmanfm-qt under KDE by default.

Under Debian, I didn't have KDE and Dolphin, so there was no issue. But here, every time I want to log into KDE, I should remove pcmanfm-qt from the list of default apps (in `~/.config/mimeapps.list`).

**Comment by tsujan** [comment] 2016-08-07 10:00
BTW, as @LStranger told, it's `inode/directory`, not `x-scheme-handler/file`.

**Comment by Vladimir-csp** [comment] 2016-08-07 10:01
The spec allows to DE-specific associations https://specifications.freedesktop.org/mime-apps-spec/latest/ar01s02.html

**Comment by tsujan** [comment] 2016-08-07 10:08
@Vladimir-csp Thanks a lot! That solved my problem. I didn't know about DE-specific associations.

However, we couldn't expect an average LXQt user to do such things.

**Comment by luis-pereira** [comment] 2016-08-07 13:22
After the release (and vacations) I will add that feature to libqtxdg.

**Comment by tsujan** [comment] 2016-08-09 23:04
@luis-pereira, the problem is deeper.

In an app (a notes manager), I use `QDesktopServices::openUrl()` to open links. Under KDE, links are always opened correctly. For example, if the link is `~/Desktop/mytext.txt` (`.txt` isn't needed), it'll be opened by the text editor. That's actually what `QDesktopServices::openUrl()` does.

However, the same link is opened by Firefox under LXQt!

In fact, the reason why I wanted a way to set the default file manager was that, with the same app, directory links were also opened by Firefox under LXQt, while they were opened (correctly) by Dolphin under KDE.

Does libqtxdg affect the behavior of `QDesktopServices::openUrl()`? How?

**Comment by palinek** [comment] 2016-08-10 06:46
> In an app (a notes manager), I use QDesktopServices::openUrl() to open links. Under KDE, links are always opened correctly.

I may not fully understand this topic, but do you have `xdg-utils`  installed? Looking into the [Qt code](https://github.com/qt/qtbase/blob/dev/src/platformsupport/services/genericunix/qgenericunixservices.cpp#L153) and the [detectWebBrowser() function](https://github.com/qt/qtbase/blob/dev/src/platformsupport/services/genericunix/qgenericunixservices.cpp#L83), this seems like what you're observing -> for KDE the `kfmclient` is used and for other envs one of `const char *browsers[] = {"google-chrome", "firefox", "mozilla", "opera"};`

**Comment by tsujan** [comment] 2016-08-10 07:05
@palinek 
Yes, I have xdg-utils. My problem is that, apparently, `QDesktopServices::openUrl()` opens all local files (file:///..) with the default browser instead of appropriate apps.

However, I admit that I shouldn't have blamd LXQt so soon! `xdg-open` shows the same behavior. What I told above occurs on *Manjaro*. On Debian, the links are opened correctly under LXQt too. Something is wrong with Manjaro's default settings and I should find it.

BTW, thanks for the `kfmclient` hint!

**Comment by tsujan** [comment] 2016-08-10 11:20
For the record:

The problem was because `perl-file-mimeinfo` (`libfile-mimeinfo-perl` in Debian) wasn't installed! Without it -- and when `XDG_CURRENT_DESKTOP` is *not* GNOME, KDE or XFCE -- `xdg-mime` only consults `/usr/share/mime/magic` to know about the mime type and so, `xdg-open` may use a wrong app, which causes `QDesktopServices::openUrl()` to do the same thing. (See `/usr/bin/xdg-mime → info_generic()`!)

**Comment by tsujan** [comment] 2016-08-10 11:54
IMO, recommending `libfile-mimeinfo-perl` at https://github.com/lxde/lxqt/wiki/Building-From-Source would be a good idea because LXQt is considered as a "generic" DE by xdg-mime.

**Comment by luis-pereira** [comment] 2016-08-12 14:14
@tsujan 

- `QDesktopServices::openUrl()` behaviour can be "modeled" throug the implementation of `QPlatformIntegrations::services()` and the consequent implemenation of `QPlatformServices`.

- I started to write an replacement of the current libqtxdg implementation of [Association between MIME types and applications](https://standards.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.1.html).

The combination of the two can solve the issue.

**Comment by tsujan** [comment] 2016-08-12 14:39
@luis-pereira 
Changing the behavior of `QDesktopServices::openUrl()` in the code wasn't the problem. Actually, I encountered two distinct issues, which are solved now:

(1)  Setting the default browser *only* for LXQt. This was solved by @Vladimir-csp's hint (https://github.com/lxde/lxqt/issues/35#issuecomment-238073815).

(2) The second issue is discussed (and solved) at https://github.com/lxde/lxqt/issues/1111.

Therefore, both issues are solved. *I don't think you need to change anything.*

**Comment by luis-pereira** [comment] 2016-08-12 14:48
Good.
The `XdgDesktopFileCache` implementation has to be rewritten anyway becouse it contains several bugs and some non implemented features.

**Comment by tsujan** [comment] 2016-08-12 15:37
I forgot to say that I encountered a bug related to https://standards.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.1.html:

If `~/.config/lxqt-mimeapps.list` is created, it works as expected for `[Default Applications]` but not for `[Added Associations]` and `[Removed Associations]`.

Of course, `~/.config/mimeapps.list` works OK.

**Comment by luis-pereira** [comment] 2016-08-12 15:41
@tsujan Yeap. That's one of the bugs. But there also some ordering issues.

**Comment by agaida** [comment] 2018-10-07 09:44
Renamed, it isn't about browsing directories/files in the first place. We really should add a proper mimetype handling if possible.

**Comment by tsujan** [comment] 2019-12-31 00:47
An old problem that was fixed by @luis-pereira (I didn't have time to find the link).

**Closed by tsujan** 2019-12-31 00:47 UTC
Labels: bug, feature request, high-priority
