### ISSUE TITLE
lxqt-panel placement with multi-monitor

### ISSUE THREAD

**Issue by Mister-Arkse** [lxqt/lxqt#1787] opened 2020-04-30 18:43 UTC
After upgrading LXQt from 0.14 to 0.15 the bottom panel on my primary monitor disappeared.
In the settings I can no longer set the panel to bottom of desktop 1 (primary monitor).

![image](https://user-images.githubusercontent.com/16281589/80745808-26d69480-8b21-11ea-9977-3a6c835935ce.png)

##### Expected Behavior
I should be able to set the panel bottom of desktop 1 like before.

##### Current Behavior
I can choose : 

Right of desktop 1
Top of desktop 2
Left of desktop 2
Bottom of desktop 2

* Distribution & Version: Arch Linux x86_64
* Kernel: 5.6.8
* Qt Version: 5.14.2
* liblxqt Version: 0.15.0
* Package version: 0.15.0

**Comment by tsujan** [comment] 2020-04-30 18:48
Let me explain the logic with an example (to use its link if another report is made):

With the following virtual screen, panels can be positioned at:

 1. Left of 1,
 2. Bottom of 1,
 3. Right of 2,
 4. Top of 2,

And nowhere else.

![screens](https://user-images.githubusercontent.com/981076/80747506-cce1c900-8b38-11ea-94a7-9a246c8063d2.png)

The reason is that, for example, if a panel could be positioned at the bottom of 2, window/menu maximization/positioning would be problematic with most window managers — an old issue that's avoided in 0.15.

**Comment by tsujan** [comment] 2020-04-30 18:52
If you want to put panels at the bottom of 1 *and* 2, align the bottoms of the screens -- they aren't aligned in your case -- and the same for top panels.

**Comment by Mister-Arkse** [comment] 2020-04-30 19:01
Thank you, I understand the logic and by doing that my previous panel was restored.
My monitor on the left is rotated that's why the bottom weren't aligned.

Is there a way to keep the monitor aligned and somehow offset the mouse when I move between screens?

**Comment by tsujan** [comment] 2020-04-30 19:11
> Is there a way to keep the monitor aligned and somehow offset the mouse when I move between screens?

You mean making the cursor jump upward/downward? If you have bottom panels on both screens, no. But if you don't use a bottom panel with screen 2, you could move it upward.

**Comment by Mister-Arkse** [comment] 2020-05-01 12:55
I tried but I can't do it, maybe I missed something or it's my setup, currently I'm like this : 

![image](https://user-images.githubusercontent.com/16281589/80806192-42da4480-8bba-11ea-894d-e3c5fabd1828.png)
DisplayPort-2 is screen 1, HDMI-A-0 is screen 2

Physically they're like this : 

![image](https://user-images.githubusercontent.com/16281589/80806306-9b114680-8bba-11ea-9ee4-92ec96bd8c5b.png)

Whatever I do, only screen 2 can have the bottom panel unless both bottom are aligned.

**Comment by tsujan** [comment] 2020-05-01 16:33
In your second screenshot, the panel should be able to be positioned at the visible bottom of HDMI-A-0 because it's below the visible bottom of DisplayPort-2.

**Comment by Mister-Arkse** [comment] 2020-05-01 17:17
Yes I understand that part, my issue is I want to have a bottom panel on DisplayPort-2 but with the setup on the second screenshot.

Right now, I can't have a bottom panel on DisplayPort-2 even if I remove the panel on HDMI-A-0.

Despite the fact that DisplayPort-2 is the main monitor, since HDMI-A-0 is on the left the desktop start here followed by DisplayPort-2.

At least that's how I understand it.

**Comment by tsujan** [comment] 2020-05-01 17:27
> Yes I understand that part, my issue is I want to have a bottom panel on DisplayPort-2 but with the setup on the second screenshot.

You say that you understand it, then you say something in the opposite direction ;) It's also possible that the misunderstanding is mine but I have no clue how.

> Right now, I can't have a bottom panel on DisplayPort-2 even if I remove the panel on HDMI-A-0.

With one screen, that should be impossible. If you have only one screen but can't put the panel at its bottom, please open another issue -- maybe a developer could reproduce and fix it.

> Despite the fact that DisplayPort-2 is the main monitor...

It doesn't matter which monitor is the main one.

**Comment by Mister-Arkse** [comment] 2020-05-01 17:30
So if I understand correctly, only the desktop matters?

Since HDMI-A-0 is on the left there is no way for me to have a bottom panel on DisplayPort-2 unless both bottom are aligned?

**Comment by tsujan** [comment] 2020-05-01 17:34
> Since HDMI-A-0 is on the left there is no way for me to have a bottom panel on DisplayPort-2 unless both bottom are aligned?

Being on the left/right doesn't matter. The bottom panel goes to the screen whose bottom is below the bottom of the other one. If the bottoms are aligned, panel's could be positioned at both of them.

**Comment by tsujan** [comment] 2020-05-01 17:42
Also see  https://github.com/lxqt/lxqt/issues/1703 and https://github.com/lxqt/lxqt/issues/1704 (among others) for the reason.

**Comment by Mister-Arkse** [comment] 2020-05-01 18:54
Thank you, now I understand, the "most" bottom or aligned bottoms will get the bottom panel.

I guess I will have to learn to live with the fact that I can't have a bottom panel on DisplayPort-2 unless both bottoms are aligned (in reference to the second screenshot).

The old behavior was perfect for my setup but I understand the reason of the change after looking at #1704

**Comment by tsujan** [comment] 2020-05-01 19:03
> The old behavior was perfect for my setup

I understand that -- another user complained about the new behavior too (I'm not saying you were complaining) -- but putting panels only on farthest edges was a solution to an annoying problem. I hope a different solution will be found by another dev; that was what I could do to get rid of the issue.

**Comment by thx1111** [comment] 2020-05-02 02:40
Well, obviously, I appreciate that you are resolving issues with panel placement.

I have now noticed that aligning the bottom edge of my three horizontally placed monitors will cause "Bottom of desktop <n>" to appear for all three "desktops" in the "Position" drop-down menu.  That work-around resolves my primary complaint, about being able to place the panel on the bottom of my preferred monitor.  By default, xrandr applies "left-of" and "right-of" by aligning the *top* edges of each display, so that xrandr "pos" must be used explicitly to have the bottom edges aligned.  There is a script that does that when lxqt starts.

I am also noticing that whatever is applying the background image gets confused about where the edge of the virtual screen is located, so that the background image only fills two of the three monitor screens, when lxqt-panel is first running.  Here, the background "Wallpaper mode" is set to "Stretch to fill the entire screen".  After killing the panel, the background image immediately fills all three monitor screens, as otherwise normal.  After restarting the panel, the background image remains in place, covering all three screens.  I've seen this issue with the background image, not filling the entire virtual screen, come and go in the past, but I've never really noticed a repeatable pattern.  In this case, I'm using the openbox window manager.

**Comment by tsujan** [comment] 2020-05-02 03:03
> I've seen this issue with the background image, not filling the entire virtual screen, come and go in the past.

@thx1111 
That may be because of an old Qt bug (the one responsible for https://github.com/lxqt/lxqt/issues/1735) or, if you use openbox, it can be caused by it (check https://github.com/lxqt/pcmanfm-qt/issues/1033). To rule out the second, you could try another WM, like KWin *(please do so!)*.

If none of them is relevant, please try to find a way of reproducing the issue with 2 monitors -- I don't have 3 screens and I don't think other LXQt devs do either.

A word about your comment at https://github.com/lxqt/lxqt-panel/issues/1390:

Like many users, you seem to be Gnome-bitten. Here, we try to fix problems, provided that they're reported in a reproducible way; we really don't have time for policy-making, let alone imposing policies on users.

**Comment by miopa** [comment] 2020-05-15 02:24
I just want to mention that this change has made LXQt practically unusable for my dual screen setup (I have identical software environment as OP).
Left monitor is primary display, I have one taskbar panel at bottom, and quick-launch at left side. The extension display on the right is bigger, and now no matter how I place it (top or bottom or middle align), there is one or other problem.

I'm using LXQt with two monitors for more than 5 years, and until some months ago, I was quite happy with it (I have found workarounds for most issues that annoyed me). What definitely broke it was when 'virtual' desktop stopped to reflect the size of the monitors, and now I can move the mouse in some non-existent invisible space over the top of the smaller monitor. I was pretty sure it was some obvious bug that will get fixed soon and didn't even bother to report an issue, but now after skimming this issue, it seems it was all intentional?

**Comment by tsujan** [comment] 2020-05-15 05:24
> ... and until some months ago, I was quite happy

Making a user "unhappy" isn't a sufficient condition for being a bug, as making another user "happy" doesn't justify a bug. So, instead of "happiness", we focus on fixing bugs.

**Comment by miopa** [comment] 2020-05-15 06:41
Agreed, we should focus on fixing bugs. I apologize for the unwarranted manifest of emotions, please have understanding that I'm a bit upset because the desktop environment I have used for so long is becoming unusable for me

**Comment by tsujan** [comment] 2020-05-15 06:56
> please have understanding that I'm a bit upset because the desktop environment I have used for so long is becoming unusable for me

I understand that but "unsuable" is a bit of exaggeration. Align the bottoms of your screens and you could have panels at the bottoms of all of them. And similarly for left, right or top, if you use left, top or right panels.

In addition, anyone who can solve the problem of window maximization with *all WMs*, without putting panels at the farthest edges of the virtual screen, is very welcome to make a PR (see the above-mentioned links to old issues).

**Comment by palinek** [comment] 2020-05-15 09:52
@tsujan How about allowing any edge of any screen in case the hiding is disabled? (just a thought)

**Comment by tsujan** [comment] 2020-05-15 10:07
@palinek 
Theoretically speaking, that should be possible if we exclude the places between screens.

BTW -- and unrelated to this report -- I think `KWindowSystem::setExtendedStrut()` may have a problem. I can't upgrade `KWindowSystem` on the laptop that I use for testing multiple screens, so, I can only hope the problem is fixed with later versions: *Apparently*, the available virtual geometry isn't reported correctly sometimes.

**Comment by tsujan** [comment] 2020-05-15 10:13
@palinek 
Sorry, I misread your comment.

Putting the panel on the *farthest* edges of the virtual screen was necessary for preventing maximization problems. It had nothing to do with auto-hiding. In the image of https://github.com/lxqt/lxqt/issues/1787#issuecomment-622035610, if we allowed a bottom panel on screen 2, window maximization (and some other things) would be damaged on screen 1.

**Comment by palinek** [comment] 2020-05-15 15:58
> Putting the panel on the farthest edges of the virtual screen was necessary for preventing maximization problems.

This (`Reserve space on display`) is also configurable in panel's config.

**Comment by tsujan** [comment] 2020-05-15 16:34
Yes, it is.

I have no problem with making exceptions for special cases, although I prefer a way of solving the maximization problem without putting panels at the farthest screen edges. KDE has no problem but I'm not sure it isn't because of KWin.

**Comment by tsujan** [comment] 2020-05-15 17:32
OK, in an experimental PR, I'll remove the limitation of "farthest edges" and only keep this condition: "No part of a panel should be between 2 screens." Then I'll do some tests to see if a maximization problem happens with the new conditions.

**Comment by tsujan** [comment] 2020-05-15 19:26
The patch is here: https://github.com/lxqt/lxqt-panel/pull/1404

With the following screens, it'll be possible to put the panel at the bottoms of screen 1 and screen 2 but not at the right of 1 or the left of 2:

![setting1](https://user-images.githubusercontent.com/981076/82088659-68f9fb80-9707-11ea-98ca-d7924984ca72.png)

But with this setting, the panel cannot be at the bottom of screen 2 because otherwise, a part of it might be above screen 1:

![setting2](https://user-images.githubusercontent.com/981076/82088677-70210980-9707-11ea-87f4-805191e8a436.png)

With the new conditions, which are less limiting than the previous ones, I didn't encounter any problem in my tests; hopefully, other users won't either.

**Closed** 2020-05-20 10:19 UTC

**Comment by miopa** [comment] 2020-05-25 15:19
Thanks, this landed in arch repos, solved the issue

**Comment by tsujan** [comment] 2020-05-25 15:27
Thanks for testing.
