### ISSUE TITLE
Desktop bookmarks

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#590] opened 2015-04-13 06:25 UTC
That is a tricky question.
Pcmanfm-qt now uses GTK bookmarks. Qt file dialogs (and most of the other Qt apps) do not use it. There are [XDG specs](https://wiki.freedesktop.org/www/Specifications/desktop-bookmark-spec/) for bookmarks (along with recent files and apps). IMHO they have a better shot at being cross-toolkit, and are already widely supported (at least in 'recently used' part, never saw these bookmarks implemented anywhere yet).

**Comment by jleclanche** [comment] 2015-11-01 07:10
@luis-pereira I'll assign this to you because i think it's more of a libqtxdg thing.

**Comment by luis-pereira** [comment] 2015-11-04 14:26
The best place to implement it is libqtxdg. But pcmanfm doesn't link to libqtxdg

**Comment by jleclanche** [comment] 2015-11-06 17:49
That's fine, it should.

**Comment by redtide** [comment] 2020-05-11 17:38
I'm not sure but if this is about the native Qt dialog this should be fixed upstream, isn't it?
Meanwhile I now see that the `QFileDialog` paths are stored in `$HOME/.config/QtProject.conf`.

**Comment by tsujan** [comment] 2020-05-11 17:45
Oh, these old reports won't be closed if new comments aren't added.

LXQt has its own native (Qt) file dialog (of course, it didn't in 2015).

**Closed by tsujan** 2020-05-11 17:45 UTC
Labels: feature request, pcmanfm-qt

**Comment by redtide** [comment] 2020-05-11 17:55
Well it seems to me the problem is still there, I see no bookmarks in current QFileDialogs, I had to edit manually that config file to have something useful.

**Comment by tsujan** [comment] 2020-05-11 18:03
Default Qt file dialogs aren't our file dialogs. If you don't see LXQt's native file dialog with a Qt app, either your LXQt installation is incomplete or that app enforces non-native dialogs everywhere.

**Comment by redtide** [comment] 2020-05-11 18:32
![qfiledialog](https://user-images.githubusercontent.com/1171962/81597596-42b22400-93c6-11ea-90fb-9aa08d94392e.png)
these are respectively QFileDialogs from QtCreator and LXImage-Qt; despite the different theme they looks about the same to me. The installation is a normal Arch distribution pacman install.

**Comment by tsujan** [comment] 2020-05-11 18:47
Then, your LXQt installation is incomplete -- if you're in an LXQt session at all.

![lxqt_file_dialog](https://user-images.githubusercontent.com/981076/81599066-8401fe00-93dd-11ea-8739-6871e0dd7115.png)

**Comment by redtide** [comment] 2020-05-11 19:52
then IDK what's going on here
```
$ pacman -Qe|grep lxqt
lxqt-about 0.15.0-1
lxqt-admin 0.15.0-1
lxqt-config 0.15.0-1
lxqt-globalkeys 0.15.0-1
lxqt-notificationd 0.15.0-1
lxqt-openssh-askpass 0.15.0-1
lxqt-panel 0.15.0-1
lxqt-policykit 0.15.0-1
lxqt-powermanagement 0.15.0-1
lxqt-qtplugin 0.15.0-1
lxqt-runner 0.15.0-1
lxqt-session 0.15.0-1
lxqt-sudo 0.15.0-1
lxqt-themes 0.15.0-1
```
and I'm using vanilla Archlinux
![lxqt-about](https://user-images.githubusercontent.com/1171962/81605371-a2fa9300-93d1-11ea-9a18-4793a0b2b770.png)

**Comment by tsujan** [comment] 2020-05-11 20:05
liblxqt, libqtxdg, libfm-qt, .... and probably more.

**Comment by redtide** [comment] 2020-05-11 20:28
libqtxdg 3.5.0-1
liblxqt 0.15.0-2
libfm-qt 0.15.0-1 (pcmanfm-qt works)

I wonder where the LXQT file dialog is included and which configuration files it uses, might be some old configurations from a previous LXDE environment? This is an old Archlinux installation.

**Comment by tsujan** [comment] 2020-05-11 21:11
Check whether you have `qt5ct`, which can ruin everything everywhere. The environment variable `QT_QPA_PLATFORMTHEME` should be `lxqt`.

**Comment by redtide** [comment] 2020-05-11 23:00
I've set it time ago as suggested by the configuration tool in `.bash_profile`, setting it to `lxqt` was not enough. Once I've set it also on `$HOME/.config/lxqt/session.conf` the file dialog magically changed to the expected one. Thank you!

**Comment by tsujan** [comment] 2020-05-12 05:20
`qt5ct` contradicts the concept of platform integration and interferes with it. It was made to continue a Qt4 tradition but Qt developers had a good reason to not make a config tool for Qt5.
