### ISSUE TITLE
Panel menu does not get updated when a menu's desktop file is updated.

### ISSUE THREAD

**Issue by jleclanche** [lxqt/lxqt#65] opened 2014-04-26 22:11 UTC

**Comment by Soukyuu** [comment] 2015-09-05 14:30
Is there any manual workarounds for this in the meantime?

**Comment by pmattern** [comment] 2015-09-05 14:33
> Is there any manual workarounds for this in the meantime?

Forgot to mention in #809: most of the time the workaround is to update the timestamp of the *.menu file in use manually. E. g. using the default one run `# touch /etc/xdg/menus/lxqt-applications.menu` as root.

**Comment by Soukyuu** [comment] 2015-09-05 15:15
Yes, that worked. Thanks!

**Comment by rapgro** [comment] 2015-09-18 14:14
:+1:

**Comment by pmattern** [comment] 2015-11-10 14:24
(Adding a milestone as I saw this masking lots of other issues in the meantime.)

**Comment by palinek** [comment] 2015-12-01 21:25
Is this still valid? I wasn't able to reproduce with current master neither with menu-cache (debian unstable) nor without it. (the menu entries are correctly updated if the shown .desktop file is updated)

**Comment by stefonarch** [comment] 2015-12-02 08:16
On arch with latest Aur packages updates  immediately the menu entries on change.
 (/usr/lib/menu-cache is present but no idea if it gets used)

**Comment by pmattern** [comment] 2015-12-06 00:19
Two findings can still be seen.

Updating `*.desktop` files while no LXQt session is running, e. g. when the corresponding package gets updated, can make them disappear from the menu.
This happens sporadically only and I spent quite some time trying to figure out the conditions when it takes place to no avail.

Submenu "Other" in main menu's top level persists all the time even if it has no content.
File `lxqt-applications.menu` isn't to blame as the problem cannot be seen using the very same file in Xfce. Also, menu-cache per se doesn't seem to be the culprit as the problem cannot be seen in LXDE either. But menu-cache definitely seems to be involved somehow as the problem cannot be seen if the panel gets compiled with cmake option `-DWITHOUT_MENU_CACHE=Yes`.
(Actually I thought we already had an issue about this but couldn't find it.)

By the way, if lxqt-panel gets compiled with  `-DWITHOUT_MENU_CACHE=Yes` any change regarding the menu gets applied after login out and in again only and both the values of keys `Name` and `GenericName` are displayed all the time.

Latest checkouts of all LXQt components on Arch Linux, new user profiles.

**Comment by palinek** [comment] 2015-12-07 10:13
> Submenu "Other" in main menu's top level persists all the time even if it has no content.

Why shouldn't it?

**Comment by pmattern** [comment] 2015-12-07 11:10
>> Submenu "Other" in main menu's top level persists all the time even if it has no content.

> Why shouldn't it?

Because empty topics are never displayed in menus.
Besides I don't know whether this behaviour is part of the specification it not only makes perfect sense IMO but moreover is the very same in all major desktop environments like KDE, LXDE or Xfce as well as LXQt with submenu `Other` being the only exception.
You may try and reproduce with any other submenu within the menu's top level like Games, Internet or Office. If you remove all corresponding desktop entry files `*.desktop` and hence nothing needs to be displayed any longer the submenu itself will disappear.

**Comment by palinek** [comment] 2015-12-07 12:19
There is a XDG spec for menu files: http://standards.freedesktop.org/menu-spec/menu-spec-1.0.html

I had a look into the code (with menu-cache) and I don't see any public API for getting the *(Default)Layout* information. But the tags are parsed/processed by menu-cache's internal logic => with menu-cache the *Other* menu entry should be filtered out and not presented to `mainmenu`.

@LStranger Is there a way for the menu-cache client to get information about the *Layout* or should it be handled internaly by menu-cache?

**Comment by LStranger** [comment] 2015-12-07 12:54
>I had a look into the code (with menu-cache) and I don't see any public API for getting the *(Default)Layout* information. But the tags are parsed/processed by menu-cache's internal logic => with menu-cache the *Other* menu entry should be filtered out and not presented to `mainmenu`.

>@LStranger Is there a way for the menu-cache client to get information about the *Layout* or should it be handled internaly by menu-cache?

That is exact, it is and have to be handled internally, since menu-cache
produces ready-to-use menu which requires no further processing.

In regards of your note - the 'Other' menu presence should be defined in
the .menu file, the 'show_empty' attribute of <DefaultLayout> tag defines
that behavior, in accordance to the XDG standard. If there is some case
where menu-cache handles it incorrectly then report that, please.

**Comment by palinek** [comment] 2015-12-07 14:05
The layout in our [case](https://github.com/lxde/lxqt-common/blob/master/menu/lxqt-applications.menu) is:
```xml
        <Layout>
                <Merge type="files"/>
                <Merge type="menus"/>
                <Separator/>
                <Menuname>DesktopSettings</Menuname>
                <Menuname show_empty="false" inline="true">LXQt-About</Menuname>
                <Separator/>
                <Menuname show_empty="false">X-Leave</Menuname>
                <Menuname show_empty="false" inline="true">Screensaver</Menuname>
        </Layout>
```

If we change it following way:
```diff
--- a/menu/lxqt-applications.menu
+++ b/menu/lxqt-applications.menu
@@ -222,7 +222,7 @@
                </Include>
        </Menu> <!-- End Screensaver -->
 
-       <Layout>
+       <Layout show_empty="false">
                <Merge type="files"/>
                <Merge type="menus"/>
                <Separator/>
```
... it correctly filters the *Other* menu entry.

@LStranger is such change valid? (as there is no such attribute for the *Layout* tag mentioned in spec)

**Comment by pmattern** [comment] 2015-12-07 14:09
`lxde-applications.menu` of LXDE does *not* comprise `show_empty="false"`, the corresponding panel plugin does use menu-cache, too, afaik yet the problem with submenu "Other" can not be seen.
Doesn't this suggest there's some problem in LXQt code and setting `show_empty="false"` is rather a workaround?

**Comment by LStranger** [comment] 2015-12-07 14:42
>If we change it following way:
>```diff
>--- a/menu/lxqt-applications.menu
>+++ b/menu/lxqt-applications.menu
>@@ -222,7 +222,7 @@
>                </Include>
>        </Menu> 
> 
>-       <Layout>
>+       <Layout show_empty="false">
>                <Merge type="files"/>
>                <Merge type="menus"/>
>                <Separator/>
>```
>... it correctly filters the *Other* menu entry.

>@LStranger is such change valid? (as there is no such attribute for the *Layout* tag mentioned in spec)

It is invalid and it is correctly ignored by menu-cache, only <DefaultLayout>
and <Menuname> tags' attributes are taken into consideration. You can test it
manually running menu-cache-gen with your menu file and then comparing files
it generates.

**Comment by palinek** [comment] 2015-12-07 14:57
> It is invalid and it is correctly ignored by menu-cache, only <DefaultLayout>
and <Menuname> tags' attributes are taken into consideration. You can test it
manually running menu-cache-gen with your menu file and then comparing files
it generates.

I've realized that... that was my faulty testing. But based the specification:
```
<DefaultLayout [show_empty="false"] [inline="false"] [inline_limit="4"] [inline_header="true"] [inline_alias="false"]>
The <DefaultLayout> element is an optional part of this specification. Implementations that do not support the <DefaultLayout> element should preserve any <DefaultLayout> elements and their contents as far as possible. Each <Menu> may optionally contain a <DefaultLayout> element which defines the default-layout for the current menu and all its sub-menus. If a menu has a <DefaultLayout> element then this will override any default-layout specified by a parent menu. The default-layout defines the suggested layout if a <Menu> element does either not have <Layout> element or if it has an empty <Layout> element. For explanations of the various attributes see the <Menuname> element. If no default-layout has been specified then the layout as specified by the following elements should be assumed: <DefaultLayout show_empty="false" inline="false" inline_limit="4" inline_header="true" inline_alias="false"><Merge type="menus"/><Merge type="files"/></DefaultLayout>
```
... I assume -> if there is no \<DefaultLayout\> in the menu, "empty" menus shouldn't be showed at all (this is our case).

**Comment by LStranger** [comment] 2015-12-07 15:02
You should also check if some menu file sourced by yours (the <MergeFile> tag)
contains the <DefaultLayout> tag, it would get into action after merging.

**Comment by palinek** [comment] 2015-12-07 15:03
There is no \<MergeFile\> either, you can see it [here](https://github.com/lxde/lxqt-common/blob/master/menu/lxqt-applications.menu)

**Comment by LStranger** [comment] 2015-12-07 15:16
>There is no \<MergeFile\> either, you can see it [here](https://github.com/lxde/lxqt-common/blob/master/menu/lxqt-applications.menu)

Well, there is a <DefaultMergeDirs/> tag there, it acts as <MergeFile> for every
applications-merged/*.menu file under all menu search paths, so you may have tons
of <MergeFile> from it actually, depending on their presence on your system.

**Comment by palinek** [comment] 2015-12-07 19:32
> Well, there is a <DefaultMergeDirs/> tag there, it acts as <MergeFile> for every
applications-merged/*.menu file under all menu search paths, so you may have tons
of <MergeFile> from it actually, depending on their presence on your system.

Even without \<DefaultMergeDirs/\> menu *Other* is still shown. However show/not show/ of this menu is seems to be connected to it's \<Include\> definition. Now it is defined as:
```xml
                <Include>
                        <And>
                                <Not><Category>Core</Category></Not>
                                <Not><Category>Settings</Category></Not>
                                <Not><Category>Screensaver</Category></Not>
                        </And>
                </Include>
```
... if I add at least one "positive" \<Category\>, e.g:
```xml
                <Include>
                        <And>
                                <Category>DontFindAnyOfSuchCategory</Category>
                                <Not><Category>Core</Category></Not>
                                <Not><Category>Settings</Category></Not>
                                <Not><Category>Screensaver</Category></Not>
                        </And>
                </Include>
```
... the *Other* menu is not shown. This seems to me as a discrepancy (if not even a bug).

**Comment by pmattern** [comment] 2015-12-09 12:23
FWIW release 1.0.1 of menu-cache doesn't have an impact on the display of submenu "Other". (I had assumed it eventually could have as tag `<OnlyUnallocated/>` is mentioned in [NEWS](https://github.com/lxde/menu-cache/blob/master/NEWS).)

**Comment by paulolieuthier** [comment] 2016-06-01 02:04
@LStranger ping.

**Comment by LStranger** [comment] 2016-06-01 11:04
The conversation here is confusing. It was about another issue (see the
issue subject) initially. Don't mix several issues into a single, please,
and open separate issue report for incorrect handling of 'show_empty'
setting as I suggested above and let fix it, not for lxqt panel but for
menu-cache instead. Thank you.

**Comment by palinek** [comment] 2016-06-01 11:14
lxde/menu-cache#10

**Comment by palinek** [comment] 2016-06-01 11:18
> The conversation here is confusing. It was about another issue (see the
issue subject) initially. Don't mix several issues into a single, please,
and open separate issue report for incorrect handling of 'show_empty'
setting as I suggested above and let fix it, not for lxqt panel but for
menu-cache instead. Thank you.

But why didn't you say it back then? Half a year ago it was OK to discuss it here and now it isn't...

**Comment by paulolieuthier** [comment] 2016-06-01 12:04
@LStranger: IMO it would be confusing if more than one topic were being discussed concurrently, which is not the case. The discussion moved completely to this specific bug. But anyway, you are technically correct. Let's continue discussing it in lxde/menu-cache#10.

**Comment by paulolieuthier** [comment] 2016-06-28 13:25
Is there anything from the original issue to be discussed?

**Closed as completed** 2018-05-23 21:01 UTC
Labels: lxqt-panel
