### ISSUE TITLE
changing width in lxqt-panel leads to lxqt-panel crash and window decorations of browser gone. 

### ISSUE THREAD

**Issue by shirishag75** [lxqt/lxqt#1602] opened 2018-10-29 20:49 UTC
I was changing the width of the panel via config panel and it crashes. It does save the setting but the session crashes. The window decorations on the browser are gone and can't do anything except to go to CTRL+ATL+F1 and either stop the display manager and do a new session or reboot the system. In either case, it works but only after that doing that. 
![configuration-panel-changes](https://user-images.githubusercontent.com/727626/47679364-1ec72d00-dbea-11e8-8a33-464d79cc7103.png)

These were the changes I was trying to do. 

I am not sure though what Reserve space on display means, I don't get what is meant by that.

**Comment by tsujan** [comment] 2018-10-29 20:56
Can't reproduce this either.

Crash → Backtrace is very important.

**Comment by tsujan** [comment] 2018-10-29 20:58
For some reason unknown to me, your LXQt installation is very unstable.

**Comment by shirishag75** [comment] 2018-10-29 20:59
While I could reproduce it I don't know how to share it with you.

**Comment by tsujan** [comment] 2018-10-29 21:10
> I don't know how to share it with you.

With a backtrace.

**Comment by tsujan** [comment] 2018-10-29 21:35
> The point is how do I do a backtrace

Like you did it very well here: https://github.com/lxqt/qterminal/issues/504 but with `lxqt-panel` instead of `qterminal`. Don't forget `dbgsym`!

**Comment by agaida** [comment] 2018-10-29 23:13
and for god sake - please check for running daemons that might provide things via dbus to applications - a few of them are specific to the used DE and it would be bad (aka lead to chrashes) when these daemons fire settings to applications. The only daemon in that is known working is the qtplugin and xsettingsd - so if there are things running from the former installation (mate i guess) that might lead to crashes.

**Comment by tsujan** [comment] 2019-01-27 14:54
No backtrace and not reproducible. Closing.

**Closed by tsujan** 2019-01-27 14:54 UTC
