### ISSUE TITLE
 Bug in LXQT Theme

### ISSUE THREAD

**Issue by SoheilFM** [lxqt/lxqt#2511] opened 2023-12-27 19:21 UTC
Hello, I've come across an issue with the new lxqt 1.4 update which was absent in 1.3, after upgrading lxqt 0.17 on ubuntu server 22.04 with the ppa:lubuntu-dev/backports to 1.4 upon changing the theme with the check mark to use the theme's wallpaper the supposed elements change but the background turns solid black To resolve this, I've had to manually right click on the desktop and choose the background manually and immediately upon reselecting the other themes we encounter the same problem which was not present in version 1.3.

**Comment by Bluey26** [comment] 2024-02-08 18:59
Hello, i can reproduce it in arch linux, and i think the problem is related to pcmanfm-qt, because i have had a similar issue with a custom action. (Check https://github.com/stefonarch/custom-actions/issues/7 )

For some reason, if i do not add the `--wallpaper-mode=stretch` in the following command:

`pcmanfm-qt --wallpaper-mode=stretch -w ABSOLUTE_PATH_TO_WALLPAPER`

the background turns black, because the wallpaper mode changes, from the stretch(the one i use), into 'color' mode.
(Somehow, ` --wallpaper-mode=color` is added if not wallpaper-mode is specified)

Reproducing the steps detailed in the issue, by opening Appareance, marking 'Use wallpaper provided by theme' and changing the theme, turns the background blackfor me (changes the mode to solid color). To solve this, i need to change the wallpaper mode.

This may be related to a recent change into the 'wallpaper-mode' command:

https://github.com/lxqt/pcmanfm-qt/pull/1822

Maybe it would be possible to make pcmanfm-qt to 'do not change' the wallpaper mode if one is not specified?

`Pcmanfm-qt version: 1.4.0`

**Comment by tsujan** [comment] 2024-02-08 21:20
Yes, there seems to be a regression somewhere. Thanks for reporting!

**Comment by tsujan** [comment] 2024-02-08 22:02
The PR that should fix it is here https://github.com/lxqt/pcmanfm-qt/pull/1858

pcmanfm-qt 1.4.1 will be released when it's approved and merged.

**Comment by stefonarch** [comment] 2024-02-09 07:28
> Reproducing the steps detailed in the issue, by opening Appareance, marking 'Use wallpaper provided by theme' and changing the theme, turns the background black for me (changes the mode to solid color). To solve this, i need to change the wallpaper mode.

Repeating doesn't turn black anymore with the fix, but changes never wallpaper now, if the path in` --desktop-preferences`  is left empty it will always be the color switching themes.

**Comment by tsujan** [comment] 2024-02-09 13:27
@stefonarch 
Probably you tested the Qt6-based pcmanfm-qt, while this is about the current Qt5 version.

**Comment by tsujan** [comment] 2024-02-09 14:30
> but it didn't work on the fix PR too.

The purpose of the PR is clear. It has nothing to do with anything other than pcmanfm-qt.

**Closed** 2024-02-09 18:32 UTC
Labels: bug

**Comment by sfalken** [comment] 2024-02-10 18:01
Should be in openSUSE Tumbleweed when the next image gets built/released, so probably Monday (12-Feb)

**Comment by tsujan** [comment] 2024-02-12 00:25
> Should be in openSUSE Tumbleweed when the next image gets built/released, so probably Monday (12-Feb)

Thanks!

Then, openSUSE Tumbleweed is faster than Arch :)

**Comment by sfalken** [comment] 2024-02-12 17:49
We try to stay on top of things.
