### ISSUE TITLE
Task manager terminal icon change on bell

### ISSUE THREAD

**Issue by picorealm** [lxqt/lxqt#1753] opened 2019-10-26 05:04 UTC
Terminal application icon on the task manager changes to a bell icon when the terminal emits a bell (even when all notifications are disabled in e.g. konsole).

##### Expected Behavior
Icon for terminal application in task manager remains the same.

##### Current Behavior
The icon for konsole on the task manager changes to a bell icon and remains permanently as a notification (bell) icon.

##### Possible Solution
In lxqt Desktop Notifications settings under Advanced Settings -> Ignore these applications I have listed Konsole,konsole.  Does not have any effect on the problem.

##### Steps to Reproduce (for bugs)

1. Open konsole and hit the backspace key or perform other activity that produces a bell event.

##### Context

The icons for terminal sessions in the task manager are incorrect.

##### System Information

* Distribution & Version: Debian GNU/Linux bullseye/sid amd64
* Kernel: 5.3.0-1-amd64 #1 SMP Debian 5.3.7-1 (2019-10-19) x86_64 GNU/Linux
* Qt Version: 
* liblxqt Version: 0.14.1-4
* Package version: 0.14.1-1

**Comment by tsujan** [comment] 2019-10-26 05:11
Please attach a screenshot of the panel when the icon of Konsole's task manager button changes!

Also, please attach `~/.config/konsole.notifyrc` and `~/.config/konsolerc` as zipped files.

**Comment by picorealm** [comment] 2019-10-26 05:29
![konsole task manager icon before](https://user-images.githubusercontent.com/41875886/67614722-bec08380-f776-11e9-9054-f47e53a49da8.jpg)
![konsole task manager icon after](https://user-images.githubusercontent.com/41875886/67614724-c2540a80-f776-11e9-85a2-c871a497953c.jpg)
[konsole.notifyrc.gz](https://github.com/lxqt/lxqt/files/3774481/konsole.notifyrc.gz)
[konsolerc.gz](https://github.com/lxqt/lxqt/files/3774482/konsolerc.gz)

**Comment by picorealm** [comment] 2019-10-26 05:31
If you can't reproduce it I recommend checking a couple things on your system:
1.  see if you have ~/.inputrc  with configuration option to disable bell
2.  see if anything related to bell is set in your env:
    $ env |grep -i bell

**Comment by tsujan** [comment] 2019-10-26 07:30
OK, this is not as simple as it seems:

  1. First of all, it isn't related to `Desktop Notifications → Advanced Settings → Unattended Notifications → Ignore these applications`. The list is for ignoring *Unattended Notifications* and the GUI is explicit about that. If `Konsole` is added to the list, its unattended notifications won't be remembered. So, there's no problem here.

  2. It happens only with some icon themes when `Task Manager Settings → Appearance → Use icons by window class` is checked. Breeze and Oxygen trigger it. (This was the reason I couldn't reproduce it at first.)

  3. It happens with all icon themes if the above-mentioned task manager option is unchecked.

(3) is understandable but I don't know yet why (2) happens and how those icon themes are different.

**Comment by picorealm** [comment] 2019-10-26 07:45
"Use icons by WindowClass, if available" was unchecked in my settings and I was using the Breeze icon theme.  I have just done a test and enabled "Use icons by WindowClass, if available"  and switched to the Tango and Obsidian icon themes and still getting the problem.

**Comment by picorealm** [comment] 2019-10-26 07:55
Just an update for reference purposes: This problem is *not* happening with qterminal nor lxterminal.

Also tested with konsole, "Use icons by WindowClass, if available" checked, and Tangerine and Gnome icon themes and problem still exists.

**Comment by tsujan** [comment] 2019-10-26 07:58
Found the cause: (2) happens with icon sets that don't have an icon for "konsole". Strangely enough, neither Breeze nor Oxygen has that icon, while my icon set does.

Now, the question is: What's the best way of handling such special cases?

**Comment by tsujan** [comment] 2019-10-26 08:04
And the ridiculous things is that even the Gnome icon theme has "konsole" and so, (2) doesn't happen with it.

**Comment by picorealm** [comment] 2019-10-26 08:15
It's happening for me with Gnome-ILLUSTRIOUS icon theme with both "Use icons by WindowClass, if available" checked and unchecked.

**Comment by tsujan** [comment] 2019-10-26 08:21
> It's happening for me with Gnome-ILLUSTRIOUS icon theme

Then, "Gnome-ILLUSTRIOUS" shouldn't contains an icon named "konsole". Am I right?

**Comment by picorealm** [comment] 2019-10-26 08:24
Correct I don't see any reference to 'konsole' in the gnome-illustrious-icon-theme package contents.

Just out of curiosity what is your window manager set to in Session Settings -> Basic Settings?  Mine is set to kwin.

**Comment by picorealm** [comment] 2019-10-26 08:29
FYI using GNOME (default Gnome theme) which I think is what is provided by the package gnome-icon-theme and that package does contain konsole icons.  However am still getting the problem with "Use icons by WindowClass, if available" both checked and unchecked.
I haven't been able to find any combination of settings so far where the problem doesn't occur.

**Comment by tsujan** [comment] 2019-10-26 08:33
> Mine is set to kwin.

I use kwin too.

> I haven't been able to find any combination of settings so far where the problem doesn't occur.

That complicates the situation. For now, I focus on what I see here. If it can be fixed here, it might be fixed for you too.

**Comment by tsujan** [comment] 2019-10-26 09:45
This is the correct result of our code: We check the class and use the window icon only if the class icon doesn't exist. In the case of Konsole, the class icon doesn't exist, the window icon permanently changes to the bell icon and the task bar follows it.

In this sense, it isn't a bug: the changed window icon is reflected by the task bar correctly. Therefore, I removed the "bug" label.

However, we might be able to find another way of setting task button icons. Hence, I left the report open.

**Comment by tsujan** [comment] 2019-10-26 11:42
OK, it is possible to do it but only with a suboptimal code. My final conclusion after looking into the code more deeply: **We have done it correctly.**

Short technical explanation:

We check both `NET::WMIcon` and `NET::WM2WindowClass` in the function `LXQtTaskGroup::onWindowChanged`. *If we only checked the latter, the task bar icon would not change in (2)* (see https://github.com/lxqt/lxqt/issues/1753#issuecomment-546578767) but that would mean a minor bug, which KDE Plasma has (other DEs may have it too).

Short nontechnical explanation:

In our panel, the task button icon reflects the window icon *if the class icon doesn't exist*. That's very correct.

Closing...

**Closed by tsujan** 2019-10-26 11:42 UTC

**Comment by rbertoche** [comment] 2020-06-01 01:15
I still have this so called non-bug. It's the only thing stopping me from using lxqt as my default DE.

**Comment by tsujan** [comment] 2020-06-01 05:44
> Even if we call this a bug in konsole, it's unlikely to be fixed if it's manifesting only on LXQt.

That may be true but it isn't LXQt's problem.

> Also all users will see it as a LXQt bug.

"All users" may not use Konsole under LXQt.

FYI, this isn't the first time a hidden KDE bug shows up in LXQt. In the case of https://github.com/lxqt/lxqt/issues/1525#issuecomment-406907067, we found the bug in their code (after wasting our time with Facebook-like comments) but we don't have time to debug others' codes constantly.

**Comment by Chiitoo** [comment] 2020-06-01 15:56
This looks like KDE bug 408458 [1], at least with regards to Konsole.

I, too, worked around it by changing the default icon under General settings of the Konsole Profile.

1. https://bugs.kde.org/show_bug.cgi?id=408458

**Comment by tsujan** [comment] 2020-06-01 16:05
@Chiitoo 
Thanks for the info!

**Comment by rbertoche** [comment] 2020-06-01 21:46
@tsujan I didn't to waste anybody's time. I'm sorry if it is the case.

@Chiitoo That on the otherside will probably be rather useful. Thanks!
