### ISSUE TITLE
Lid Watcher: Turn off laptop screen when lid is closed

### ISSUE THREAD

**Issue by dagostinelli** [lxqt/lxqt#1473] opened 2018-04-11 14:05 UTC
##### Expected Behavior

When the laptop lid is closed and there are external monitors plugged in, the laptop screen should turn off and the primary desktop should move to the first external monitor.

##### Current Behavior

When the laptop lid is closed, it stays on and remains the primary monitor

##### Possible Solution

Add settings to Power Management or Monitor Settings to control this behavior. 

##### Steps to Reproduce (for bugs)

1. Install Fedora Workstation (give you gnome by default)
2. Group install LXQT
3. Setup 2 external monitors, get it working in Gnome
4. Switch to LXQT
5. Close the lid

##### System Information

* Distribution & Version: 
$ cat /etc/fedora-release 
Fedora release 27 (Twenty Seven)

* Kernel: 
$ uname -r
4.15.10-300.fc27.x86_64

LXQT Version | 0.11.1
Qt | 5.9.4
Build type | Release
System Configuration | /etc/xdg
Share Directory | /usr/share/lxqt

$ glxinfo | grep -i render
direct rendering: Yes
OpenGL renderer string: Quadro K2000M/PCIe/SSE2
    GL_ARB_conditional_render_inverted, GL_ARB_conservative_depth, 
    GL_KHR_robustness, GL_KTX_buffer_region, GL_NVX_conditional_render, 
    GL_NV_compute_program5, GL_NV_conditional_render, 
    GL_NV_parameter_buffer_object2, GL_NV_path_rendering, 
    GL_ARB_compute_variable_group_size, GL_ARB_conditional_render_inverted, 
    GL_KHR_robustness, GL_KTX_buffer_region, GL_NVX_conditional_render, 
    GL_NV_compute_program5, GL_NV_conditional_render, 
    GL_NV_parameter_buffer_object2, GL_NV_path_rendering, 
    GL_EXT_multisample_compatibility, GL_EXT_multisampled_render_to_texture, 
    GL_EXT_multisampled_render_to_texture2, GL_EXT_occlusion_query_boolean, 
    GL_EXT_render_snorm, GL_EXT_robustness, GL_EXT_sRGB, 
    GL_NV_conditional_render, GL_NV_copy_buffer, GL_NV_copy_image, 
    GL_NV_packed_float_linear, GL_NV_path_rendering, 
    GL_OES_fbo_render_mipmap, GL_OES_geometry_point_size,

$ lspci | grep -i vga                                                                                                                                             
01:00.0 VGA compatible controller: NVIDIA Corporation GK107GLM [Quadro K2000M] (rev a1)

**I get the following no matter if the lid is open or closed**

$ xrandr --query
Screen 0: minimum 8 x 8, current 5760 x 1080, maximum 16384 x 16384
VGA-0 disconnected primary (normal left inverted right x axis y axis)
LVDS-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.15*+  40.06  
DP-0 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      74.98    59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      74.98    59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)

**Comment by tsujan** [comment] 2018-04-11 14:30
Here, with or without an external monitor, when the lid is closed, the laptop suspends, as expected.

> Install Fedora Workstation (give you gnome by default)

I'm afraid if reproducing a "bug" requites installing a distro, it might be a problem caused by that distro. What do you have in Power Management Settings → Lid → Enable Lid Watcher → Action when lid is closed?

BTW, on another computer, I had Gnome+GDM and had seen some Gnome processes running even when I hadn't logged into it -- I replaced GDM with SDDM because of that intrusion. So, this may be caused by a Gnome/GDM interference too.

**Comment by dagostinelli** [comment] 2018-04-11 15:15
> it might be a problem caused by that distro. 

Ok. Probably so then.  Still, this is a valid use case for a DE and probably worth making sure it works.  For instance, I can switch to KDE and the lid thing works fine.  

> What do you have in Power Management Settings → Lid → Enable Lid Watcher → Action when lid is closed?

- Enable Lid Watcher is checked
- Action when lid is closed On Battery: Hibernate On AC: Nothing
- When using external monitor is checked, On Battery: Nothing  On AC: Nothing

But there is no option to say "turn off the laptop lid screen"

> I had Gnome+GDM and had seen some Gnome processes running even when I hadn't logged into it

It looks like I have that too.  Still, it seems like there is a small problem in LXQT.

$ ps -aux | grep -i gdm
root      1446  0.0  0.0 409764  8328 ?        Ssl  08:46   0:00 /usr/sbin/gdm
root      1460  0.0  0.0 367600  8636 ?        Sl   08:46   0:00 gdm-session-worker [pam/gdm-launch-environment]
gdm       1474  0.0  0.0  81428  8032 ?        Ss   08:46   0:00 /usr/lib/systemd/systemd --user
gdm       1531  0.0  0.0 118832  4452 ?        S    08:46   0:00 (sd-pam)
gdm       1540  0.0  0.0 421256  9748 tty1     Ssl+ 08:46   0:00 /usr/libexec/gdm-x-session gnome-session --autostart /usr/share/gdm/greeter/autostart
gdm       1554  0.3  0.2 298488 75908 tty1     Sl+  08:46   0:16 /usr/libexec/Xorg vt1 -displayfd 3 -auth /run/user/42/gdm/Xauthority -background none -noreset -keeptty -verbose 3
gdm       1992  0.0  0.0  54252  4708 ?        Ssl  08:47   0:00 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
gdm       1995  0.0  0.0 665364 13848 tty1     Sl+  08:47   0:00 /usr/libexec/gnome-session-binary --autostart /usr/share/gdm/greeter/autostart
gdm       1999  0.0  0.0 355812  6424 ?        Ssl  08:47   0:00 /usr/libexec/at-spi-bus-launcher
gdm       2004  0.0  0.0  53732  4140 ?        Sl   08:47   0:00 /bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
gdm       2007  0.0  0.0 223096  6892 ?        Sl   08:47   0:00 /usr/libexec/at-spi2-registryd --use-gnome-session
gdm       2015  0.3  0.6 4068596 206348 tty1   Sl+  08:47   0:19 /usr/bin/gnome-shell
gdm       2090  0.0  0.0 1736332 11448 ?       S<l  08:47   0:00 /usr/bin/pulseaudio --start --log-target=syslog
gdm       2183  0.0  0.0 488100 10136 ?        Ssl  08:47   0:00 /usr/libexec/xdg-permission-store
gdm       2188  0.0  0.0 464964  8856 tty1     Sl   08:47   0:00 ibus-daemon --xim --panel disable
gdm       2192  0.0  0.0 387560  5956 tty1     Sl   08:47   0:00 /usr/libexec/ibus-dconf
gdm       2195  0.0  0.0 459200 21576 tty1     Sl   08:47   0:00 /usr/libexec/ibus-x11 --kill-daemon
gdm       2197  0.0  0.0 387424  5728 ?        Sl   08:47   0:00 /usr/libexec/ibus-portal
gdm       2220  0.0  0.0 543652 21872 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-wacom
gdm       2223  0.0  0.0 609876 22852 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-xsettings
gdm       2224  0.0  0.0 547740 21468 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-a11y-keyboard
gdm       2225  0.0  0.0 510480 11180 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-a11y-settings
gdm       2226  0.0  0.0 458620 20088 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-clipboard
gdm       2228  0.0  0.0 794288 24400 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-color
gdm       2229  0.0  0.0 470680 12748 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-datetime
gdm       2230  0.0  0.0 510144 11064 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-housekeeping
gdm       2237  0.0  0.0 619564 21664 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-keyboard
gdm       2240  0.0  0.0 994556 23536 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-media-keys
gdm       2248  0.0  0.0 434300  9552 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-mouse
gdm       2252  0.0  0.0 919496 24272 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-power
gdm       2253  0.0  0.0 472276 12544 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-print-notifications
gdm       2259  0.0  0.0 434316  9512 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-rfkill
gdm       2260  0.0  0.0 508032 10864 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-screensaver-proxy
gdm       2263  0.0  0.0 416644  7440 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-sharing
gdm       2272  0.0  0.0 699732 15660 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-smartcard
gdm       2277  0.0  0.0 552840 12288 tty1     Sl+  08:47   0:00 /usr/libexec/gsd-sound
gdm       2337  0.0  0.0 192148  5040 ?        Sl   08:47   0:00 /usr/libexec/dconf-service
gdm       2344  0.0  0.0 313756  5876 tty1     Sl   08:47   0:00 /usr/libexec/ibus-engine-simple
root     21467  0.0  0.0 390392  9912 ?        Sl   10:07   0:00 gdm-session-worker [pam/gdm-password]
dagosti+ 21523  0.0  0.0 421256 10036 tty2     Ssl+ 10:08   0:00 /usr/libexec/gdm-x-session --run-script startlxqt
dagosti+ 21527  3.7  0.2 322568 94408 tty2     Sl+  10:08   0:08 /usr/libexec/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3
dagosti+ 23525  0.0  0.0 119528  1008 pts/0    S+   10:11   0:00 grep --color=auto -i gdm

**Comment by tsujan** [comment] 2018-04-11 15:25
> But there is no option to say "turn off the laptop lid screen"

So, those settings work correctly but you want an extra option to turn off the screen on closing the lid. That's a valid feature request and not related to Fedora/Gnome/GDM. I don't know if this special use case is popular enough to be worth implementing. Anyhow, other devs should look into it -- not my area.

@selairi ?

**Comment by dagostinelli** [comment] 2018-04-11 15:40
@tsujan I wouldn't exactly call this a special use case. Wouldn't you think it's expected behavior for a laptop connected to a docking station with external monitors? 

Additional Info: I just tried out SDDM and also LightDM.  As I'm writing this I'm under SDDM (no GDM running) and it's doing the same thing (not shutting off the laptop screen when the lid is closed) 

BTW, Even though I'm still not where I want to be, I just wanted to write "Thanks!" for suggesting that I try all of that.  I just got a whirlwind lesson in how to change DMs.  Good stuff! 👍

**Comment by tsujan** [comment] 2018-04-11 15:55
> @tsujan I wouldn't exactly call this a special use case. Wouldn't you think it's expected behavior for a laptop connected to a docking station with external monitors?

That was just an opinion, not a decision. When I connect my laptop to an external monitor, I want to use its keyboard. 

> As I'm writing this I'm under SDDM (no GDM running) and it's doing the same thing  (not shutting off the laptop screen when the lid is closed)

When there's no option for that (yet), it shouldn't. But SDDM is surely better than GDM, unless you only want Gnome.

I hope we'll see @selairi's reply.

**Comment by dagostinelli** [comment] 2018-04-11 16:28
As another data point....  (This is from XFCE) 

I just installed XFCE and it has an equivalent power manager tool. There is an option for switching off the display when laptop lid is closed (see pic)  

![image](https://user-images.githubusercontent.com/715418/38629921-03221762-3d7b-11e8-9cc6-868f89bacdd8.png)

That said, it also doesn't handle this use-case correctly.  When I close the lid, it doesn't automatically move the primary display to one of the external monitors.  To make that happen, I have to also uncheck "Use this display" in the Display tool manually.  

KDE and gnome do properly handle this use-case without me needing to set an option somewhere.

**Comment by Vladimir-csp** [comment] 2018-04-11 17:18
Just to bring some clarity to this issue, in case not everyone here has the full picture: there are several mechanisms at play. 

First, there is the lid state, which can be accessed through ACPI, for example: 
```
$ cat /proc/acpi/button/lid/LID0/state
state:      open
```

Second, there is systemd-logind handling of lid event (whether to sleep, or not):
```
$ cat /etc/systemd/logind.conf | grep -i 'suspend\|lid'
#HandleSuspendKey=suspend
#HandleLidSwitch=suspend
#HandleLidSwitchExternalPower=suspend
#HandleLidSwitchDocked=ignore
#SuspendKeyIgnoreInhibited=no
#LidSwitchIgnoreInhibited=yes
```

Third is X and XRandr, those stand totally apart from the above. So it is a matter of user-level monitor handling tool to react to lid state change and switch profiles accordingly. Lid state should be incorporated into profile's matching. And lid state change should trigger refresh similar to output state change.

**Comment by tsujan** [comment] 2021-04-19 11:31
Implemented more than a year ago.

**Closed by tsujan** 2021-04-19 11:31 UTC
Labels: lxqt-powermanagement
