### ISSUE TITLE
menu-button opens in wrong position (on portrait display, normal on landscape..) 

### ISSUE THREAD

**Issue by guiverc** [lxqt/lxqt#1709] opened 2019-04-20 04:55 UTC
Setup is a machine with two displays, left is landscape and right is in portrait.
By adding a panel to the portrait display, the menu doesn't open as expected just above the panel, but can open on the wrong screen (rare), or usually a distance above the panel (eg. a test  on opensuse tumbleweed box has it open closer to top of screen that bottom when panel is at the bottom)

##### Expected Behavior

I expect panel to open on the correct display, or if on correct display just above or very near the panel where I clicked the menu to avoid excessive mouse movement.

##### Current Behavior

The menu usually opens well above the panel (with panel at bottom of screen, menu opens closer to top of display than bottom).  This however varies, depending I think on how screens are positions using LXQt.Settings->Monitor.Settings

A screenshow should be visible via (opensuse)
https://drive.google.com/file/d/1RRrGNhn1PIUQsSkdyuHJgPXGi18puiMn/view?usp=sharing
note: it appears the menu is positioned to align with panel on left-display (look at panel to see panel positions), but this is closer to the top of the right (portrait) display than to the panel at the bottom of the display it's on. 

(When menu appears on display 0 (or landscape screen, display 1 being the portrait display where I clicked the menu); it's always just above panel - and I'm suspicious that this could be I sometimes have screens slightly-overlapping when setting up using Monitor.Settings; but I'm not sure). The vertical position does not change during the session.

##### Steps to Reproduce (for bugs)

1.  use machine with two displays
2.  rotate one display to portrait mode (advanced - left is what I used)
3. add panel to bottom of portrait display, adding menu & other desired widgets to panel (it doesn't matter which, but menu is required) 
4. click on menu on the second (portrait) display, menu will open & display well above the panel (even on wrong screen sometimes in test, usually though just well above)

Note: If you don't see this occur, try switching displays so your portrait is the landscape & vice-versa. I had to do this on opensuse (which doesn't have have a portrait display).

##### Context

It's just annoying; operation & pleasure is just lessened by unwanted behavior.

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* Package version: 

This bug was discovered in debian-testing (installed on one d755) that
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916105

It was later discovered in Lubuntu 19.04 QA-testing (daily iso) to exist there 
on the same machine & another marchine (d780) with identical display setup.
https://bugs.launchpad.net/ubuntu/+source/lxqt-panel/+bug/1810075

Test on opensuse tumbleweed & occurs there too
https://bugzilla.opensuse.org/show_bug.cgi?id=1132937

Distribution & Version: debian testing & opensuse tumbleweed & lubuntu 19.04
Kernel: 4.19.0-14 & 5.0.0-8-generic & 5.0.0-8
Qt Version: 0.14.1 & 0.14.1 & 0.14.1
liblxqt Version: 0.14.1 & 0.14.1 & 0.14.1
Package version: (0.14.1-1) & liblxqt-devel 0.14.1-1.1 x86_64 & liblxqt0 x86_64 0.14.1-0ubuntu1

**Comment by tsujan** [comment] 2019-04-20 05:05
Probably related to the other issue you reported: https://github.com/lxqt/lxqt/issues/1704

**Comment by guiverc** [comment] 2019-04-20 05:42
Whilst two issues (#1703 & #1704) are certainly related as they haven't occurred for ages on my primary box (which you noticed & possibly explained in the 'guess' that 'fits' on April 12 #1704), the screensaver issue remains, so I believe it to be separate, as possibly is this issue.

This issue hasn't disappeared, and was noticed/reported [on debian] before others, though it could also be because I don't use boxes with this landscape+portrait orientation screens as often.

**Comment by guiverc** [comment] 2019-09-18 10:31
Any progress?

In Lubuntu testing (19.10 daily) I still note this issue on dell optiplex 755 & optiplex 780's (both boxes share the same displays so have same setup). It was also noted in debian buster 'live' builds (a few months back).

Of note - I no longer notice the issue on my installed debian-testing (now bullseye) on d755; though it may be @tsujan was correct and it is related to other issues; as they [1703&1704] stopped being an issue on my installations (with exception of opensuse tumbleweed - one box where I've made no setting/config changes to try and keep 'pure' for comparison purposes).  Thanks, Chris g.

**Comment by tsujan** [comment] 2019-09-18 12:16
> Any progress?

No. The cause or cause are still unknown -- at least to me.

> as they [1703&1704] stopped being an issue on my installations

A Qt or X11 update?

**Comment by agaida** [comment] 2019-09-18 14:59
Easy as can be - what we can't reproduce we can't fix.

**Comment by tsujan** [comment] 2019-09-18 15:08
@agaida, actually I succeeded in reproducing one of @guiverc's issues after following his advice but haven't tried it again since then.

If some of them are really fixed for him, it means that the problem was in Qt or X11 or... but not in LXQt. That's very likely, IMO, because I've seen a Qt problem about virtual screen first hand (lack of signals where they should be emitted).

**Comment by guiverc** [comment] 2019-09-19 00:15
For my d755 (debian bullseye install) 
guiverc@755-deb:/$ lxqt-about  --version
lxqt-about 0.14.1
liblxqt   0.14.1
Qt        5.11.3

My comment was based on (https://github.com/lxqt/lxqt/issues/1704#issuecomment-482544722) or "My guess: a default value is wrong, once it's overridden, everything is OK."

I have the issue with Lubuntu 'live' systems, and it continues after install, however as I use the system and change configuration etc - eventually the problem disappears; 1703 & 1704 anyway, my guess is maybe it applies to this one too!! and the reason for my comment). It's also why I don't touch my 'opensuse tumbleweed' config in attempts to keep it clean from changes, so it doesn't require re-install.

I bet if I re-install this debian box; the issue would return (**). That occurs for my regular re-installs (usually for QA-testing purposes) of Lubuntu.  If I had any clues as to what configuration options actually achieved the 'fix' I've had said - alas I've achieved fix twice, but in re-doing steps again post-reinstall it didn't work (and it was 2-3 hours to reinstall & try and follow the ~40 things that seemed to 'fix' it (ie. I never narrowed it down).  In use, it eventually seems to go away (what I believe has happened to this debian-11 install), but I've been unable to find what causes that to occur sorry.  (fyi: 1705 screensaver issues has never gone away so to me that's a different issue)

** if you want me to re-install debian to confirm my theory; I'll do it on the d780 that also has those issues; but it may take awhile (as in days)

**Comment by guiverc** [comment] 2019-11-03 07:20
![lxqt_menu_2019-11-03](https://user-images.githubusercontent.com/43461333/68081645-b7c7fe00-fe65-11e9-9eeb-3183deab0fa3.jpg)

I just full-upgraded this debian-testing box 
dell [optiplex] 755 (c2d-e8300, 8gb, amd/ati radeon rv610/radeon hd2400 pro/xt)
with lxqt.debian.net's experiemental-snapshots, logged out and back in.

For testing purposes, the displays have been setup one below the other (like my hp 8200, d960). I didn't change orientation of the 'lower' display so it's still set to portrait-left tilted (thus is higher, but not as wide as other display; it was centered rather than left/right aligned relative to other display. The panel at the bottom of picture, or terminal shown is full-width which shows how it appears in the screenshot (lximage-qt -s).

guiverc@755-deb:/$   apt-cache policy lxqt-session                                                                          
lxqt-session:                                                                                                               
  Installed: 0.14.1-2                                                                                                       
  Candidate: 0.14.2~50-g82e4fbd-1                                                                                           
  Version table:                                                                                                            
     0.14.2~50-g82e4fbd-1 500                                                                                               
        500 https://lxqt.debian.net/debian experimental-snapshots/main amd64 Packages    

The menu when clicked on the bottom display (1280x1024 displays) can be seen in the attached jpg.  The menu appears top of the actual display crunched up below the panel on the 'top' display.


On some boxes, including how I referred to it earlier today in another (1704) it appears as only a few pixels...  In https://github.com/lxqt/lxqt/issues/1704#issuecomment-549103295 @tsujan should never appear on the boundary of two displays; when I first logged in after adding the experimental I noted the option of where the panel could be placed was 3 sides only for each display just like @tsujan suggested; however the moment I put screens up/down (one below the other) I could place the panels on any of the four edges of the screen.

**Comment by tsujan** [comment] 2019-11-03 09:22
> however the moment I put screens up/down (one below the other) I could place the panels on any of the four edges of the screen.

That should be impossible but -- who knows? -- the obsolete class `QDesktopWidget` may be the culprit. I'm trying to remove `QDesktopWidget` from the panel code.

**Comment by siduction-machine-user** [comment] 2019-11-03 09:31
\<sarcasm>only a remark - i pointed @guiverc to my insane repos - so multi-monitor handling still seems not optimal :D - but i'm proud that we just provide a system on wich it is possible to make screenshots\</sarcasm>

Beside of this - we can only get better - so the removal of `QDesktopWidget` might be the first step

And please forget about siduction-machine-user - still agaida :smile:

**Comment by tsujan** [comment] 2019-11-03 09:42
We'll see what happens after https://github.com/lxqt/lxqt-panel/pull/1261 is finished (I found a problem in it; will tell when it's complete).

**Comment by guiverc** [comment] 2019-11-03 11:00
booting siduction-patience-lxqt-amd64-latest.iso 2019-11-02

adjust displays so vertical arrangement (one above the other), open pcmanfm-qt and on initial monitor the menu is usable, move pcmanfm-qt window to bottom monitor and menu now cannot be opened. 

swap top/bottom monitors from what I initially setup, and now menu can be accessed regardless of which monitor pcmanfm-qt is on; ie. as expected/hoped for.

**Comment by tsujan** [comment] 2019-11-03 18:20
> and I'm suspicious that this could be I sometimes have screens slightly-overlapping when setting up using Monitor.Settings

@guiverc I'm very sorry! I'd missed the above sentence in your comment. Yes, *overlapping can alow the panel to be at the middle of the screen* and ruin everything. That's in the panel code (and I didn't change it in my patch).

Since a panel at the middle of screen causes problems, the code can be changed to make it always impossible, even with an overlap. IMO, a middle panel is senseless on a big virtual screen (although it makes sense when the screens aren't combined).

@agaida, what do you think? Should I remove the possibility? What @guiverc reported is inevitable with it. Or is an overlap a bad thing that should be avoided?

**Comment by tsujan** [comment] 2019-11-04 18:02
Answering to myself:

LXQt panel should be put only at the virtual screen edges. `LXQtPanel::canPlacedOn` tries to do it but is incomplete. I'll add a commit to https://github.com/lxqt/lxqt-panel/pull/1261 for that.

**Comment by tsujan** [comment] 2019-11-10 23:30
Closed in https://github.com/lxqt/lxqt-panel/pull/1261

**Comment by tsujan** [comment] 2019-11-10 23:33
@guiverc Please test the latest git panel!

**Comment by guiverc** [comment] 2019-11-15 10:53
This issue **IS** still re-producible sorry.  (on one box?? so far)

(panel was bottom of 'portrait' display, but clicking menu and the menu was closer to 'top' of display than bottom; well away from panel; only on 'portrait' display).

lxqt-panel 0.14.2~389-g02cfca52-1 amd64
hp dc7700 (c2d-e6320, 5gb, nvidia quadro nvs 290)
using debian-testing & https://lxqt.debian.net/

Screens on this box are NOT landscape+portrait, so I just used 'Monitor Settings' to mimic that arrangement & *gritted teeth* 

**HOWEVER** I also tested on 
dell [optiplex] 780 (c2q-q9400, 8gb, amd/ati cedar radeon hd 5000/6000/7350/8350)

which should be ~identical setup, also '_newish_' install, and actually has landscape+portrait displays and I could **NOT** re-produce???
I did some quick minor changing of Monitor.Settings setup to see if I could re-produce, nope..

I'll endeavour to do more testing with this (including my original [_discovery_] box dell [optiplex] 755 (c2d-e8300, 8gb, amd/ati radeon rv610/radeon hd2400 pro/xt), but it won't be tonight.

**Comment by tsujan** [comment] 2019-11-15 10:59
In your screenshot on this page, a panel is at the middle of the screen. That's impossible with the latest patches. So, the problem you're seeing now may not be the same problem you reported here.

A screenshot could be very helpful.

**Comment by guiverc** [comment] 2019-11-15 11:06
![tsujan_screenshot_2019-11-15](https://user-images.githubusercontent.com/43461333/68939091-db8b2c80-07f3-11ea-9f4b-d382322fd5f6.jpg)

Probably not tidy, but 2x 1920x1080 screens; one (right) made portrait. 
One qterminal is in a strange location (when I moved displays in Monitor.Settings and I ignored it). 

The menu on the 'right' portrait display is where cursor is. Menu on that display is clicked; where it can be seen ~halfway up the display

**Comment by tsujan** [comment] 2019-11-15 14:38
> Panels are both at the 'bottom' of display

But, in your screenshot, the left panel is at the middle!

**Comment by agaida** [comment] 2019-11-15 16:06
meh - give me some time to catch up with latest git

**Comment by tsujan** [comment] 2019-11-15 16:16
@agaida Is @guiverc's  panel the latest git (https://lxqt.debian.net/)? The answer to this question is important.

**Comment by tsujan** [comment] 2019-11-15 16:23
No, it isn't (g02cfca52). Very confusing! A lot of info is missing from these reports...

**Closed by tsujan** 2019-11-15 16:23 UTC

**Comment by guiverc** [comment] 2019-11-15 21:36
Nah the panel on the left screen is at the bottom of the actual screen, that is the landscape screen (1920x1080), where as the right screen is 1080x1920 thus far higher.

A huge portion bottom-left of the screengrab does **NOT** appear on either display due to landscape+portrait selection.

The untidy (lowest) terminal is mostly off-screen and only the bit below the menu itself is actually visible on my 'right; display.  The panels are at the bottom edges of my actual displays.  Everything below left-panel is invisible to me as *off-screen*.

**Comment by tsujan** [comment] 2019-11-15 22:03
@guiverc I think, also in the other cases, where you couldn't reproduce issues anymore, it was only by chance. Please wait until the latest panel patches come into https://lxqt.debian.net/ and then, retry.

Please also note that closed issues might be reopened if needed.

**Comment by guiverc** [comment] 2021-02-23 08:44
Lubuntu hirsute (what will be 21.04) just upgraded to LXQt 0.16; todays daily (2020-02-22.1) installed on d755-8 (box name given only as helpful to me)
lxqt-about 0.16.0
liblxqt 0.16.0
Qt 5.15.2
and I'm retesting some old bugs.

This still occurs, as can be seen via [https://bugs.launchpad.net/ubuntu/+source/lxqt-panel/+bug/1810075/+attachment/5466112/+files/screen_menu_wrong_position2.jpg](url)

On the left display/monitor you'll see (Monitor.Setting window) Monitor Positions relative to each other.. ie. they should be touching, the right is portrait-left tilted, left is landscape.

I've added a panel on the right (portrait-left tilt) display, and clicked the menu button.

The MENU however is opening quite a distance up the screen.

FYI:  There is another glitch where pressing PRINTSCREEN always shows a gap between the monitors, which is actually reflected when you move the mouse between the monitors, however no change has been made to the monitor positions and they should be just as the left Monitor.Settings window reflects.  I can move them apart, Apply & Save, exit the Monitor.Settings dialog, re-open it and return to the setup shown (which matches the displays on this box) and whilst Monitor.Settings doesn't show a gap, printscreen & mouse-movement will reflect a gap.  

The menu glitch maybe related to this 'gap' is issue I may have filed here (github), or just on launchpad; but i'm ignoring that for now.  The menu opening way above the panel is the reason for this update.

**Comment by wxl** [comment] 2021-02-23 18:52
@guiverc another thing to point out is that [this PPA](https://launchpad.net/~lubuntu-ci/+archive/ubuntu/unstable-ci) is essentially Git master here. It's the first place I turn to test issues I have downstream. You may want to give that a go in your testing of this.

**Comment by tsujan** [comment] 2021-02-23 20:14
I'll test the main menu when I find the time (probably not soon). Screengrab's behavior is as expected and OK.

**Comment by guiverc** [comment] 2021-02-25 06:30
Short off-topic remark.  

The 'gap' shown in the picture in comment 2 days ago, is reported on launchpad.net in https://bugs.launchpad.net/ubuntu/+source/lxqt-session/+bug/1882411 but has **NOT** been reported upstream (ie. here in github/lxqt).

I've only noticed it on that box it seems (so it may be that orientation of screens and maybe resolution?).  I'll endeavour to explore it some more & file report on it now I know it impacts lxqt 0.16.   (and thanks @wxl)
