### ISSUE TITLE
pcmanfm-qt crashed, sharing backtrace 

### ISSUE THREAD

**Issue by shirishag75** [lxqt/lxqt#1610] opened 2018-11-05 17:49 UTC
pacmanfm-qt crashes when I take out a removable drive. I tried the coredump methodology which was shared before but unfortunately that didn't work here. 

So while I was looking at something else, came to know that pcmanfm-qt coredump was stored at /var/lib/systemd/coredump . 

copied the 35 mb coredump file and chmod it to 777 . Used lz4 to decompress the archive and then used gdb using pcmanfm-qt on the coredump file to get the following output - 

https://paste.debian.net/1050439/

Hopefully it will have something of interest. 

```
Version: 0.13.1~202-g7014a03-1
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages pcmanfm-qt depends on:
ii  dbus-user-session [default-dbus-session-bus]  1.12.10-1
ii  dbus-x11 [dbus-session-bus]                   1.12.10-1
ii  desktop-file-utils                            0.23-4
ii  libc6                                         2.27-8
ii  libfm-qt6                                     0.13.2~276-gccd984f-1
ii  libglib2.0-0                                  2.58.1-2
ii  libqt5core5a                                  5.11.2+dfsg-4
ii  libqt5dbus5                                   5.11.2+dfsg-4
ii  libqt5gui5                                    5.11.2+dfsg-4
ii  libqt5widgets5                                5.11.2+dfsg-4
ii  libqt5x11extras5                              5.11.2-2
ii  libstdc++6                                    8.2.0-9
ii  libxcb1                                       1.13.1-1
ii  lxqt-sudo                                     0.13.1~78-ga571dda-1

Versions of packages pcmanfm-qt recommends:
ii  breeze-icon-theme  4:5.49.0-1
ii  eject              2.1.5+deb1+cvs20081104-13.2
ii  faenza-icon-theme  1.3.1-1
ii  ffmpegthumbnailer  2.1.1-0.2+b1
ii  gvfs-backends      1.38.0-2
ii  gvfs-fuse          1.38.0-2
ii  lximage-qt         0.14.0~really~0.7.1~141-g7ea87b8-1
ii  lxqt-policykit     0.13.1~51-gbd2134e-1
ii  lxqt-qtplugin      0.13.1~4-g7065c43-4
ii  oxygen-icon-theme  5:5.49.0-1
ii  pcmanfm-qt-l10n    0.13.1~202-g7014a03-1

Versions of packages pcmanfm-qt suggests:
pn  cdtool       <none>
ii  libfm-tools  1.3.0.2-1

-- no debconf information
```

**Comment by tsujan** [comment] 2018-11-05 18:07
>  tried the coredump methodology which was shared before but unfortunately that didn't work here.

How? When you have a coredump, just do `coredumpctl gdb pcmanfm-qt` and `where`. Did you change something in your system?

https://paste.debian.net/1050439/ doesn't show that the fault is in libfm-qt/pcmanfm-qt.

**Comment by tsujan** [comment] 2018-11-05 18:08
Or you could describe how to reproduce the crash in a step-by-step way.

**Comment by shirishag75** [comment] 2018-11-05 18:30
At my end it is reproducible reliably - 

1. Either click on pcmanfm-qt via desktop shortcut or otherwise. 
2. Attach a removable usb drive 
3. Let it remain there for couple of minutes 
4. Unmount the drive 
5. physically detach the drive from the usb port. 

It is at this point that pcmanfm-qt folds/crashes. The expected behavior is that the icon for the drive should disappear not the whole application itself. If running under gdb it shows as closing normally when there has been no move to close pcmanfm-qt.

**Comment by tsujan** [comment] 2018-11-05 18:41
I do that on a regular basis; if it crashed, I would be the first one that would see it ;)

Perhaps, you mistake closing with crashing. If you unmount the drive and the only tab is that of the drive, pcmanfm-qt's window will be closed. This behavior can be changed in Preferences → Volume. Moreover, a crash means that your whole desktop should disappear.

If that's the case, please close this issue!

**Comment by shirishag75** [comment] 2018-11-05 18:55
![pcmanfm-qt-window](https://user-images.githubusercontent.com/727626/48019680-0c08a700-e15a-11e8-92c2-5d71cd637f5f.png)

see that, if I unmount the drive, the name of the removable drive is ISOIMAGE . If I remove it physically, manually many a times it will close, ideally it should not close.

**Comment by tsujan** [comment] 2018-11-05 19:03
If you have opened ONLY a folder that shows the contents of a mounted drive and then that drive is unmounted in any way, there will be nothing to see, so the tab will be closed and, because it's the only tab, pcmanfm-qt's window will be closed too. You could change that behavior in Preferences.

No disappearance of desktop means no crash. pcmanfm-qt is a single-process app: all its windows and desktop share the same process; so a crash would affect all of them.

**Closed by tsujan** 2018-11-05 19:03 UTC

**Comment by tsujan** [comment] 2018-11-05 19:06
BTW, your screenshot shows that you don't have the latest git version, although that isn't related to your report: there has been no unmount crash for a long time.
