### ISSUE TITLE
The "Delete" key does not work in PCManfm-qt

### ISSUE THREAD

**Issue by RetroOswi** [lxqt/lxqt#1819] opened 2020-06-30 03:51 UTC
For more than a year I have been using Lubuntu with LXQT as a desktop and I really like both its design and how light it works, except for one detail:

PCManfm-qt works very well, but when I want to send a file to the recycle bin using the "Delete" key it doesn't work. In LXDE PCManfm it worked without problems but in PCManfm-qt it doesn't work. Only Shift + DEL combination works to delete files permanently.

Is it a PCManfm-qt BUG? o Did you remove the function of sending files to the trash using the "Delete" key?

Thank you very much in advance and good luck ...
                                                         --->
*** Distribution & Version: Lubuntu 20.04
* Kernel: 5.3
* Qt Version: 0.14.1**

**Comment by stefonarch** [comment] 2020-06-30 05:59
I remember it, it was long time ago, but it should be fixed also in the 0.14.1 version and I cannot reproduce it on Lubuntu 20.04 in VM
https://github.com/lxqt/lxqt/issues/512

**Closed** 2020-06-30 12:18 UTC
Labels: invalid/dup/rejected
