### ISSUE TITLE
Xrandr and panning: the desktop and the panel (at bottom) do not scale at all.

### ISSUE THREAD

**Issue by frank038** [lxqt/lxqt#2363] opened 2023-01-03 08:45 UTC
##### Expected Behavior

The desktop and the panel should extend their sizes.
##### Current Behavior

The desktop and the panel do not extend their sizes.
##### Steps to Reproduce (for bugs)

1. Command with monitor connected to hdmi-1 under X: xrandr --output HDMI-1 --mode 1280x720 --fb 1920x1080 --panning 1920x1080 (to restore: xrandr --output HDMI-1 --mode 1920x1080)
2. 
3. 
4. 

##### System Information

* Distribution & Version: any
* Kernel: any
* Qt Version: 5.15.7 (and previouses)
* liblxqt Version: 1.2.0 (and previouses)
* Package version: 1.2.0 (and previouses)

**Comment by tsujan** [comment] 2023-01-03 08:56
Duplicate of https://github.com/lxqt/lxqt/issues/1735

**Closed by tsujan** 2023-01-03 08:56 UTC

**Comment by tsujan** [comment] 2023-01-03 15:24
> Kde Plasma has the same issue.

That's a good piece of info. It points to the cause (see below).

> Maybe this bug may be related to a library used by both DEs.

It's in Qt (`QScreen`). I haven't reported it to Qt because they want a "code sample" and I don't have any — I can't tell them to install LXQt for it.
