### ISSUE TITLE
riot-web icon is not visible correctly in lxqt-panel. 

### ISSUE THREAD

**Issue by shirishag75** [lxqt/lxqt#1601] opened 2018-10-29 14:11 UTC
![lxqt-panel-riot-web-icon](https://user-images.githubusercontent.com/727626/47655106-4bf7e900-dbb2-11e8-9ab6-c7cf258a1ded.png)

If you look at the riot-web icon in the notification area i.e. the one next to clipboard history, you would see something pretty hazy, it is only by right-clicking on it I was able to figure out it was riot-web and not something else. 

```
Package: lxqt-panel
Version: 0.13.1~985-gfb8f1805-2
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages lxqt-panel depends on:
ii  libasound2              1.1.6-1
ii  libc6                   2.27-6
ii  libdbusmenu-qt5-2       0.9.3+16.04.20160218-1
ii  libkf5solid5            5.49.0-1
ii  libkf5windowsystem5     5.49.0-1
ii  liblxqt-globalkeys-ui0  0.13.1~68-g1aa38a6-2
ii  liblxqt-globalkeys0     0.13.1~68-g1aa38a6-2
ii  liblxqt0                0.13.1~92-gd694b0f-1
ii  libpulse0               12.2-2
ii  libqt5core5a            5.11.2+dfsg-3
ii  libqt5dbus5             5.11.2+dfsg-3
ii  libqt5gui5              5.11.2+dfsg-3
ii  libqt5widgets5          5.11.2+dfsg-3
ii  libqt5x11extras5        5.11.2-2
ii  libqt5xdg3              3.2.1~12-g7d7e6e7-1
ii  libqt5xml5              5.11.2+dfsg-3
ii  libsensors4             1:3.4.0-4
ii  libstatgrab10           0.91-1+b2
ii  libstdc++6              8.2.0-8
ii  libsysstat-qt5-0        0.4.1-2
ii  libx11-6                2:1.6.7-1
ii  libxcb-xkb1             1.13.1-1
ii  libxcb1                 1.13.1-1
ii  libxcomposite1          1:0.4.4-2
ii  libxdamage1             1:1.1.4-3
ii  libxkbcommon-x11-0      0.8.2-1
ii  libxkbcommon0           0.8.2-1
ii  libxrender1             1:0.9.10-1
ii  lxmenu-data             0.1.5-2
ii  lxqt-policykit          0.13.1~51-gbd2134e-1

Versions of packages lxqt-panel recommends:
ii  lxqt-about          0.13.1~84-g299f518-1
ii  lxqt-config         0.13.1~503-gc73826d-1
ii  lxqt-notificationd  0.13.1~92-g6e95e1c-1
ii  lxqt-panel-l10n     0.13.1~985-gfb8f1805-2
ii  lxqt-qtplugin       0.13.1~4-g7065c43-4
ii  lxqt-runner         0.13.1~78-g134783d-1
ii  lxqt-session        0.13.1~189-gd456314-2
ii  pavucontrol         3.0-4
ii  qlipper             1:5.1.2~13-g0e90641-1

Versions of packages lxqt-panel suggests:
ii  lxqt       27
ii  lxqt-core  27

-- no debconf information
```

**Comment by tsujan** [comment] 2018-10-29 14:18
Duplicate of https://github.com/lxqt/lxqt/issues/1514

@agaida Please close this if that's the case.

**Comment by agaida** [comment] 2018-10-29 16:55
![](https://i.imgur.com/QfAGGMG.png) 

Can't reproduce - ok, riot-web is GTK, but this should be no problem

**Closed by agaida** 2018-10-29 16:55 UTC

**Comment by tsujan** [comment] 2018-10-29 18:19
@shirishag75 There are 2 panel widgets for systray: `System Tray` (old) and `Status Notifier Plugin` (new). Make sure you have both (although you said elsewhere that you couldn't configure panel).

**Comment by shirishag75** [comment] 2018-10-29 19:25
yeah, I cannot either configure panel or Add new widgets. Clicking on Add new widgets does nothing :(

**Comment by shirishag75** [comment] 2018-10-29 19:36
Is there any other way to remove a panel ?

**Comment by tsujan** [comment] 2018-10-29 19:38
Please first answer to https://github.com/lxqt/lxqt/issues/1600#issuecomment-434047480

**Comment by shirishag75** [comment] 2018-10-29 19:52
just did.

**Comment by tsujan** [comment] 2018-10-29 20:05
Your screenshot at https://github.com/lxqt/lxqt/issues/1600#issuecomment-434054172 *may* show the source of this problem (but I'm not sure). Probably, you don't have `Status Notifier Plugin`.

As for removing the panel, since you don't have the right click possibility, do this:

(1) Keep a pcmanfm-qt window open.
(2) Stop the panel from LXQt Session Settings → Basic Settings → LXQt Modules (don't close the dialog after that).
(3) Remove (and preferably, back up) `~/.config/lxqt/panel.conf` with pcmanfm-qt.
(4) Start the panel again with LXQt Session Settings.

The panel won't be removed but will have the default settings.

**Comment by shirishag75** [comment] 2018-10-29 20:24
I think I got it, it probably is because openbox is not installed as the window manager 
![basic-settings-lxqt-session-settings](https://user-images.githubusercontent.com/727626/47678010-ba569e80-dbe6-11e8-8f8c-8b56363307c3.png)

**Comment by tsujan** [comment] 2018-10-29 20:29
> it probably is because openbox is not installed as the window manager

I don't have openbox either.

**Comment by shirishag75** [comment] 2018-10-29 20:35
disregard that,  it took me sometime to understand what you were asking and what the lxqt basic settings were showing. Instead of backing up, I just followed your instructions to the T and removed `~/.config/lxqt/panel.conf` started the panel, logged back in and moved the panel from bottom to top and it worked  At least the panel configuration works now :)

**Comment by tsujan** [comment] 2018-10-29 20:43
> At least the panel configuration works now

Happy to know that.

We should find out why the config didn't work in the first place; that isn't acceptable.

**Comment by shirishag75** [comment] 2018-10-29 20:57
I *think* the statusnotifier is now there as well as other things. 

See - 

![configure-panel-now-works](https://user-images.githubusercontent.com/727626/47679889-51255a00-dbeb-11e8-9ebd-e939546af393.png)

**Comment by agaida** [comment] 2018-11-01 13:16
just use a matching icon theme - nothing we can and want to do here - it is discussed several times in our bug tracker. There will be differences in provided icon themes - so please don't expect icon themes as complete or working with Qt and GTK - hint: faenza should work fine, papirus should work fine, there might be other themes that work fine too - in case these themes work, just file bugs against the icon themes.

**Comment by shirishag75** [comment] 2018-11-01 18:28
I had to figure out that icon themes is in Menu > Preferences > LXQT Settings > Appearance > Icon themes > Faenza, even just clicking on Adwaita fixed the icon on the system-tray/status notifier.  I would probably try logging out and logging in back again to see if this holds. I guess I would need to do with all the icon themes, would probably do it in week-end and file bugs if there are some icon themes which aren't able to give a good view.  

Another possibility is that some of the updates might also have helped - 

```
Package: lxqt-panel
Version: 0.13.1~985-gfb8f1805-2
Severity: normal



-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages lxqt-panel depends on:
ii  libasound2              1.1.6-1
ii  libc6                   2.27-6
ii  libdbusmenu-qt5-2       0.9.3+16.04.20160218-1
ii  libkf5solid5            5.49.0-1
ii  libkf5windowsystem5     5.49.0-1
ii  liblxqt-globalkeys-ui0  0.13.1~68-g1aa38a6-2
ii  liblxqt-globalkeys0     0.13.1~68-g1aa38a6-2
ii  liblxqt0                0.13.1~97-g151ca66-1
ii  libpulse0               12.2-2
ii  libqt5core5a            5.11.2+dfsg-4
ii  libqt5dbus5             5.11.2+dfsg-4
ii  libqt5gui5              5.11.2+dfsg-4
ii  libqt5widgets5          5.11.2+dfsg-4
ii  libqt5x11extras5        5.11.2-2
ii  libqt5xdg3              3.2.1~12-g7d7e6e7-1
ii  libqt5xml5              5.11.2+dfsg-4
ii  libsensors4             1:3.4.0-4
ii  libstatgrab10           0.91-1+b2
ii  libstdc++6              8.2.0-8
ii  libsysstat-qt5-0        0.4.1-2
ii  libx11-6                2:1.6.7-1
ii  libxcb-xkb1             1.13.1-1
ii  libxcb1                 1.13.1-1
ii  libxcomposite1          1:0.4.4-2
ii  libxdamage1             1:1.1.4-3
ii  libxkbcommon-x11-0      0.8.2-1
ii  libxkbcommon0           0.8.2-1
ii  libxrender1             1:0.9.10-1
ii  lxmenu-data             0.1.5-2
ii  lxqt-policykit          0.13.1~51-gbd2134e-1

Versions of packages lxqt-panel recommends:
ii  lxqt-about          0.13.1~84-g299f518-1
ii  lxqt-config         0.13.1~503-gc73826d-1
ii  lxqt-notificationd  0.13.1~92-g6e95e1c-1
ii  lxqt-panel-l10n     0.13.1~985-gfb8f1805-2
ii  lxqt-qtplugin       0.13.1~4-g7065c43-4
ii  lxqt-runner         0.13.1~78-g134783d-1
ii  lxqt-session        0.13.1~189-gd456314-2
ii  pavucontrol         3.0-4
ii  qlipper             1:5.1.2~13-g0e90641-1

Versions of packages lxqt-panel suggests:
ii  lxqt       27
ii  lxqt-core  27

-- no debconf information

```

**Comment by shirishag75** [comment] 2018-11-01 18:43
seems to be some sort of stickiness issue, I tried with couple of themes, once I change themes or even click on themes the icon is clear but once I log out and log back in, the old behavior returns. Have no idea why that happens.

**Comment by shirishag75** [comment] 2018-11-04 18:19
some more info. I didn't even need to log out and come back in to see that the icon file-size changes. I just need to quit riot-web from either the system-tray or from task-manager/application and load it again via qterminal. The difference when themes are changed, stopping and starting riot-web can be seen. 

Sharing the various screenshots in various positions. 

![riot-web-icon-seen-before-theme-change](https://user-images.githubusercontent.com/727626/47968176-1fe5d780-e08c-11e8-8ffa-493831d8ff76.png)

see the somewhat fuzzy icon next to variety-wallpaper-changer which is next to the networking applet in the systray.

**Comment by tsujan** [comment] 2018-11-04 19:30
@shirishag75 Some apps have hard-coded icons for the systray, so that nothing will change if you switch to another icon theme. Also, some apps' codes are old or wrong or, sometimes, not capable of creating a standard systray icon because of the toolkit or programming language they use.

It's practically futile (and very time-consuming) to look into codes of such apps to know why they have bad tray icons. Such issues should be solved by their developers. Moreover, we have a standard notification area and it wouldn't be good to make exceptions for this or that app even if that was possible.

**Comment by shirishag75** [comment] 2018-11-04 19:39
meaning it's probably riot-web's fault.

**Comment by tsujan** [comment] 2018-11-04 19:41
> meaning it's probably riot-web's fault.

Most probably. If I wasn't the cautious developer I am, I'd say, "doubtlessly."

**Comment by agaida** [comment] 2018-11-04 19:57
i close things only if i'm damn sure that there is no problem - please have a closer look at the screenshot - the riotweb logo is in the panel, that should be enough. So - all things are fine except the icon theme - and any icon theme is in absolutly no way our problem.
