### ISSUE TITLE
Print values as numbers

### ISSUE THREAD

**Issue by forraskod** [lxqt/lxqt#1755] opened 2019-11-04 12:57 UTC
Hello,

I really would like libsysstat will be able to print different values in numbers not only diagrams. Do you plan to do it?

**Comment by stdcerr** [comment] 2020-05-31 06:08
Hi, I'm new here and I'm interested in becoming a contributor but I'm not 100% sure about the OP's request. Can anyone clarify, please?

**Comment by stefonarch** [comment] 2020-05-31 10:07
I'm not a developer, but afaik  anyone is welcome to contribute, not sure if you saw this already:
https://github.com/lxqt/lxqt/wiki/Contributing-code

**Comment by yan12125** [comment] 2020-05-31 10:43
For this specific issue, I believe the original poster was talking about the sysstat plugin in lxqt-panel.

**Comment by stdcerr** [comment] 2020-05-31 20:02
The OP, @forraskod didn't mention the panel though and I'm not even able to add the "System Statistics" widget to my panel from the "Configure Panel" > "Add Plugins" dialogue...
I even failed to add the System Statistics widget to a  new & otherwise empty panel. Seems like I might be missing yet another config option, am I or is this an actual problem?

**Comment by stdcerr** [comment] 2020-05-31 20:09
Also, I think this is a duplicate of #1615

**Comment by yan12125** [comment] 2020-06-01 04:54
> The OP, @forraskod didn't mention the panel though

AFAIK the only component in LXQt that uses libsysstat is lxqt-panel, hence the guess

> I'm not even able to add the "System Statistics" widget to my panel from the "Configure Panel" > "Add Plugins" dialogue...

The libsysstat package needs to be installed

> Also, I think this is a duplicate of #1615

Yes, thanks!

**Closed by yan12125** 2020-06-01 04:54 UTC
Labels: lxqt-panel
