### ISSUE TITLE
Desktop Border Incorrect

### ISSUE THREAD

**Issue by js290** [lxqt/lxqt#2420] opened 2023-05-06 20:43 UTC
##### Expected Behavior

LXQt desktop should fill out both monitors on session start.

##### Current Behavior

Two monitor config Display 0 on left of and slightly staggered below Display 1.  The desktop extended on Display 0 does not extend down to the full height of the monitor.  Bottom of Desktop 0 aligns with bottom of Display 1 with black border at bottom of Desktop 0, even though the mouse has access to the entire Display 0.

##### Possible Solution

If I go into LXQt Monitor Settings and re-Apply the monitor position on every restart, desktop is properly resolved.

##### Steps to Reproduce (for bugs)

1.  Two monitor config Display 0 on left of and slightly staggered below Display 1
2.  Log into session and observe LXQt not using the full height of Display 0
3. Re-apply LXQt Monitor Settings to have desktop properly adjusted
4. 

##### Context

This was not a problem on LXQt 1.1.0 on Lubuntu 22.10, but is now a problem on [LXQt 1.2.0 on Lubuntu 23.04](https://bugs.launchpad.net/ubuntu/+source/lxqt-config/+bug/2018192).

##### System Information

* Distribution & Version: Lubuntu 23.10
* Kernel: 6.2.0-20.20-generic
* Qt Version:  5.15.8
* liblxqt Version: 1.2.0-0ubuntu3
* Package version: lxqt-config 1.2.0-1ubuntu2

**Comment by tsujan** [comment] 2023-05-06 21:10
Not reproducible with KWin.

If you use Openbox, you'll have to tolerate its multi-screen bugs, which won't be fixed because Openbox's development stopped years ago.

**Closed by tsujan** 2023-05-06 21:10 UTC
