### ISSUE TITLE
"View" in notification daemon popup fails to distinguish electron apps

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1517] opened 2018-07-13 21:13 UTC
I've Telegram and Discord open in , often when a discord notification pops up clicking the "view" button it opens  theTelegram window

##### Expected Behavior

The associated program should open when clicking "view".

##### Current Behavior

Random opening between Discord and Telegram.

##### System Information

* Distribution & Version: arch, recent  LXQt git

**Comment by tsujan** [comment] 2018-07-13 21:50
Could you give an example with a simple script and without Telegram and Discord? The randomness you mentioned is something I've never seen anywhere.

**Comment by tsujan** [comment] 2018-07-14 08:34
> What do you mean with a "simple script"?

A way of reproducing the issue you see without needing specific apps like Telegram or Discord -- to know whether it's really an LXQt issue. I neither understood which "view" button you meant.

**Comment by stefonarch** [comment] 2018-07-14 11:36
There is a "view" button in the pop up window, below  the title and the  incipit of the messag; the button   should open the app

**Comment by tsujan** [comment] 2018-07-14 12:39
> There is a "view" button in the pop up window

Understood.

Do you know which mimetype is viewed each time? I ask because, although xdg-utils still has [problem](https://github.com/lxqt/lxqt/issues/1298), I have no idea how it could call apps randomly.

You could also try this: https://github.com/lxqt/lxqt/issues/1298#issuecomment-399266516

**Comment by stefonarch** [comment] 2018-07-14 15:01
![schermata-14-17-01-20](https://user-images.githubusercontent.com/10681413/42725655-97972cb0-8787-11e8-91b7-f77779763a90.png)

**Comment by tsujan** [comment] 2018-07-14 15:09
Yes, I got that. That view button is just a notification action. I can also make one with `dunstify`:

![example](https://user-images.githubusercontent.com/981076/42725684-44b529e6-879d-11e8-8ae4-95b94d03e89a.png)

The important thing is the action itself, about which we know nothing. If it uses `xdg-utils`, what I mentioned in my previous comment will be worth a try.

**Comment by tsujan** [comment] 2018-07-14 15:18
I don't have Discord but I have Telegram and the only mimetype it covers is `x-scheme-handler/tg` (about which I have no idea). I have the following line below `[Default Applications]` in `~/.config/mimeapps.list`, added by Telegram:
```
x-scheme-handler/tg=telegramdesktop.desktop
```
So, `x-scheme-handler/tg` -- whatever it is -- should be opened by Telegram and only Telegram, at least with `gio open ...`. Otherwise, I suspect the app that makes the notification in question might have a bug.

**Comment by stefonarch** [comment] 2018-07-14 15:24
I have to admit that I use a symlynk `xdg-open → kde-open5` because I had always weird stuff with xdg that I never could fix, like open pdf from browsers in gimp and other, that was the fast way.
But not all notification pop up have the "view" button, konversation doesn't, thunderbird has, others I don't remember.

**Comment by tsujan** [comment] 2018-07-14 15:55
> I have to admit that I use a symlink xdg-open → kde-open5

I recommend you return to xdg-open but with the [above-mentioned](https://github.com/lxqt/lxqt/issues/1298#issuecomment-399266516) modification; it's a guarantee that all apps will be called correctly.

> But not all notification pop up have the "view" button

I get email notifications every 10 min. from Conky and through a bash script I've written for that purpose, which creates a notification with a "Get Mail" button, which just calls Thunderbird. There is nothing special about that "View" button you see; it's created by an app (Discord?).

**Comment by tsujan** [comment] 2018-07-14 20:11
Closing this because that weird randomness became somehow understandable because of `kde-open5` -- who knows how it works? Reopen it if the same thing happens with a `gio` based `xdg-open`, which is going to be introduced by @luis-pereira.

**Closed by tsujan** 2018-07-14 20:11 UTC

**Comment by stefonarch** [comment] 2018-10-28 14:16
I've replaced the symlink and I'm using xdg-open, but no difference. Recently I noticed that wire and brave (browser) notification  view button opens mostly telegram too. Wire has as title "Elektron" in the message box, discord and brave their app name.

Not sure if it's really an lxqt issue or depends on how those apps build their notifications, but surely it's annoying clicking "view" and have the wrong app opened.

**Comment by tsujan** [comment] 2018-10-28 14:34
> with "we" you mean lxqt?

Yes  :)

**Comment by tsujan** [comment] 2018-10-28 14:36
Change `xdg-open` → `open_lxqt()` to
```sh
open_lxqt()
{
    if gio help open 2>/dev/null 1>&2; then
        gio open "$1"
    else
        open_generic "$1"
    fi
}
```
and get rid of problems.

**Comment by stefonarch** [comment] 2018-10-28 16:58
Sorry, I don't understand where to modify this....

**Comment by tsujan** [comment] 2018-10-28 17:05
> Sorry, I don't understand where to modify this....

Open `/usr/bin/xdg-open` as root and search for `open_lxqt()` int it.

**Comment by stefonarch** [comment] 2018-10-28 17:32
Hm, does actually the same mess as xdg-open before, opens firefox instead of brave from some applications like discord or telegram.
```
xdg-open <url>
gio open <url>
```
open both firefox, and `echo $BROWSER` is brave. The reason could be those mimeinfo.cache files, I've got three of them (/usr/local/share | /usr/share/ ~/.local/share - all recently updated), deleting all it works, but have still to test.

**Comment by tsujan** [comment] 2018-10-28 17:38
> Hm, does actually the same mess as xdg-open before

Then, the problem wasn't in `xdg-open`. I have no clue where it is.

**Comment by stefonarch** [comment] 2018-10-28 17:43
It's some years I was fighting this, using KDE's systemsettings alongside lxqt settings and symlinking xdg-open to kde-open5 was the solution that worked  best, but it's not quite orthodox, so to say.

**Comment by tsujan** [comment] 2018-10-28 18:07
In the case of your last problem, does kde-open5 work differently from `xdg-open` and `gio`?
