### ISSUE TITLE
Upcoming release

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1490] opened 2018-05-19 14:55 UTC
As mentioned in lxqt/lxqt/issues/1487 we should release fast (aka before Qt 5.11)

I've prepared the release, versions etc - but need help with the release notes. We had the aggreement that our last release notes was far to technical, so we should remove or sum up things as far as possible to prevent TL;DR. 

@palnek @PCMan @selairi @luis-pereira  @tsimonq2 @tsujan @yan12125 

One can find the notes here - feel free to change, it's a wiki post: https://forum.lxqt.org/c/announcements

**Comment by tsujan** [comment] 2018-05-19 15:45
I can do it for libfm-qt and pcmanfm-qt.

**Comment by agaida** [comment] 2018-05-19 16:02
that would be cool -  i removed as much as possible "boring" technical things from the other packages right now - we should put as much as we can in short and understandable words into the highlights - no user and nearly no maintainer is interested in technical details - i will work on the packaging notes meanwhile.

**Comment by tsujan** [comment] 2018-05-19 16:08
Since you said it shouldn't be technical, I made changes to libfm-qt and pcmanfm-qt notes so that ordinary users could understand them. Tell me if more is needed!

I can help with screengrab and also a little with qterminal -- and maybe other components.

BTW, is LXQt ready for Qt5.11? Can all components be compiled against it?

**Comment by agaida** [comment] 2018-05-19 16:11
have done so several times with Arch and kde-unstable activated - to much noise from gcc8 - we should take care later, but latest git was no problem with Arch

**Comment by tsujan** [comment] 2018-05-19 16:20
That gcc8 noise isn't really important and yes, I'll try to silence gcc8 with libfm-qt and pcmanfm-qt later.

As for lxqt-connman-applet, @palinek and @luis-pereira know it much better than I do.

**Comment by agaida** [comment] 2018-05-19 16:50
btw - before i forget - one can find the full test "Release" at https://github.com/4sid - tagged, uptodate changelogs etc

**Comment by tsimonq2** [comment] 2018-05-19 22:28
Did we ever decide to have a social media presence? If nobody objects, mind if I create a few accounts, or at least be in charge of posting there?

**Comment by agaida** [comment] 2018-05-19 22:29
social media like facebook? Why? And who should use/maintain it?

**Comment by tsimonq2** [comment] 2018-05-19 22:41
Nah, Facebook is horrible. Never Facebook.

I'm talking about Mastodon and Twitter, to name two.

I will volunteer to maintain it.

**Comment by agaida** [comment] 2018-05-19 23:01
my point is only that development is boring :P - so for developers it is easy to follow certain repositories on github - thats the source they know and use - and what else we can share on non-dev-related channels? Fixed Bug XY - agaida fixed a typo? - So i guess it would be better to concentrate on our new and shiny forum and maybe create one channel where distributions can spread their latest news about LXQt and their spins

**Comment by tsujan** [comment] 2018-05-19 23:13
> what else we can share on non-dev-related channels? 

None. IMO, a social media would be a source of distraction.

**Comment by tsimonq2** [comment] 2018-05-19 23:34
I disagree.

One thing I heard from a variety of different sources is that the last release announcement didn't have anything besides copy/pasting from changelogs really.

What people want is what /actually/ changed and why they should care.

That being said, I would be more than happy to write such an announcement. But, it would be good to have some sort of social media to be able to post a link to the announcement to.

**Comment by agaida** [comment] 2018-05-19 23:36
if people find such low traffic channel - why not -  and feel free to edit the release notes, any help appreciated

**Comment by agaida** [comment] 2018-05-20 00:28
twitter can work - we should do it - i will take care of -  re blog - i "borrowed" the lxde-blog from medicalwei - so your credentials for blog.lxqt.org should be the same as for blog.lxde.org

**Comment by tsimonq2** [comment] 2018-05-20 00:54
Here we are: https://twitter.com/LXQtOfficial

**Comment by tsimonq2** [comment] 2018-05-20 00:55
I emailed Alf with the password (I hope I used the right key, mine is 5C7ABEA20F8630459CC8C8B5E27F2CF8458C2FA4 ).

If anyone else wants it, just let me know.

(It would be nice to manage that under an @lxqt.org address; for now I used tsimonq2@lubuntu.me )

**Comment by MichaelTunnell** [comment] 2018-05-20 01:57
Social Media accounts is a really good idea and the more the better. Twitter, Mastodon, Diaspora (diasp.org), Google+ (page and community) would all be good options.

More information provided about LXQt the more people who will be interested and release notes that include features details and stuff like that will be very good as well. KDE is a good example because their Plasma release notes provide a lot of good detail which is great for a variety of reasons. Providing clear information about releases also makes it easier for blogs and podcasters (like myself) to cover the releases in more detail without digging.

I covered 0.12.0 release on [my podcast](http://tuxdigital.com/thisweekinlinux) but I could only talk about so much because it was very difficult to find info even though I researched it quite a lot.

Social Media provides mediums to spread different kinds of information like feature snippets and stuff like that to get people excited about new things coming. New feature in the application menu? No need for a full blog post but could totally tweet about it. :+1:

**Comment by jubalh** [comment] 2018-05-20 08:13
> I covered 0.12.0 release on my podcast but I could only talk about so much because it was very difficult to find info even though I researched it quite a lot.

Well.. If you mean by 'researching': looking for existing articles. Then yes. Otherwise its not hard at all. If you join the IRC channel, talk to people, look at code and changes. Real researching, then its pretty easy ;)

**Comment by agaida** [comment] 2018-05-20 18:30
@all - if nothing speak against i want to merge the Bump PRs within the next hour and test the result in Arch.

**Comment by tsujan** [comment] 2018-05-20 18:51
Do it.

Is the problem with lxqt-connman-applet+Qt5.11 fixed without side effects for Qt < 5.11?

**Comment by agaida** [comment] 2018-05-20 19:03
afaik no - but i don't know the state of the applet, so i would leave it out for the moment - if we want to we can release it without pain, if we want to and if it is in a release-worthy state.

**Comment by tsujan** [comment] 2018-05-20 19:07
Oh, all this time, I'd mistaken `lxqt-connman-applet` with `lxqt-common-..`, which was deprecated a long time ago! I use CMST and I really need some sleep ;)

**Comment by agaida** [comment] 2018-05-20 19:08
:)

**Comment by agaida** [comment] 2018-05-20 19:14
+1 for pull requests, discussions and to postpone it :)

**Comment by agaida** [comment] 2018-05-20 19:52
All needed bumps should be in place - now to the funny part of the evening - rebuild the whole thing in Arch :)

**Comment by jubalh** [comment] 2018-05-20 20:35
@agaida No need. OBS already [built](https://build.opensuse.org/project/show/X11:LXQt:git) all of the packages. Updating right now to see how everything behaves.

**Comment by agaida** [comment] 2018-05-20 20:39
with Qt 5.11 and gcc-8 ? :P

**Comment by jubalh** [comment] 2018-05-20 20:56
> with Qt 5.11 and gcc-8 ? :P

X11:LXQt:git uses the defaults of Tumbleweed. So that is: gcc 7, Qt 5.10

Let's talk about such things before the next release. We already have Qt 5.11 in a sepreate devel project. I could have copied X11:LXQt:git (which builds new every time we make a commit to upstream master) to X11:LXQt:pre-release or something and tell the project to build against Qt 5.11 using gcc8.

OBS is good for automating various such cases and building them automatically.
I will open a forum post about this soon. Maybe you guys can describe me what scenarios in general terms are needed and I can set them up in OBS.

Then you don't have to build this stuff manually.

**Comment by agaida** [comment] 2018-05-20 20:57
Now the same thing for sid

**Comment by jubalh** [comment] 2018-05-20 20:59
![showlxqt](https://user-images.githubusercontent.com/1658215/40283613-5e1d4a4a-5c81-11e8-8c4b-8ebc031abc3d.png)
;) Build all automatically and installed through normal package manager.

Let's talk about it soon in the forum.

**Comment by tsujan** [comment] 2018-05-21 03:43
So, it's fine with Qt 5.11 and 5.10, under Arch and OpenSUSE. I'm sure it's OK under Debian sid too.

**Comment by tsimonq2** [comment] 2018-05-21 05:32
Please wait for an ACK from me before publishing the release announcement/notes.

**Comment by agaida** [comment] 2018-05-21 12:39
@tsimonq2  - hurry up :P

**Comment by agaida** [comment] 2018-05-21 14:59
@all - if there is no last minute blocker i will start with tagging and uploading in a half hour

**Comment by luis-pereira** [comment] 2018-05-21 15:03
Nothing that comes to mind.
Completely out of time these days

**Comment by tsujan** [comment] 2018-05-21 15:03
> if there is no last minute blocker...

Everything seems good.

**Comment by agaida** [comment] 2018-05-21 17:32
@tsimonq2 - it would be nice if you would do your review within the next 2 hours

**Comment by tsimonq2** [comment] 2018-05-21 18:09
I can do that.

It's 1:09 PM right now for me. I'll have my review done by 2:30 at the very latest.

**Comment by agaida** [comment] 2018-05-21 18:14
fine

**Comment by agaida** [comment] 2018-05-21 20:06
https://downloads.lxqt.org and https://downloads.lxqt.org/current.html ready

**Comment by agaida** [comment] 2018-05-21 20:58
forum, blog and lxqt.org have release notes now - blog and l.org have something in common - the CSS is fucking ugly. We should improve it.

@tsimonq2 Would you be so kind and take care of twitter and lists.lxde.org?

**Comment by palinek** [comment] 2018-05-21 21:11
>  lxqt.org have release notes now

The screenshots are still "0.10.0"  :-)

**Comment by agaida** [comment] 2018-05-21 21:12
oldies but goldies - and yes, we should change that

**Comment by agaida** [comment] 2018-05-21 21:16
and before i forget - can someone check our github releases - just to be sure that don't upload the wrong files

**Comment by tsujan** [comment] 2018-05-22 06:14
Just wanted to thank you all. Whenever a new release is made, I say to myself, "this is better than the previous one." The more releases, the more feedback and the better LXQt will become :)

**Comment by selairi** [comment] 2018-05-22 07:45
May I suggest adding links to blogs or social media of members of the LXQt community in lxqt.org?
In LXQt community are people from Taiwan, Germany, USA, Spain, France,...  We could write a few words about LXQt in our social media channels in English, French, Spanish,... This could help to people knows about LXQt in their own language.

**Comment by palinek** [comment] 2018-05-22 08:01
As the release was done... I've moved all the open issues from milestone 0.13 to newly created 0.14

**Comment by jeremywh7** [comment] 2018-05-22 18:54
Great release guys!  However, the user perspective (e.g. from the Phoronix announcement) is still that the Release Notes are still too technical.  :-)  Half of the "Highlights" are Developer details, and the blog link only shows that and the "Packagers" notes.

The full Release Notes' "Notable Changes" sections have relevant user info that I'd suggest in the future be separated out.  The Developers(/technical) details can have it's own section after the Users then Packagers details, so that the user-oriented info is front-facing in the blog, for users that don't bother to link to the full info.  Something like:

* Highlights:
  blah [general stuff like Qt version-dependent changes]
  lxqt-config: blah
  lxqt-panel: blah
  lxqt-powermanagement: blah

* Notes for Packagers:
  blah:

* Notes for Developers:
  blah:

**Comment by MichaelTunnell** [comment] 2018-05-22 19:18
@jubalh 
> Well.. If you mean by 'researching': looking for existing articles. Then yes. Otherwise its not hard at all. If you join the IRC channel, talk to people, look at code and changes. Real researching, then its pretty easy ;)

Thank you for providing such a fantastic example of how not to talk to people. This will come in handy for the future for developers to reference of what not to do.

**Comment by tsujan** [comment] 2018-05-22 19:54
> However, the user perspective (e.g. from the Phoronix announcement) is still that the Release Notes are still too technical. :-) 

I don't think so. There are always people who prefer ranting to reading: "So what's actually new here that benefits the end users and why would I want to install it?"

**Comment by rapgro** [comment] 2018-05-22 20:20
We obviously need some help in Fedora to update all those packages.

**Comment by agaida** [comment] 2018-05-22 20:46
@MichaelTunnell - i don't think so - but hey, if you are willing to translate our technical changelogs in things that are of interest for users - fine, you have a job. I'm out of ideas.

@rapgro - why, we didn't change much and introduced only one soname-bump in libfm-qt - so 90% of the work is just to change the sources and be done with :sunglasses:  - Hmm, one should change the version in the rpm file too.

**Comment by tsujan** [comment] 2018-05-23 16:26
@jeremywh7 We did our best in squeezing out a summary from months of work. Maybe, we'll do better next time but your help would be appreciated then.

The first time I installed LXQt, I hadn't read any blog. In that time, LXQt had many bugs, so I uninstalled it. However, just a few months later, I was so curious that I installed its newer version (by using @agaida's deb packages) and saw the great amount of work that had been done. So simple! Since then, it's my main DE.

My point: the ranting type will always rant and those who can appreciate a good work will find it.

**Comment by agaida** [comment] 2018-05-23 16:32
and i see another problem with the notes - if we really translate the most things into user readable text the reaction would be: "Hey, are you guys kidding me - what you describe are mostly basics that i expect to work ..." and from a user perspective the user is right :sunglasses: Really, 80-90% of our notes readed that way would grant us the "Captain Obvious Award" for life time - and leave potential developers out. - So my try was to put the obvious part into the hightlights and the more detailed things into the noteworthy packaging changes.

**Comment by tsujan** [comment] 2018-05-23 16:42
IMO, there's no clear-cut category called "users". I'm a user and a developer at the same time. A user my not be a developer but have a good knowledge of his/her distro; another user may not have that knowledge but be intelligent enough not to take this or that for granted; another one may be stupid enough to take everything for granted, and so on and so forth.

**Comment by agaida** [comment] 2018-05-23 16:43
also true :P

**Comment by tsujan** [comment] 2018-05-23 18:03
> But a Qt dev I am not; I do C.

I may have told you this before: If you do C, you could do C++ and Qt too ;)

**Closed** 2018-05-23 21:36 UTC
Labels: high-priority

**Comment by telmo1241** [comment] 2021-03-12 13:31
> Aqui estamos: https://twitter.com/LXQtOfficial

nothing has been posted on Twitter for a long time
Would you mind if I managed the account and had to announce new updates to lxqt etc?

**Comment by jubalh** [comment] 2021-03-12 13:39
I already wrote to the person who has rights to the account that I would manage it. But I didn't get any reply.

**Comment by telmo1241** [comment] 2021-03-12 13:45
@tsimonq2

**Comment by stefonarch** [comment] 2021-09-08 10:40
@tsimonq2 ??

**Comment by stefonarch** [comment] 2021-09-08 14:10
I got this answer, they're fast:

Hello,
 
The account you have reported is currently inactive. We can release this username for your brand's use by transferring the username to a Twitter account that you manage. We can either rename an account you currently have or transfer the username to a new placeholder account that you create.
 

> To proceed with the transfer, simply reply to this email with the username of the account you want renamed with the requested username. This could be an existing Twitter account that you want renamed or a new placeholder account (for example, twitter.com/temp123 or @temp123). Once we receive the username for the existing account you want renamed or placeholder account, we will apply the requested username to it.
> 
>    * A username transfer only changes the username of your account. 
>    * All the existing content on your existing or placeholder account (followers, Tweets) will remain intact. 
>    *  A username change will not affect your existing followers, Direct Messages, or replies. Your followers will simply see a new username next to your picture when you Tweet.
>     Since other users will need to mention and message you at your new username, you may find it helpful to post a Tweet to let your followers know that you've selected a new username. 
> 
> After the transfer, your previous or temporary placeholder username will be released immediately for use by other accounts.
>  
> Safety tip: We strongly advise you to use an email address at your company’s official domain with your Twitter account. This makes it much easier for us to help you if you should encounter issues with your account in the future. To learn how to change the email address of a Twitter account, see https://support.twitter.com/articles/15356.
> 

The problem is that there is no "official" email where several people have access to active. I remember to have heard that there is multiple access with more users possible.

@telmobss1 @jubalh

**Comment by stefonarch** [comment] 2021-09-08 21:06
I set up an temp account https://twitter.com/LxqtTemp and I see no way to add other people, except https://techcrunch.com/2015/02/17/share-twitter-account/ which looks working for who is already on twitter.

![schermata-09-08-23-05](https://user-images.githubusercontent.com/10681413/132585553-b1d2d760-14d2-493a-bc90-ee46ca5a873e.png)


Other solution: configuring an shared email address somewhere.

Question: who is interested/available to keep twitter up and running?

**Comment by telmobss1** [comment] 2021-09-08 22:18
I won't have a computer for a while now, but if that's okay, it could help.

**Comment by jubalh** [comment] 2021-09-09 06:47
@stefonarch I can help with twitter. Doing this for another project too.

**Comment by stefonarch** [comment] 2021-09-09 07:04
Ok, thanks! Probably sharing passwd works, only issue could be asking for a 2FA which is atm my phone, I've an account but use hardly twitter so I'm not expert with  settings.

**Comment by jubalh** [comment] 2021-09-09 07:10
>  only issue could be asking for a 2FA which is atm my phone

On the other project that I help with we also share passwords. But for 2FA we used the email where several people have access to. Should be possible here too?

**Comment by stefonarch** [comment] 2021-09-09 07:42
> . But for 2FA we used the email where several people have access to. Should be possible here too?

Perfect would be an twitter@lxqt-project.org, otherwise we can agree to riseup, gmail or whatever.

[Reading again](https://github.com/lxqt/lxqt/issues/1490#issuecomment-915274245) I'm doubtful about the existing content/followers in lxqtofficial - looks like loosing all?

**Comment by stefonarch** [comment] 2021-09-09 20:29
Wrote again to twitter, they will not let us access the existing account, saying they are unable to verify us, 
So it looks like transferring the account and start from scratch or leave it as it is...
