### ISSUE TITLE
Panel buttons are cut off on both sides with breeze theme

### ISSUE THREAD

**Issue by E5ten** [lxqt/lxqt#1525] opened 2018-07-21 20:53 UTC
##### Expected Behavior
the icon should be fully visible on the left with excess text being cut off on the right

##### Current Behavior
the icon and text are centered, causing excess text to push text and the icon off on the left, and text on the right.

##### Steps to Reproduce (for bugs)
1.  Install breeze
2.  Set breeze as Qt theme
3.  Cause an apps title in lxqt-panel to be longer than can fit in the button

##### Context
It has made my bar look less good, and in cases where the icon is fully cut off, harder to navigate.
![image](https://user-images.githubusercontent.com/24554283/43039972-9c0e70bc-8d06-11e8-8f34-44a1cbe1c9ba.png)

##### System Information

* Distribution & Version: Arch
* Kernel: 4.17.8
* Qt Version: 5.11.1
* liblxqt Version: 0.13.0
* Package version: 0.13.0-1

**Comment by tsujan** [comment] 2018-07-21 22:38
I'm afraid that should be a problem with KDE themes -- Breeze and Oxygen alike. All themes that come with Qt (Fusion included), Kvantum and partly QtCurve (with a minor problem: lack of ellipsis) work fine.

KDE themes are developed by KDE devs and we have no control over them. Since this only happens with Breeze+LXQt System theme, there are many ways to avoid it.

**Comment by simoniz0r** [comment] 2018-07-22 15:44
I think it's worth looking into on your end as this doesn't happen with other Qt based panels (lumina's panel for example).

**Comment by agaida** [comment] 2018-07-22 16:00
excuse me - we talking about what? Using the breeze theme engine might be not the very best idea - it never was - using the icons is fine. But if one expect these themes to work i would call it wrong assumtion.

**Comment by simoniz0r** [comment] 2018-07-22 16:02
Please drop your hatred of breeze.  This could be an issue with your panel and not breeze at all.

**Comment by agaida** [comment] 2018-07-22 16:03
nope - there is no hatred - only false assumtions.

**Comment by tsujan** [comment] 2018-07-22 16:31
> nope - there is no hatred - only false assumtions.

@agaida, you could safely ignore @simoniz0r's comments. It would be a waste of time to reply to them.

**Comment by simoniz0r** [comment] 2018-07-22 16:52
>@agaida, you could safely ignore @simoniz0r's comments. It would be a waste of time to reply to them.

Wow.  Thanks.  I'll remember to never bring up legit complaints to the LXQt team again.

**Comment by tsujan** [comment] 2018-07-22 16:58
Helpful issue reports (like this one) or comments are appreciated because they make programs better, whether directly or indirectly. Of course, they require knowing the difference between helpful and nonsense.

**Comment by simoniz0r** [comment] 2018-07-22 17:02
>they require knowing the difference between helpful and nonsense.

You would think that members of the LXQt team would do the same.  You insulting me doesn't help anything.

**Comment by tsujan** [comment] 2018-07-22 17:17
Ha ha.. You've mistaken here with Facebook...

**Comment by tsujan** [comment] 2018-07-22 17:21
OK, crap talking aside, I'll investigate why Breeze may be different in this regard when I find time -- it isn't a priority though.

**Comment by tsujan** [comment] 2018-07-22 18:19
Found the reason:

In `breezestyle.cpp` → `drawToolButtonLabelControl`, breeze searches for the *KDE-specific* widget property `PropertyNames::toolButtonAlignment` and does a bad thing: if it isn't found (which, of course, isn't found in LXQt), Breeze will center the contents of tool-buttons; hence the issue reported here.

No other widget style does such a thing. We can add a workaround to the task button code for that. However, I think it's a very bad idea. If Breeze wants to have KDE-specific properties, why should we care?

What we *should* do may not be easy: we should draw the contents of our task buttons ourself because it's a legal thing to center them in a widget style. No other style does so (and even Breeze does it in a special case) but it's acceptable.

All in all, this report shows a potential problem and is quite valid, IMO.

**Comment by tsujan** [comment] 2018-07-22 18:41
And before someone does that, I emphasize that when the contents are to be draw, the panel should be drawn too, which means the whole task-button style should be enforced, because otherwise, it'll be broken by this or that widget style.

Let me be more specific:

On the one hand, it was wrong, in the first place, to let tool-buttons *whose widths we limited* be drawn by widget styles. It may work with all styles except for Breeze but there's no guarantee that it'll work with future widget styles.

On the other hand, if we style task buttons in the code, the "System" theme will be contradicted, while it's needed as a good option.

Professional ideas are welcome.

**Comment by E5ten** [comment] 2018-07-22 20:15
Is there an easy thing to change in breezestyle.cpp that could be a temporary solution for myself or others using breeze?

**Comment by tsujan** [comment] 2018-07-22 20:30
I can't be sure unless I recompile it but I prefer to focus on the task-button code to find a way out of this. However, if you want to recompile Breeze-5.13.3 (here, I have that version), you could try this:

Find these lines:
```c++
            const bool leftAlign( widget && widget->property( PropertyNames::toolButtonAlignment ).toInt() == Qt::AlignLeft );
            if( leftAlign ) {
                const int marginWidth( Metrics::Button_MarginWidth + Metrics::Frame_FrameWidth + 1 );
                iconRect = QRect( QPoint( contentsRect.left() + marginWidth, contentsRect.top() + (contentsRect.height() - iconSize.height())/2 ), iconSize );
            }
            else {

                const int contentsWidth( iconSize.width() + textSize.width() + Metrics::ToolButton_ItemSpacing );
                iconRect = QRect( QPoint( contentsRect.left() + (contentsRect.width() - contentsWidth )/2, contentsRect.top() + (contentsRect.height() - iconSize.height())/2 ), iconSize );

            }
```
and replace `if( leftAlign )` with `if(true)`.

Have a copy of Breeze's installable package to re-install it if something goes wrong.

**Comment by agaida** [comment] 2018-07-22 20:43
ok, with my limited understanding of C++ one can write this like that:
```
const bool leftAlign( widget && widget->property( PropertyNames::toolButtonAlignment ).toInt() == Qt::AlignLeft );
const int marginWidth( Metrics::Button_MarginWidth + Metrics::Frame_FrameWidth + 1 );
iconRect = QRect( QPoint( contentsRect.left() + marginWidth, contentsRect.top() + (contentsRect.height() - iconSize.height())/2 ), iconSize );
```
but i guess upstream wouldn't like this change

**Comment by tsujan** [comment] 2018-07-22 20:44
> This worked

@E5ten Happy to hear that. And you did it so fast!

> I'll still look forward to lxqt-panel drawing the contents of the buttons itself.

If you select any LXQt theme other than the System theme, you won't have this problem. I'm searching for a solution that doesn't require painting the button with the System theme because otherwise, and as said above, that would be a contradiction. I think only LXQt has a System theme (which leaves the drawing to the widget style). That's a good feature we shouldn't damage, IMO.

**Comment by tsujan** [comment] 2018-07-22 20:46
@agaida Yes, but that workaround would be specific to Breeze. Although rarely, other widget styles might do the same ting but without `PropertyNames::toolButtonAlignment` -- at least, that's quite possible. IMHO, we shouldn't add KDE-specific codes to ours; it would be ugly.

**Comment by E5ten** [comment] 2018-07-22 20:46
Yeah I already have a setup with the breeze PKGBUILD and stuff because I modify the package, so all I had to do was add a sed line to the PKGBUILD and make it.

**Comment by tsujan** [comment] 2018-07-22 20:48
@E5ten Good! So, from now on, I'll count on your skill in compiling and installing the latest packages if you report issues :)

**Comment by agaida** [comment] 2018-07-22 20:50
@E5ten - and before i forget - quilt works fine with PKGBUILDs as far as i remember - but sed is ok too :P

**Comment by E5ten** [comment] 2018-07-22 20:50
I don't even know what quilt is, I'll check it out.

**Comment by agaida** [comment] 2018-07-22 20:51
a quilt might be made of patches :P

**Comment by tsujan** [comment] 2018-07-22 23:55
OK, contrary to what I said above, this isn't just about centering button contents -- which can be done correctly in any style -- but about a real bug in Breeze. This is the explanation:

Every style should be prepared for cases where there isn't enough space for a widget's contents. Breeze isn't, in this case. The following piece of code, inside `breezestyle.cpp` → `Style::drawToolButtonLabelControl`, is wrong:
```c++
            else {

                const int contentsWidth( iconSize.width() + textSize.width() + Metrics::ToolButton_ItemSpacing );
                iconRect = QRect( QPoint( contentsRect.left() + (contentsRect.width() - contentsWidth )/2, contentsRect.top() + (contentsRect.height() - iconSize.height())/2 ), iconSize );

            }
```
The value of `contentsWidth` is the sum total of icon width, text width and an arbitrary spacing, *as if the button width should be, at least, equal to it*, which is a false presupposition: Qt gives us no guarantee that there's enough space for the text -- `contentsRect.width() - contentsWidth` can be negative.

Other widget styles put the icon at the left side of the *real rectangle* (with some spacing) and draw the text after it, so that if the button width isn't enough for it, the text will be cut (Kvantum even elides the text in such cases). We've added a simple code for the task-button, so that the text will be elided with all styles as far as possible. However, KDE didn't deal with such a scenario in Oxygen's code and the problem is inherited by Breeze.

I close this for the above-mentioned reasons. If someone is willing to report the issue to the KDE bug tracker, he/she could quote this comment.

**Closed by tsujan** 2018-07-22 23:55 UTC
Labels: enhancement

**Comment by palinek** [comment] 2018-07-23 05:45
> Every style should be prepared for cases where there isn't enough space for a widget's contents. Breeze isn't, in this case...

@tsujan Good job in investigating the real reason

**Comment by tsujan** [comment] 2018-07-23 11:00
@palinek thanks!

**Comment by chimak111** [comment] 2018-08-10 17:10
Bug reported: https://bugs.kde.org/show_bug.cgi?id=397337

**Comment by tsujan** [comment] 2018-08-10 17:45
@chimak111 Good!

If I remember correctly, Breeze (Oxygen) dose the same thing in some other places too. Since a widget's label (text + icon) is drawn by the widget style, the latter is also responsible for considering the *real* widget rectangle, inside which the label should be drawn.

Of course, a developer can make a hard-coded style to circumvent such issues but that's not relevant here because the System theme is supposed to be drawn by the active widget style (Breeze, in this case); in other words, it isn't a theme.
