### ISSUE TITLE
Screensaver/Lock-Screen only hides top (of two vertically aligned displays)

### ISSUE THREAD

**Issue by guiverc** [lxqt/lxqt#1705] opened 2019-04-11 10:26 UTC
Two displays (1920x1080) but when screensaver takes effect, both screens dim briefly before only one gets hidden by it, the other is fully visible & updates.  This occurs when screens are vertically aligned (one above the other)

Lock-Screen on LXQt menu also does not work (for lower display) with same screen alignment
 

##### Expected Behavior

Both displays should be hidden by screensaver, so people cannot read any confidential information on display on a 'locked' system.

##### Current Behavior

This occurs as installed, until you use Monitor.Settings to adjust the default-right display to be below the default-left display - now only the top display gets hidden by xscreensaver.

https://bugzilla.opensuse.org/attachment.cgi?id=802602
shows the screensaver active on upper display, but firefox bug.report, glances is fully visible despite the screen being locked on the bottom display.  My screens aren't perfectly aligned (horizontally), but even if setup one directly below the other you get the same result. 

##### Steps to Reproduce (for bugs)

1. have two displays (mine are 1920x1080), set what starts default-right so it's positioned below the default-left display
2. open Screensaver.Preferences and click "Preview".  The top display will show screensaver and the bottom display shows nothing
3.  alternatively set "blank after" to 1 minute, then wait a minute.  You'll note both screen go dark then the top shows screensaver, whilst bottom returns to normal. You cannot use either until you've entered password, but you can fully see & read the lower screen (eg. glances in my picture kept updating)

##### Context

You cannot rely on screensaver or the LXQt "Lock Screen" function to lock your lower display; it only works for upper display when two are aligned vertically.

##### System Information

- Distribution & Version: opensuse tumbleweed & lubuntu 19.04
- Kernel: 5.0.5-1 & 5.0.0-8
- Qt Version: 0.14.1 & 0.14.1
- liblxqt Version: 0.14.1 & 0.14.1
- Package version: liblxqt-devel 0.14.1-1.1 x86_64 & liblxqt0 x86_64 0.14.1-0ubuntu1

https://bugzilla.opensuse.org/show_bug.cgi?id=1132184
https://bugs.launchpad.net/ubuntu/+source/xscreensaver/+bug/1814490

**Comment by tsujan** [comment] 2019-04-12 08:23
Probably, like https://github.com/lxqt/lxqt/issues/1704 and https://github.com/lxqt/lxqt/issues/1703. I didn't close it because I don't use screensaver/lock screen. Waiting for an LXQt dev to test it.

**Comment by guiverc** [comment] 2019-04-12 09:04
Please also test swapping your top & bottom screens if this doesn't occur.  If I setup my 'top' screen as the bottom display, and 'bottom' as the top using Monitor.Settings, other than screwing up with my sense of reality (with regards mouse-control) the behavior does NOT occur.

My instructions (how it occurs for me) maybe created the opposite position as to what it did for me.  I tested this using Lubuntu 19.04's which I run on a dell optiplex 960, and Opensuse tumbleweed which runs on a hp 8200 which both have the same screen layout; the sit next to each other but do not share displays.

**Comment by tsujan** [comment] 2019-04-12 09:17
Yes, you're right about swapping.

I have a feeling that this, https://github.com/lxqt/lxqt/issues/1704 and https://github.com/lxqt/lxqt/issues/1703 have the same cause.

**Comment by guiverc** [comment] 2019-04-20 05:29
Quick note:  On my main Lubuntu 19.04 box the other two issues (#1703 & #1704) haven't occurred for ages (which I noticed & possibly explained in the guess on April 12 #1704), but this screensaver issue remains, so it maybe separate.  Likewise the #1709 issue may also be similar but unrelated (it like screensaver issue hasn't disappeared with play)

**Comment by atsepkov** [comment] 2019-08-12 18:01
I have a similar issue with 3 monitors. I have 1 labeled as "primary" and 2 as "extended" (one to the left of primary and 1 to the right). When I lock screen, all 3 screens dim, but the primary comes back on a second later. The machine is still in "locked" state (and requires password to show the 2 dimmed screens) but the primary is completely visible while the machine is supposedly locked.

**Comment by guiverc** [comment] 2019-10-25 06:36
Another touching-base follow-up, this issue still occurs for me with Lubuntu 20.04 latest daily (kernel 5.3.0-19, LXQt 0.14.1, Qt 5.12.4) plus my installed system (same Lubuntu), & opensuse tumbleweed.

**Comment by palinek** [comment] 2019-10-25 07:05
What is the difference with using `xscreensaver` in different DE? Is it the same with KDE, Xfce, Gnome ... ?

**Comment by guiverc** [comment] 2019-10-25 07:28
When using another desktop (or live system with screens configured to match my setup) I have no issues.  This my primary Lubuntu 20.04 installed system does not have the issue if I login with XFCE, MATE or GNOME (nor with LXDE though I haven't done that in ages). If I use a 'live' system I also don't have the issue with Kubuntu/KDE. The box with opensuse tumbleweed only has the issue in LXQt also (I'd have to boot it to list, but I believe it has LXQt, KDE, MATE & XFCE installed).

(Note: XFCE (4.14) no longer uses xscreensaver on 19.10 & 20.04 so some comparisons are old; if MATE or GNOME have been changed I may also not have noticed as I mostly use LXQt and to a lesser extent XFCE)

These are multiple desktops installed on the same system, and the issue only occurs when LXQt is running.  When I boot a 'live' system and the screens are the default left-right setup the issue does NOT occur. My screens however are positioned one above the other and the issue only occurs  in that setup (but note if I swap bottom & top displays the issue also does NOT occur - only when displays match my actual setup). The same occurs on multiple boxes though with almost identical screen arrangement.

The un-hidden screen is updated; so if `htop` etc is on a window,  it can be seen to update with screensaver only hiding my 'top' display.

**Comment by guiverc** [comment] 2019-11-02 11:19
I upgraded my fedora 30 box today to f31.   this issue impacts fedora
hardware: hp 8200 elite sff (i5-2400, 8gb, nvidia quadro 600)

kernel 5.3.7-301.fc31.x86_64, LXQt 0.14.1, Qt 5.12.5

**Comment by guiverc** [comment] 2019-11-03 10:57
booting siduction-patience-lxqt-amd64-latest.iso 2019-11-02
adjust displays so vertical placement, screensaver (preview) only hides top display, lower display.  
(Swap top/bottom and screensaver covers both displays, so one combination of top/bottom only is a problem.)

**Comment by guiverc** [comment] 2019-11-15 08:57
I changed screens on a box to have another box with vertically aligned screens (for testing). It is running a very recently installed debian-testing install, with https://lxqt.debian.net/ as a source (provided by @agaida on irc).

liblxqt 0.14.1
Qt 5.12.5
screensaver 5.42+dfsg1-1

I could **NOT** reproduce this issue on this box :)

**Comment by tsujan** [comment] 2019-11-15 09:56
@guiverc Thanks for the feedback! If you have the latest panel patches, I think the other related issues you reported shouldn't be reproducible anymore either.

**Comment by tsujan** [comment] 2019-11-15 10:11
Closed in https://github.com/lxqt/lxqt-panel/pull/1261

**Closed by tsujan** 2019-11-15 10:11 UTC
