### ISSUE TITLE
xdg-open support

### ISSUE THREAD

**Issue by HongxuChen** [lxqt/lxqt#561] opened 2015-03-27 10:44 UTC
Currently `xdg-open` in Debian Jessie cannot recognize when `XDG_CURRENT_DESKTOP` is set to **LXQt** (where lxqt is installed via http://packages.siduction.org/lxqt), so it changes to its default behavior, which causes many issues when using regular `xdg-open`.

**Comment by Vladimir-csp** [comment] 2015-03-27 18:44
what issues are caused by going trough open_generic function?

**Comment by jleclanche** [comment] 2015-03-27 18:54
This is an issue which was fixed in an xdg release last year. Debian Jessie packagers will have to install a more up to date version of xdg-open.

CC @lxde/release-maintainers

**Comment by HongxuChen** [comment] 2015-03-28 01:38
@Vladimir-csp For example, when using `xdg-open .` in a certain terminal emulator, an unexpected application will be started (in my case, the audacious player). But when I tweaked `xdg-open` script a bit to make it work exact as `LXDE` (of course `pcmanfm` was changed to `pcmanfm-qt`), everything works fine.

As @jleclanche said, this is not an issue if Debian Jessie packagers are using a newer one.

**Comment by Vladimir-csp** [comment] 2015-03-28 01:58
open_generic in xdg-open is usually most reliable, it should choose current MIME association with file, without any DE tweaks.

You can check the association with:
```xdg-mime query default `xdg-mime query filetype $FILE_NAME````

and change default application with:
```xdg-mime default $APPLICATION $MIME_TYPE```

**Comment by HongxuChen** [comment] 2015-03-28 02:06
Yes, you're right. I think there is something wrong in one of
my mimeapps.list files. But I failed to locate the entry; even after I
deleted all my *local* mime type files I was not able to open with the
right application.
Personally I think lxqt and lxde should be treated as "the same class
citizen" by xdg-open.

**Comment by MttCastelli** [comment] 2015-05-02 10:32
the removable media device menager on the panel is some way buggy: (1) do not see my android phone when it is connected, while pcmanfm-qt shows it between devices, (2) and if I connect an usb and try to open trough it, manager launches audacious. Strange!

**Closed** 2018-07-15 11:50 UTC
Labels: downstream
