### ISSUE TITLE
Battery info applet shows invalid information

### ISSUE THREAD

**Issue by plasticassius** [lxqt/lxqt#1761] opened 2020-01-11 15:38 UTC
Battery info applet shows invalid information

Expected Behavior
I would expect that Energy Full is less than Energy Full Design. And, that Energy Now is less than Energy Full, and Energy Now / Energy Full = % charged.

Current Behavior
The battery info applet one of two sets of information:
1.
State: Charging
Energy Full Design: 42.00 Wh
Energy Full: 121.27 Wh (94%)
Energy Now: 121.27 Wh (8%)
Energy rate: 0.03 W
2.
State: Fully Charged
Energy Full Design: 42.00 Wh
Energy Full: 121.27 Wh (94%)
Energy Now: 39.71 Wh (100%)
Energy rate: 0.01 W

Steps to Reproduce (for bugs)
I leave the laptop charging almost all of the time, and often leave it in sleep mode instead of off. The battery info applet one of two sets of information (that I've noticed). I haven't investigated what happens when I let the battery discharge.

Context
It is hard to have confidence in the numbers reported since the Energy Full value is about 3 times larger than the Energy Full Design value. While it is possible that the battery is charged to 3 times the amount of energy it was designed for, is that really the case? Also, it isn't clear what 121.27 is 94% of, or 8% of, for that matter. Also, why is 39.71 Wh fully charged (is that considered 100% of 42.00 Wh)?

System Information
* Distribution & Version: Debian GNU/Linux 10
* Kernel: 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
* Qt Version: 5.11.3
* liblxqt Version: 0.14.1
* Package version: 0.14.1-1
![battery0](https://user-images.githubusercontent.com/20727345/72206639-b97af700-3490-11ea-8729-ef03315932c2.png)
![battery1](https://user-images.githubusercontent.com/20727345/72206641-b97af700-3490-11ea-9c3c-a08f52718227.png)

**Comment by agaida** [comment] 2020-01-11 17:16
we accept pull requests

**Comment by stefonarch** [comment] 2020-01-11 18:33
Check the values in the files in /sys/class/power_supply/BAT0/ 
My guess is that those are the source of the problem, so not related to LXQt.

**Comment by plasticassius** [comment] 2020-01-12 10:21
I'll post a pull request if I get that far with this.

For now I'd like to record a comparison between what I read from /sys/class/power_supply/BAT0/ vs the battery applet:

Energy Full Design: 42.00 Wh doesn't seem to match charge_full_design: 3684000
Energy Full: 121.31 Wh (94%) is way off charge_full: 3483000 and doesn't seem to be related to any other number in BAT0
Energy Now: 39.71 Wh (100%) is not quite charge_now: 3483000

$cat capacity
100
$cat capacity_level
Full
$cat charge_full
3483000
$cat charge_full_design
3684000
$cat charge_now
3483000
$cat current_now
1000
$cat cycle_count
0
$cat manufacturer
BYD
$cat model_name
DELL FW8KR87
$cat present
1
$cat serial_number
1995
$cat status
Full
$cat technology
Li-ion
$cat type
Battery
$cat uevent
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Full
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11400000
POWER_SUPPLY_VOLTAGE_NOW=12444000
POWER_SUPPLY_CURRENT_NOW=1000
POWER_SUPPLY_CHARGE_FULL_DESIGN=3684000
POWER_SUPPLY_CHARGE_FULL=3483000
POWER_SUPPLY_CHARGE_NOW=3483000
POWER_SUPPLY_CAPACITY=100
POWER_SUPPLY_CAPACITY_LEVEL=Full
POWER_SUPPLY_MODEL_NAME=DELL FW8KR87
POWER_SUPPLY_MANUFACTURER=BYD
POWER_SUPPLY_SERIAL_NUMBER=1995
$cat voltage_min_design
11400000
$cat voltage_now
12444000

![bat](https://user-images.githubusercontent.com/20727345/72217275-78d0bb80-352c-11ea-8039-351b1ef7fbdc.png)

**Comment by plasticassius** [comment] 2020-01-12 12:44
also...

$cat alarm
0
$cat capacity
8
$cat capacity_level
Normal
$cat charge_full
39694000
$cat charge_full_design
25627000
$cat charge_now
3483000
$cat current_now
1000
$cat cycle_count
0
$cat manufacturer
Sony
$cat model_name
,DELL FW8KR87
$cat present
1
$cat serial_number
51968
$cat status
Unknown
$cat technology
Unknown
$cat type
Battery
$cat uevent
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Unknown
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Unknown
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=34829000
POWER_SUPPLY_VOLTAGE_NOW=12444000
POWER_SUPPLY_CURRENT_NOW=1000
POWER_SUPPLY_CHARGE_FULL_DESIGN=25627000
POWER_SUPPLY_CHARGE_FULL=39694000
POWER_SUPPLY_CHARGE_NOW=3483000
POWER_SUPPLY_CAPACITY=8
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=,DELL FW8KR87
POWER_SUPPLY_MANUFACTURER=Sony
POWER_SUPPLY_SERIAL_NUMBER=51968
$cat voltage_min_design
34829000
$cat voltage_now
12444000

![bat](https://user-images.githubusercontent.com/20727345/72219008-90666f00-3541-11ea-9fd6-e8ddb8b75c3d.png)

**Comment by mokraemer** [comment] 2020-01-21 09:20
I can confirm the battery applet /powermanagement has invalid battery state.
Battery applet in tray show 89% (discharging), while acpi shows 19% (charging) and /sys/class/power_supply/BAT0/ has equivalent information.
My guess is the state / registration is not renewed after suspend, so it shows the state before suspend.

**Comment by plasticassius** [comment] 2020-01-21 15:16
I can confirm that the battery applet has a more sensible state after a clean boot (attached below). It's after a resume that the state gets corrupted (particularly Energy Full and Energy Now). However, it doesn't correspond to the state before suspend, rather some other values seem to get loaded.

$cat capacity
100
$cat capacity_level
Full
$cat charge_full
3483000
$cat charge_full_design
3684000
$cat charge_now
3483000
$cat current_now
1000
$cat cycle_count
0
$cat manufacturer
BYD
$cat model_name
DELL FW8KR87
$cat present
1
$cat serial_number
1995
$cat status
Full
$cat technology
Li-ion
$cat type
Battery
$cat uevent
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Full
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11400000
POWER_SUPPLY_VOLTAGE_NOW=12290000
POWER_SUPPLY_CURRENT_NOW=1000
POWER_SUPPLY_CHARGE_FULL_DESIGN=3684000
POWER_SUPPLY_CHARGE_FULL=3483000
POWER_SUPPLY_CHARGE_NOW=3483000
POWER_SUPPLY_CAPACITY=100
POWER_SUPPLY_CAPACITY_LEVEL=Full
POWER_SUPPLY_MODEL_NAME=DELL FW8KR87
POWER_SUPPLY_MANUFACTURER=BYD
POWER_SUPPLY_SERIAL_NUMBER=1995
$cat voltage_min_design
11400000
$cat voltage_now
12290000
![bat](https://user-images.githubusercontent.com/20727345/72816477-7ecf4680-3c68-11ea-831a-d12d5bc0f51c.png)

**Comment by tsujan** [comment] 2020-02-17 16:15
This problem has never happened with my two laptops, whether before or after resuming from suspend.

lxqt-powermanagement uses the the signal [`Solid::Battery::chargeStateChanged`](https://api.kde.org/frameworks/solid/html/classSolid_1_1Battery.html#acf7bf64c35c14a4154399bbb7477e034). So, there may be a problem in `solid` that shows up with some laptops/batteries. If that's the case, we'll have to wait for a fix in KDE.

I searched the Internet quickly and found pages like these: https://bbs.archlinux.org/viewtopic.php?id=235408, https://forum.manjaro.org/t/battery-indicator-in-kde-shows-faulty-values/107060. A thorougher search might result in a KDE bug report. If you find it, please add a link.

**Comment by mokraemer** [comment] 2020-02-17 18:56
As you can see by attached screenshot the info dialog shows different info than the output of acpi.
Batinfo worked well on lxde, which I was using for years.
My laptop already died a few times because of an empty battery.
![batinfo](https://user-images.githubusercontent.com/2962806/74679786-16b84580-51bf-11ea-8fc2-b5d7438a13d0.jpg)

**Comment by tsujan** [comment] 2020-02-17 19:12
> As you can see by attached screenshot...

You'd already told that the issue happens to you (in https://github.com/lxqt/lxqt/issues/1761#issuecomment-576591183).

> Batinfo worked well on lxde

Please read my comment above. We use `solid` in LXQt; Batinfo doesn't have any relation to it.

**Comment by mokraemer** [comment] 2020-02-17 19:18
what is solid?
I've installed the desktop from the distro, they ship an applet called "LXQt-Energieverwaltung
- Energieverwaltung für die LXQt-Desktop-Umgebung".

**Comment by agaida** [comment] 2020-02-17 19:22
ok, let's see a different opinion - `apt install inxi`
`inxi -Bxxx"

**Comment by tsujan** [comment] 2020-02-17 19:25
> what is solid?

My first comment has a link.

> I've installed the desktop from the distro,

When you have `lxqt-powermanagement`, you have `solid` too.

**Comment by mokraemer** [comment] 2020-02-17 19:26
Battery:   ID-1: BAT0 charge: 40.2 Wh condition: 88.2/93.6 Wh (94%) volts: 12.0/11.1 model: LGC 45N1011 type: Li-ion 
           serial: 46177 status: Charging 

State and capacity matches the output of acpi

**Comment by agaida** [comment] 2020-02-17 19:30
so i had to search one of my machines whith the borked hardware i could find and make a direct comparisation - if it is not helpful, i will take the next one :smile:

**Comment by tsujan** [comment] 2020-02-17 19:31
@mokraemer 
It'll be much more informative if you add the `solid` version you have. Here, it's 5.67.0. (`solid` is called `libkf5solid5` in Debian based distros).

**Comment by mokraemer** [comment] 2020-02-17 19:34
sure, current used version is
lib64kf5solid5-5.57.0-1.mga7.x86_64
solid-5.57.0-1.mga7.x86_64

**Comment by tsujan** [comment] 2020-02-17 19:38
> lib64kf5solid5-5.57.0-1.mga7.x86_64

Good. We may need to wait until `solid` is upgraded to ≥ 5.67.0 on your system. 5.57.0 is too old.

**Comment by tsujan** [comment] 2020-02-17 19:52
> so i had to search one of my machines whith the borked hardware

@agaida It will help if you have an up-to-date version of solid. I checked Debian sid; it's solid version is 5.62.0 -- better than 5.57.0 but still I can be sure only of 5.67.0, which I have here.

**Comment by agaida** [comment] 2020-02-17 20:00
that's what arch linux is for

**Comment by tsujan** [comment] 2021-03-06 15:34
`solid` is 5.79.0 now. Not a single instance of an invalid info and no update by reporters regarding their installed `solid` versions. Closing...

**Closed by tsujan** 2021-03-06 15:34 UTC
