### ISSUE TITLE
inconsistency  between file associations saved by PCManFM-Qt and lxqt-config-file-associations

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#652] opened 2015-05-24 20:47 UTC
It seems that selecting a file and  clicking "properties" in pcmanfm-qt and changing "open with" writes (and reads...) to ~/.config/mimeapps.list while File Associations configuration writes to ~/.local/share/applications/mimeapps.list (as dolphin > properties > "open with" and KDE systemsettings too), creating two different ways of handling files.

**Comment by Vladimir-csp** [comment] 2015-05-25 02:56
pcmanfm-qt follows latest mime applications spec http://standards.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.1.html

**Comment by stefonarch** [comment] 2015-05-25 06:34
The problem is that choosing an application let's say for opening *.jpg in LXQt-configuration "File Associations" has no effect in pcmanfm.

**Comment by pmattern** [comment] 2015-05-25 15:31
Confirmed.
Problem could be due to the fact that PCManFM-Qt is using `gvfs-mime` as backend and lxqt-config-file-associations `xdg-mime` as these behave accordingly (why?!).
Actually it could very well be merged into #433. But there's a bunch of related issues all of which should actually get merged into a single new one covering that topic as a whole, IMHO.
So for now I'd suggest to modify this one's header into something more specific expressing there's an inconsistency regarding the way file associations are saved by PCManFM-Qt and lxqt-config-file-associations.

**Comment by Vladimir-csp** [comment] 2015-05-25 17:15
xdg utils are outdated. Upstream is reluctant to update them up to spec and suggests using desktop-specific tools (which xdg-open uses as backend if it knows about, if it does not, it falls back to xdg-mime which is also outdated).

**Comment by pmattern** [comment] 2015-05-25 17:28
@Vladimir-csp 
Any source referring your statements ("outdated", "reluctant", "suggests using desktop-specific tools")?

**Comment by Vladimir-csp** [comment] 2015-05-25 17:41
https://bugs.freedesktop.org/show_bug.cgi?id=56352 It is all in there.

**Comment by pmattern** [comment] 2015-05-25 17:48
@Vladimir-csp 
All right. How about merging that link to your second-to-last comment and deleting all comments following? It seemed reasonable to me to have a source proving those claims, but no need to clutter this issue.

**Comment by PCMan** [comment] 2015-07-13 08:14
The new spec now uses ~/.config/mimeapps.list file to store file association while older implementations still use ~/.local/applications/default.list. If it's not possible to update xdg-open, we still have a way to workaround this. Just export $BROWSER=gvfs-open or something similar. When xdg-open cannot figure out a proper app to open the URL, it reads the BROWSER environment variable. This simple hack can partially solve the problem without fixing xdg-open.

**Comment by Vladimir-csp** [comment] 2015-07-13 08:22
1. $BROWSER is not intended to do that
2. this does not fix the situation when xdg-open does figure out the app, but wrong. (~/.local/applications/mimeapps.list is still in the spec, but with lower priority)

**Comment by PCMan** [comment] 2015-07-13 08:32
You can never fix xdg-open reliably since some proprietary programs, such as Chrome AFAIK, bring their own versions of xdg-utils. So BROWSER is a possible and reasonable "workaround".
Unfortunately, to make things work for out-dated programs, we have to write the same configuration to several different places with different formats, which is not a trivial task.

**Comment by tsujan** [comment] 2020-07-21 19:07
Not a problem anymore. Default apps are read by GLib from `~/.config/lxqt-mimeapps.list` and `~/.config/mimeapps.list`. They're written to the former, which takes priority and is specific to LXQt (in other DEs, the're written to [DE]-mimeapps.list). GLib is used by both pcmanfm-qt and libqtxdg (which is used by "File Associations").

**Closed by tsujan** 2020-07-21 19:07 UTC
Labels: lxqt-config, pcmanfm-qt
