### ISSUE TITLE
From Application Menu Search Results, Allow Dragging Icons to Quick Launch and Right-Clicking

### ISSUE THREAD

**Issue by poikilos** [lxqt/lxqt#1698] opened 2019-03-31 20:28 UTC
I don't know whether this issue exists in the latest version, but I suspect this may still be an issue since it is inconspicuous, not in the issue tracker (open or closed), and since Fedora 29 keeps pace with packages but I can try a git version at some point.

##### Expected Behavior
Application Menu search results could be dragged to Quick Launch, or right-clicked.

##### Current Behavior
Application Menu search results can neither be dragged nor right-clicked.
The operations can only be done by manually looking through the menu (while not in search mode).

##### Context
This is frustrating for first-time setup especially, since the application categories may not be known. I switched from KDE to LXQt (again, I tried it a few times before) today.

##### System Information

* Distribution & Version: Fedora 29
* Kernel: N/A
* Qt Version: 5.11.3 64-bit
* liblxqt Version: 0.13.0
* Package version: LXQt 0.13.0

**Comment by tsujan** [comment] 2019-03-31 20:41
Duplicate of https://github.com/lxqt/lxqt/issues/1626

**Comment by tsujan** [comment] 2019-03-31 20:42
BTW, LXQt 0.13 is old.

**Closed by tsujan** 2019-03-31 20:41 UTC

**Comment by stefonarch** [comment] 2019-04-01 06:57
> Context
This is frustrating for first-time setup especially, since the application categories may not be known. I switched from KDE to LXQt (again, I tried it a few times before) today.

Not sure in 0.13 but you can configure the menu search to show categories too (filter categories) and out of the categories  you can drag drop the items.
