### ISSUE TITLE
lxqt-config-brightness asking for sudo password in order to run

### ISSUE THREAD

**Issue by Fallast** [lxqt/lxqt#2213] opened 2022-03-14 18:29 UTC
each time i try to change the brightness using the corresponding keys i get an authentication dialog:
![image](https://user-images.githubusercontent.com/61057195/158237175-52ff1a98-b275-462e-a117-9112fc9e0ddd.png)
if i were to run lxqt-config-brightness -d/i on the terminal i also get the same dialog
as a workaround to this issue i remapped the brightness keybindings to use xbacklight to change the brightness amount

- LXQT version: 1.0.0
- System: Void Linux

**Comment by tsujan** [comment] 2022-03-14 18:39
Duplicate of https://github.com/lxqt/lxqt-config/issues/696

**Closed by tsujan** 2022-03-14 18:39 UTC
