### ISSUE TITLE
LXQt Appearance should be able to set GTK settings

### ISSUE THREAD

**Issue by intialonso** [lxqt/lxqt#403] opened 2014-12-04 00:33 UTC
I think that lxqt-config-appearance should be able to set the gtk theme (and icons and fonts). 
Right now the user needs to install LXAppearance (or other tools) to be able to change the gtk apps look.

**Comment by jleclanche** [comment] 2015-01-03 08:26
We need to deal with this in some way for 1.0

**Comment by PCMan** [comment] 2015-01-03 11:04
Please assign this to me since I know gtk and Qt.

**Comment by Vladimir-csp** [comment] 2015-04-01 05:43
Maybe hook xsettingsd in? It is lightweight, has miniscule dependencies, needs only config file and SIGHUP. No need to code xsettings stuff into lxqt-config-appearance.

**Comment by jleclanche** [comment] 2015-04-01 15:49
-1

**Comment by Vladimir-csp** [comment] 2016-08-25 14:03
I've been digging font configuration stuff lately. There is some indication that GTK2 applications ignore xft settings in their gtkrc since some unidentified time. I can confirm this in current Debian testing.

That is the reason for submitting #1129. And also this is a thing to keep in mind when integrating GTK theming support into lxqt-config-appearance: the following gtkrc options have no effect on gtk2 applications:
``` 
 "gtk-xft-antialias"        gint                  : Read / Write
  "gtk-xft-dpi"              gint                  : Read / Write
  "gtk-xft-hinting"          gint                  : Read / Write
  "gtk-xft-hintstyle"        gchararray            : Read / Write
  "gtk-xft-rgba"             gchararray            : Read / Write
```

https://forums.bunsenlabs.org/viewtopic.php?id=1246
https://www.linux.org.ru/forum/general/2663307

**Comment by simoniz0r** [comment] 2018-06-18 04:42
Has there been any more progress on something like this?  

IMO, the metapackages/groups/whatever for LXQt should be including lxappearance until LXQt has some sort of replacement.  Not having any way to do GTK settings out of the box is a pretty big turn off for a lot of people.

**Comment by agaida** [comment] 2018-06-18 15:24
@simoniz0r - you know that we are upstream? Packaging is downstream.

**Comment by simoniz0r** [comment] 2018-06-18 16:30
A lot of your team members take part in the packaging for various distros.

**Comment by agaida** [comment] 2018-06-18 17:05
just make a test - install xfwm4 - use it as WM, change some things with lxappearance - after xfwm4 is crashed think again if lxappearance is really a good idea ...

**Comment by agaida** [comment] 2018-07-30 08:20
gtk_appearance branch merged

**Closed by agaida** 2018-07-30 08:20 UTC
Labels: high-priority, lxqt-config
