### ISSUE TITLE
Wallpaper preview (Desktop Preferences)

### ISSUE THREAD

**Issue by intialonso** [lxqt/lxqt#391] opened 2014-11-23 16:23 UTC
It will be nice to have a wallpaper preview In the desktop preferences dialog.

**Comment by pranavg189** [comment] 2015-01-04 18:05
Does this mean that we have to show the wallpaper preview inside the desktop preferences dialog or on the desktop?.....I may be able to work on it......

**Comment by intialonso** [comment] 2015-01-04 19:06
@pranavg189 in the dialog.

**Comment by jleclanche** [comment] 2015-01-04 19:10
Well, we definitely need image preview in the file picker - that is just a flag we're not setting in the call.

In the desktop preferences dialog itself, I think we need to move wallpaper config to a tab of its own, and have a "gallery" view of wallpapers of sorts.

**Comment by jleclanche** [comment] 2015-01-04 19:12
Fixing the filepicker call before 0.9 would be nice. @PCMan can you take a quick look?

**Comment by pranavg189** [comment] 2015-01-04 21:02
Hmmm....A new tab for Wallpaper config sounds like a good idea.....Any suggestions on how to get started on this....

**Comment by jleclanche** [comment] 2015-01-04 22:03
Well a UI mockup would be the best thing to start with.

If you look at the Windows 7 wallpaper config, it's fairly close to what I have in mind:

![image](https://cloud.githubusercontent.com/assets/235410/5607696/8af46162-9465-11e4-9ccc-b281d97c2c89.png)

The image picker dialog is pretty much what I was thinking. It would display the contents of the wallpaper directory, and users would be able to add more images (with a big + icon or drag & dropping image files into it) which would *copy* them to the wallpaper directory. Users would be able to click a wallpaper to set it, it would apply immediately (and revert on cancel). Below, we would have picture repeat settings.

**Comment by pranavg189** [comment] 2015-01-04 22:45
Hmmm....will get started on the implementation.....One question I had in mind....to make a pull request which repo should I clone......just the pcmanfm-qt (which is related to this issue) or the full lxqt.....  :)

**Comment by jleclanche** [comment] 2015-01-05 00:54
Just the pcmanfm-qt repo.

**Comment by PCMan** [comment] 2015-01-05 10:17
Better to make this an dynamic module, so it can be integrated with both
pcmanfm-qt and lxqt-config-appearance.
Alternatively, let pcmanfm-qt make this part a module, and let
lxqt-config-appearance load it (optionally).
Making things more integrated is good for UX.

**Comment by jleclanche** [comment] 2015-01-05 10:28
That would be nice yes, but out of scope for this issue. Feel free to file a new one.

**Comment by paulolieuthier** [comment] 2015-08-24 18:12
An "Apply" button would mitigate it.

**Comment by alfredobonino** [comment] 2015-08-29 14:56
A preview of this??? There is The code of wallpaper preview??

**Comment by intialonso** [comment] 2015-11-21 16:42
@PCMan I think the this is not the same issue than lxde/pcmanfm-qt#236

I think this is still a valid issue.

**Comment by alfredobonino** [comment] 2015-11-21 17:46
I think.this is a importante feauture for a user friendly desktop environment @PCMan, @intialonso, @paulolieuthier

**Comment by paulolieuthier** [comment] 2015-11-23 11:05
@intialonso please reopen it and elaborate more.

**Comment by intialonso** [comment] 2015-11-23 13:32
#236 just added an "apply" button for the desktop preferences dialog.

This issue is about having wallpaper previews within the dialog as many DE already do:

! [XFCE](http://4.bp.blogspot.com/-9Mic1rQQc6g/VPR-q2QzRsI/AAAAAAAAVpY/UG9Bx-YTdYI/s1600/xfce412-desktop-background.png)
! [KDE](http://ocsmag.com/wp-content/uploads/2014/05/plasma-next-desktop-settings.png)
! [Unity](http://i.stack.imgur.com/WOLgl.png)
! [Unity](http://1.bp.blogspot.com/-cahWDRTtQnc/Vcw6VLQyz4I/AAAAAAAAEJ8/aKLyXoeycrQ/s1600/Screenshot%2Bfrom%2B2015-08-13%2B03%253A34%253A57.png)

I guess this will requiere the posibility to load a specific folder as the Images home folder, the /usr/share/backgrounds or a user chosen one.

**Comment by pmattern** [comment] 2015-12-04 17:04
A somewhat related feature I'd love to see is setting background images from image viewers, namely Phototonic.

This doesn't seem to be something too common, though. In fact the only application I'm aware of providing something similar is Gwenview which allows for dragging & dropping images to the desktop and setting them as background image from a context menu coming up then.

Yet I wonder whether this would eventually be feasible in LXQt / Phototonic and whether there's some kind of ABI or description of proceeding that could eventually be handed to the Phototonic developer (simply writing the path to `~/.config/pcmanfm-qt/lxqt/settings.conf` doesn't seem to do the trick).

**Comment by Vladimir-csp** [comment] 2015-12-04 18:29
IMHO, the best way to implement "Set as LXQT wallpaper image" feature is to add a CLI option to pcmanfm and provide a desktop entry associated with images using this command. It would be universal. Image viewers that have "Open in" feature would gain the ability to set wallpaper automatically. Viewers which have "external command" feature could be configured to use this feature. Any XDG-compatible file manager could be used to set wallpapers.

**Comment by alfredobonino** [comment] 2015-12-04 18:32
Mah, all desktop environment and windows/mac supporto this feauture.
We are in the 2015/2016 and lxqt is a user friendly desktop environment.
This feauture is very important

**Comment by intialonso** [comment] 2015-12-04 20:06
@Vladimir-csp the Manjaro LXQT spin already include a custom action for that:

https://wiki.manjaro.org/index.php?title=Custom_Actions_for_PCmanFM-Qt

```
[Desktop Entry]
Type=Action
Name[en]=Set As Wallpaper
Icon=user-desktop
Profiles=profile-zero;

[X-Action-Profile profile-zero]
MimeTypes=image/*;
Exec=pcmanfm-qt -w %f
Name[en]=Default profile
SelectionCount==1
```

**Comment by stefonarch** [comment] 2016-09-05 16:52
I see this is still open, it's quite annoying changing themes and they change the wallpaper too.
One thing we could think about IMHO is adding by default this custom action in ~/.local/share/file-manager/actions/wallpaper.desktop
        
> [Desktop Entry]
> Type=Action
> Name=Set as wallpaper
> Icon=user-desktop
> Profiles=profile-zero;
> 
> [X-Action-Profile profile-zero]
> MimeTypes=image/*;
> Exec=pcmanfm-qt -w %f
> Name=Default profile
> [Desktop Entry]
> Type=Action
> Name[it]=Usa come sfondo
> Name[de]=...
> Icon=user-desktop
> Profiles=profile-zero;
> 
> [X-Action-Profile profile-zero]
> MimeTypes=image/*;
> Exec=pcmanfm-qt -w %f
> Name=Default profile

**Comment by rogersanctus** [comment] 2019-04-23 21:07
Its 2019 and only now I knew lxqt and I am loving it. But to have a user friendly background settings with preview as people stated before is still a big deal. I hope people is working on that.

**Comment by tsujan** [comment] 2019-04-23 21:18
This report is from 2014, when libfm-qt wasn't rich enough.

Now, we have our own file dialog that shows thumbnails of images (they can be made big by selecting the thumbnail view). So, it's enough to add a small code to open the file dialog inside the folder where the last images was opened. More than that is a duplication, IMO.

**Comment by rogersanctus** [comment] 2019-04-23 21:31
![sc_wallpaper_selector](https://user-images.githubusercontent.com/1813125/56617242-c8193980-65f5-11e9-8ded-393103816714.png)
Well, here it is not showing any thumbnails. May be I have to set anything else. If so its not user friendly.

**Comment by tsujan** [comment] 2019-04-23 21:36
Then something more important is missing in your system:

![thumbnail](https://user-images.githubusercontent.com/981076/56617577-801a0700-6635-11e9-8b77-b1b4017f0a40.png)

**Comment by rogersanctus** [comment] 2019-04-23 21:47
Yes pretty much. I was using lxqt on Ubuntu 18.10 and now had upgrade to 19.04. May be some distro related setting.

**Comment by tsujan** [comment] 2019-04-23 21:51
If you have libfm-qt 0.14, then you have LXQt file dialog but your screenshot shows that it isn't used (it should be used with a standard LXQt installation). Your EVs are incorrect for some reason. Maybe, an LXQt package isn't upgraded or has a bad built.

**Comment by tsujan** [comment] 2019-04-23 21:52
Anyhow, automatically opening the folder containing the selected image should still be implemented; will do it soon.

**Comment by wxl** [comment] 2019-04-23 22:00
That seems weird, but certainly the case in Lubuntu 19.04.
Interestingly, generating thumbnails works fine in `pcmanfm-qt`, just
not in the open dialog for the wallpapers. I tried with `kwin` and same
problem, so yeah, it seems to be a distro issue, but I'm not sure
exactly where.

**Comment by tsujan** [comment] 2019-04-23 22:03
@wxl As I said, that's NOT the LXQt file dialog (in @rogersanctus's screenshot). If that's the case in Lubuntu 19.04, there's a serious problem there (not in LXQt).

**Comment by tsujan** [comment] 2019-04-23 22:06
FYI

This Qt file dialog (poor):

![qt](https://user-images.githubusercontent.com/981076/56619100-b6598580-6639-11e9-8fb7-e72d87ae6451.png)

And this LXQt file dialog (rich):

![lxqt](https://user-images.githubusercontent.com/981076/56619118-c3767480-6639-11e9-957d-ea59a0be86bc.png)

**Comment by wxl** [comment] 2019-04-23 22:09
Unless we have the wrong libfm-qt, right? And we do have
0.14.1-0ubuntu2, so that should be good, unless those two patches are
somehow problematic. What about the core libfm libraries? I can't
imagine those are the issue, especially as we're consistent with Debian
(1.3.1-1).

cc: @tsimonq2

**Comment by tsujan** [comment] 2019-04-23 22:14
> Unless we have the wrong libfm-qt, right?

Not necessarily. You may also have wrong platform integration or something else. Sorry, I don't have time to install Lubuntu on VirtualBox.

**Comment by tsujan** [comment] 2019-04-23 22:21
deb packages that should be checked:

libqtxdg
liblxqt
libfm-qt
lxqt-qtplugin
lxqt-config
lxqt-globalkeys
lxqt-session

**Comment by wxl** [comment] 2019-04-23 22:28
> libqtxdg

libqt5xdg3 3.3.1-0ubuntu2

> liblxqt

liblxqt0 0.14.1-0ubuntu1

> libfm-qt

libfm-qt6 0.14.1-0ubuntu2

> lxqt-qtplugin

lxqt-qtplugin 0.14.0-0ubuntu3

> lxqt-config

lxqt-config 0.14.1-0ubuntu1

> lxqt-globalkeys

lxqt-globalkeys 0.14.1-0ubuntu1
liblxqt-globalkeys0 0.14.1-0ubuntu1

> lxqt-session 

lxqt-session 0.14.1-0ubuntu1

**Comment by tsujan** [comment] 2019-04-23 22:33
If Lubuntu is consistent with Debian, it should happen on Debian too. @agaida could tell that; I don't have Debian either.

**Comment by wxl** [comment] 2019-04-23 23:52
Debian testing seems to suffer the same fate. It was suggested it may be
the QPA, but:

```
QT_QPA_PLATFORMTHEME=lxqt
QT_PLATFORM_PLUGIN=lxqt
```

**Comment by tsujan** [comment] 2019-04-23 23:59
I can't say anything other than that the problem isn't in LXQt. With each release, I upgrade to it and, after that, I upgrade to the latest git sources once every 1 or 2 weeks (at least). Have never seen a broken LXQt dialog -- it would be a serious issue, otherwise.

@agaida will tell about Debian.

**Comment by agaida** [comment] 2019-04-24 00:56
What should i say - works as expected - but Lubuntu is sometimes a bit sparse with recommends. Will test tomorrow a Buster live iso. Shouldn't be that hard to find the missed package, when a team has an Debian Developer - i'm only a simple Debian Maintainer :sunglasses:

**Comment by agaida** [comment] 2019-04-24 01:09
![](https://i.imgur.com/P5tTHsl.png)

The only thing about this installation is that i installed the needed packages for a local rebuild of libfm-qt before uploading the fixed version to unstable (0.14.1-6) - will test a clean debian live iso tomorrow.

**Comment by agaida** [comment] 2019-04-24 01:19
> Anyhow, automatically opening the folder containing the selected image should still be implemented; will do it soon.

Cool, just stumbled into it again too - was about to file a bug :D

**Comment by wxl** [comment] 2019-04-24 01:21
@agaida LXDE-era Lubuntu light on recommends, but it's not the case with
LXQt. 

My results in Debian testing were problematic. So something is weird.
What are your environmental variables, or at least the relevant ones?

**Comment by agaida** [comment] 2019-04-24 01:32
glad to hear about the recommends - i changed nothing, just downloaded the mondays image, started it, installed with calamares and was done with.  
After that only the usual apt update, apt install devscripts debhelpers; mkdir libfm-qt; cd libfm-qt; apt source libfm-qt
applied the patches i wanted to upload and compiled/installed  it with

debuild; apt install ,,/*deb

that's all

**Comment by agaida** [comment] 2019-04-24 02:15
So we running into a problem - a local rebuild of libfm-qt fixes this - no clue what happend.
Next test is a rebuild in a pbuilder environment. But not now :)

**Comment by tsujan** [comment] 2019-04-24 12:04
> Cool, just stumbled into it again too - was about to file a bug :D

Done in https://github.com/lxqt/pcmanfm-qt/pull/950

**Comment by tsujan** [comment] 2019-04-24 12:12
> it looks indeed strange, the Qt dialog is shown

One of many causes can be that `lxqt-qtplugin` was compiled before installing the new `libfm-qt`. The correct order is:
```
libqtxdg
lxqt-build-tools
liblxqt
libfm-qt
...
lxqt-qtplugin
```

**Comment by agaida** [comment] 2019-04-24 12:58
ok - i don't touch lxqt-qtplugin when i rebuild libfm-qt - after that rebuild it worked fine. If i remember correctly lxqt-qtplugin don't build depend on libfm-qt, it's only a run time thing. If not we have a problem since th 0.14.0 release iirc.

**Comment by tsujan** [comment] 2019-04-24 13:28
@agaida You're right. In older version, it depended on  libfm-qt but not anymore. From `lxqtplatformtheme.cpp`:
```c++
            QLibrary libfmQtLibrary{QLatin1String("libfm-qt")};
            libfmQtLibrary.load();
            if(!libfmQtLibrary.isLoaded()) {
                return nullptr;
            }
```
So, libfm-qt isn't loaded on Ubuntu for some reason related to package builds.

**Comment by agaida** [comment] 2019-04-24 16:02
erm - i make a new build - and after my test **really** should talk about :smile:

Guess i found the reason and you will not like it. Really. It was one of thes moments when i don't know if i want to swear or roflmao :)

**Comment by tsujan** [comment] 2019-04-24 16:07
> Guess i found the reason and you will not like it.

If you mean me, I like every truth in the realm of coding but not human beings ;)

**Comment by agaida** [comment] 2019-04-24 16:08
hihihi :D

**Comment by agaida** [comment] 2019-04-24 16:10
Do you have remote-viewer installed? if not, could you please install?

**Comment by tsujan** [comment] 2019-04-24 16:22
Sorry for my ignorance but, except for TeamViewer that I hate and never install, I don't know of any remote viewer.

Try words ;)

**Comment by agaida** [comment] 2019-04-24 16:30
Trust me, it doesn't hurt
```
pacman -S virt-viewer
remote-viewer spice://dev.siuction.org:6766
```

**Comment by tsujan** [comment] 2019-04-24 16:34
Will do it if it's so easy :) Learned something new.

**Comment by rogersanctus** [comment] 2019-04-24 16:43
Well, thanks to you guys, got libfm-qt sources and debuild, sudo debi and restarted session. Now its working as expected.

![image](https://user-images.githubusercontent.com/1813125/56677392-d53a3500-6696-11e9-8ff8-22964ac792cf.png)

Lubuntu 19.04 (disco)

**Comment by agaida** [comment] 2019-04-24 16:52
the solution is far more easy - but not the solution we like for distributions like debian and derivatives

* one can test it fast - start lubuntu live, try to open a file - the Qt dialog will appear
* open a terminal
```
apt update
apt install libfm-qt-dev
```
try again (it will depend on your mood if you laugh, cry or swear now - all understandable)

**Comment by agaida** [comment] 2019-04-24 16:56
And thats the reason why we don't noticed it yet  - arch and other distributions don't split out the dev files. And even on debian and derivatives  it is highly likely that the dev packages are installed on developer machines, not directly after a clean installation but latest half an hour later.

**Comment by tsujan** [comment] 2019-04-24 17:00
@agaida That was a brilliant discovery of yours. Let's search for its cause.

**Comment by agaida** [comment] 2019-04-24 17:03
first i have to start the live system again - i suspect another thing

**Comment by tsujan** [comment] 2019-04-24 17:04
@agaida On the remote-viewer, you suspected `QLibrary`. I do so too. We're sure that it didn't need headers before; aren't we?

**Comment by agaida** [comment] 2019-04-24 17:05
far more absurd - just started, you can connect

**Comment by tsujan** [comment] 2019-04-24 17:25
Good news: @agaida fixed the problem.

**Comment by agaida** [comment] 2019-04-24 17:35
```
            QLibrary libfmQtLibrary{QLatin1String("libfm-qt")};
            libfmQtLibrary.load();
```
does something wrong - it will load libfm-qt.so (the dev symlink) instead the versioned link libfm-qt.so.6 which itself point to the real file libfm-qt.so.6.1.0. Loading via libfm-qt.so.6 would be right as it consider soname bumps, only the right™ lib would be loaded.

**Comment by tsujan** [comment] 2019-04-24 17:58
OK. The question remains: Should you do it in deb packages or can it be done in the cmake file (if possible)?

**Comment by tsujan** [comment] 2019-04-24 18:02
@rogersanctus It seems you're familiar with packaging. If so, I suggest you use the latest git LXQt sources -- they're always better than latest releases.

**Comment by agaida** [comment] 2019-04-24 18:09
had to do a short test and build a new lxqt-qtplugin (and ofcourse a new live iso) - should be easy to fix. And yes, it must be done in cmake.

**Comment by agaida** [comment] 2019-04-24 18:30
```https://i.imgur.com/a8xbgPc.png```

ok, in quick and really dirty
```
--- lxqt-qtplugin-0.14.0.orig/src/lxqtplatformtheme.cpp
+++ lxqt-qtplugin-0.14.0/src/lxqtplatformtheme.cpp
@@ -239,7 +239,7 @@ QPlatformDialogHelper *LXQtPlatformTheme
         // The createFileDialogHelper() method is dynamically loaded from libfm-qt on demand
         if(createFileDialogHelper == nullptr) {
             // try to dynamically load libfm-qt.so
-            QLibrary libfmQtLibrary{QLatin1String("libfm-qt")};
+            QLibrary libfmQtLibrary{QLatin1String("libfm-qt.so.6")};
             libfmQtLibrary.load();
             if(!libfmQtLibrary.isLoaded()) {
                 return nullptr;
```
don't know if *bsd name the libs the same way, but i guess they do - the `.6` must be replaced by a proper variable that is set in CMakeLists.txt

**Comment by tsujan** [comment] 2019-04-24 18:41
> the .6 must be replaced by a proper variable that is set in CMakeLists.txt

That's troublesome. Let's call @palinek and @luis-pereira ... Where are you? ;)

**Comment by tsujan** [comment] 2019-04-24 18:43
[Qt doc](https://doc.qt.io/qt-5/qlibrary.html#QLibrary-1) says:
```
We recommend omitting the file's suffix in fileName, since QLibrary will automatically look for the file with the appropriate suffix in accordance with the platform, e.g. ".so" on Unix, ".dylib" on macOS and iOS, and ".dll" on Windows.
```

**Comment by agaida** [comment] 2019-04-24 18:45
`.so` was the neckbreaker for us - it contradicts the whole versioning thing - so maybe a switch for macOS is needed - we can leave alone Windows for now.

**Comment by tsujan** [comment] 2019-04-24 18:47
But why it wasn't a problem before? Qt doc says nothing about a change. Or, maybe, this problem was there since that code was written and we just didn't know about it.

**Comment by agaida** [comment] 2019-04-24 18:51
again - the problem will not be visible on arch an other distributions with a similar packaging strategy :)

and for debian and derivatives: Shit happend - the .so file was installed with the first thing that build depend on libfm-qt-dev :smile: 

The problem is far deeper - you have seen the live image - as long the look was ok (aka, background right set etc) there was only a very few times when i tested opening files in a fresh or live system - i guess mostly after testing some patches (and that means compiling and that means in the very most cases libm-qt-dev installed the last time)

**Comment by tsujan** [comment] 2019-04-24 19:04
OpenSUSE and other distros with devel packages should see the same issue. I downloaded OpenSUSE's `src.rpm` for libfm-qt and this was in its spec:
```
%files -n libfm-qt6
...
%{_libdir}/libfm-qt.so.*
...

%files -n libfm-qt-devel
...
%{_libdir}/libfm-qt.so
...
```
So, either Qt supposes that Linux should be like Arch -- I'm not unhappy about that for obvious reasons ;) -- which means we should do as you said, or we are missing something here.

**Comment by tsujan** [comment] 2019-04-24 19:06
All in all, our conscience is clear, I think ;)

**Comment by tsujan** [comment] 2019-04-24 19:13
Don't shout at me:

What about making the deb/rpm/.. package of `lxqt-qtplugin` dependent on libfm-qt-dev (or whatever its name is in a distro with dev packages)?

**Comment by agaida** [comment] 2019-04-24 19:18
that would mean: dev packages in a production system with no reason - not a good idea

**Comment by tsujan** [comment] 2019-04-24 19:28
OK. So far, it seems the only solution is what you proposed -- unless @palinek or @luis-pereira knows something we've missed.

**Comment by agaida** [comment] 2019-04-24 19:34
We have a nice little problem here - we know which version we expect, but we can't set a minimum version. We could do a bit magic like try to load a package at build time and extract the so-version for further use. Thats what senior programmers would likely do. Mere humans would just set the expetec so-version and absolute beginners would do a hack like me :D

**Comment by agaida** [comment] 2019-04-24 19:36
See also: https://www.smart-jokes.org/programmer-evolution.html

**Comment by tsujan** [comment] 2019-04-24 19:41
As someone that hasn't used `QLibrary` in his programs, I think there may be a solution in it but I can't test because I have Manajro and have forgotten many things about Debian ;)

**Comment by agaida** [comment] 2019-04-24 19:50
we depend on certain minimums - for the time being it is 6.x as so-version for libfm-qt. For me it is perfectly fine to hard wire th `.6` for stable - it will never ever change. And it is not to much work to change it to `.7` if we bump so-name to the 7.x series. Maybe @luis-pereira or @palinek come up with a easy solution that we don't have to touch in the future. But as downstream patch for a stable versio it is legit i guess.

**Comment by tsujan** [comment] 2019-04-24 20:02
Fortunately, the worst effect this has is that some users think that our file dialog is as elementary as they see ;)

**Comment by tsujan** [comment] 2019-04-24 21:10
@agaida The only way I found was polishing your solution a little:
```c++
QLibrary libfmQtLibrary{QLatin1String("libfm-qt"), 6};
```
We'll have to change the number 6 with every release, which seems reasonable to me. `QLibrary::LoadHints` were irrelevant as far as I tested.

Please make a PR!

**Comment by agaida** [comment] 2019-04-24 21:27
``` diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d584a40..3d1c98d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -16,6 +16,11 @@ set(CMAKE_POSITION_INDEPENDENT_CODE ON)
 set(LXQTBT_MINIMUM_VERSION "0.6.0")
 set(QT_MINIMUM_VERSION "5.7.1")
 set(QTXDG_MINIMUM_VERSION "3.3.0")
+set(FMQT_SO_VERSION "6")
+
+add_definitions(
+    -DFMQT_SO_VERSION=\"${FMQT_SO_VERSION}\"
+)
 
 find_package(Qt5DBus ${QT_MINIMUM_VERSION} REQUIRED)
 find_package(Qt5LinguistTools ${QT_MINIMUM_VERSION} REQUIRED)
diff --git a/src/lxqtplatformtheme.cpp b/src/lxqtplatformtheme.cpp
index 6405b7d..8de1091 100644
--- a/src/lxqtplatformtheme.cpp
+++ b/src/lxqtplatformtheme.cpp
@@ -239,7 +239,7 @@ QPlatformDialogHelper *LXQtPlatformTheme::createPlatformDialogHelper(DialogType
         // The createFileDialogHelper() method is dynamically loaded from libfm-qt on demand
         if(createFileDialogHelper == nullptr) {
             // try to dynamically load libfm-qt.so
-            QLibrary libfmQtLibrary{QLatin1String("libfm-qt")};
+            QLibrary libfmQtLibrary{QLatin1String("libfm-qt"), FMQT_SO_VERSION};
             libfmQtLibrary.load();
             if(!libfmQtLibrary.isLoaded()) {
                 return nullptr;
```
@palinek @luis-pereira  - what do you think

**Comment by wxl** [comment] 2019-04-24 21:31
> +set(FMQT_SO_VERSION "6")

@agaida I can't speak for all the other platforms, but that seems to
make a lot of logical sense to me.

**Comment by tsujan** [comment] 2019-04-24 21:32
@agaida Make a PR! We won't find a better solution.

**Comment by agaida** [comment] 2019-04-24 21:38
@tsujan - i prefer building a package and a iso first - if it works - fine, i will make a PR

**Comment by tsujan** [comment] 2019-04-24 21:39
Do your tests but I tested 6 on Manjaro and it worked fine (I'd moved `/usr/lib/libfm-qt.so`, of course).

**Comment by tsujan** [comment] 2019-04-25 00:49
OK, since this was about showing wallpaper previews and LXQt file dialog already does that, especially after https://github.com/lxqt/pcmanfm-qt/pull/950, and because LXQt file dialog will be used also on all systems with dev/devel packages after https://github.com/lxqt/lxqt-qtplugin/pull/47, I think this can be closed.

**Closed** 2019-05-05 23:17 UTC
Labels: idea/discussion, pcmanfm-qt
