### ISSUE TITLE
LXQt windows don't maximize to use whole display (full width but minimal height on lower display)

### ISSUE THREAD

**Issue by guiverc** [lxqt/lxqt#1704] opened 2019-04-11 10:08 UTC
Two displays of 1920x1080, when vertically aligned (one above the other) windows will not maximize on lower display.  Windows go full width, but use 1/8 to 1/6th of vertical of the screen and cannot be dragged down to use the whole display.  You need to unmaximize and drag window manually both vertically & horizontally.

##### Expected Behavior

Windows should maximize on both displays regardless of how aligned.  As installed it had two displays aligned horizontally (ie. a left & right).  I used Monitor.Settings to make the right display be below the other (originally-left) display. The consequence of this Monitor.Settings change was you cannot use maximize on the now-lower display.

##### Current Behavior

Picture can be seen at 
https://bugzilla.opensuse.org/attachment.cgi?id=802601
Note: I do have some horizontal misalignment too, but removing it so that both displays are only one-above-the-other makes no difference (except to screenshots). The Panel is on the bottom of top-display, firefox in the picture is maximized on the bottom display meaning you can only title bar, menu (file-edit-view..), tabs, address bar, title-line Bugzilla-Enter.Bug:opensuse.Tumbleweed  but no useful data from page. 

##### Steps to Reproduce (for bugs)

1. have two displays (mine are 1920x1080), set what starts default-right so it's positioned below the default-left display
2. Open a program (eg. firefox) and click maximize whilst it's on top display, it'll maximize correctly. Click it again to return to smaller window
3. Drag a window (eg. firefox) to the lower display, and click maximize button. It'll use the full width, but use almost no vertical real-estate

##### Context

I'd like maximize buttons to work equally on both displays (like they did before I moved the default-right display to be below the default-left one with Monitor.Settings)

##### System Information

Distribution & Version: opensuse tumbleweed & lubuntu 19.04
Kernel: 5.0.5-1 & 5.0.0-8
Qt Version: 0.14.1 & 0.14.1
liblxqt Version: 0.14.1 & 0.14.1
Package version: liblxqt-devel 0.14.1-1.1 x86_64 & liblxqt0 x86_64 0.14.1-0ubuntu1

**Comment by guiverc** [comment] 2019-04-11 10:11
https://bugzilla.opensuse.org/show_bug.cgi?id=1132180
https://bugs.launchpad.net/ubuntu/+source/lxqt-session/+bug/1809201

**Comment by tsujan** [comment] 2019-04-12 08:14
Not reproducible.

I have 2 1920x1080 screens. When I align them vertically, all windows are maximized correctly on both screens, regardless of Panel's position. I use KWin.

It may be a bug in the WM you use.

**Comment by guiverc** [comment] 2019-04-12 08:59
Please also test swapping your top & bottom screens.

If I swap my 'top' screen in Monitor.Settings so it's on the bottom (the opposite to the way my screens are really setup), the issue does not occur.  My instructions (how it occurs for me) maybe created the opposite position as to what it did for me.  I tested this using Lubuntu 19.04's daily image  (20190411) and it occurs on a hp 8200 & dell d980 (which have same screen layouts)

**Comment by tsujan** [comment] 2019-04-12 09:09
> Please also test swapping your top & bottom screens.

That was the only thing I didn't test. You're right. When I swap the top and bottom screens, the problem reported here is reproducible. Reopening....

**Comment by tsujan** [comment] 2019-04-12 09:11
@palinek Any idea how this is possible?

**Comment by tsujan** [comment] 2019-04-12 11:47
I got curious about this, changed my primary screen and the problem disappeared. Restored the primary screen and, again, couldn't reproduce the problem. Actually, my problem is that, after that simple change and although I reversed it, I can't reproduce the problem anymore; neither swapping nor changing the primary screen makes a difference.

My guess: a default value is wrong; once it's overridden, everything is OK.

**Comment by agaida** [comment] 2019-04-12 16:19
Will have a look

**Comment by tsujan** [comment] 2019-04-12 16:30
> Will have a look

You might not see it, as I don't anymore. I guess, by removing the settings, I could reproduce it again. The fact is that there is a bug somewhere.

**Comment by guiverc** [comment] 2019-10-25 06:32
Just touching base....  the issue still occurs on vertically aligned screens (one way only; if swap top/bottom it doesn't occur) on new systems using the Lubuntu 20.04 late daily. If clues as to how the 'settings' are changed during use of the system are worked out (ie. how to mitigate the issue) I'd really like to know.

kernel 5.3.0-19, LXQt 0.14.1, Qt 5.12.4

**Comment by guiverc** [comment] 2019-11-02 11:15
I upgraded my fedora 30 box today to f31.   this issue impacts fedora
hardware: hp 8200 elite sff (i5-2400, 8gb, nvidia quadro 600)

kernel 5.3.7-301.fc31.x86_64, LXQt 0.14.1, Qt 5.12.5

**Comment by tsujan** [comment] 2019-11-02 12:32
@guiverc 
It seems that I was the only one who could reproduce your reported issues before (only once) but I can't anymore, although I removed my configuration and tested again and again. So, I think something outside LXQt should have caused it -- something that was fixed after an upgrade (a driver, X11, KF5, Qt...?).

Since you still see it, the logical questions are:

 1. Does it happen only with your nvidia quadro 600? Did you also test with on computer *without nvidia*?

 2. Does it happen under KDE too? If I've understood https://github.com/lxqt/lxqt/issues/1703#issuecomment-500111069 correctly, the anser is "yes"; isn't it?

**Comment by guiverc** [comment] 2019-11-02 13:08
(1) 
It occurs with
dell [optiplex] 960 (c2q-q9400, 8gb, amd/ati cedar radeon hd 5000/6000/7350/8350)
hp 8200 elite sff (i5-2400, 8gb, nvidia quadro 600)

Both boxes have ~ same setup (they sit next to each other); different monitors but all are 1920x1080 with top/bottom configuration.

Opensuse [tumbleweed] & Fedora [31] are (dual-boot) on hp 8200, where as Lubuntu (now 20.04) runs on the dell 960.

(2)
I'd forgotten about that comment; and I actually can't recall it occurring in KDE, so I'll retest and comment when I can.

**Comment by tsujan** [comment] 2019-11-02 16:14
I set up vertical dual screens again and, like before, no problem happened.

However, this time I got curious and clicked on your screenshot link (fortunately, it wasn't dead: https://bugzilla.opensuse.org/attachment.cgi?id=802601) and saw a difference: Your panel is at the middle of the dual screen. That never happens here. Actually, it's impossible because `Configure Panel → Position` has only one option starting with Bottom, namely Bottom of desktop X, where X is always the bottom desktop — even when the screens are swapped. The same is true for a top panel.

I remember that, [on Apr 12](https://github.com/lxqt/lxqt/issues/1704#issuecomment-482499928), it wasn't so: the panel was at the middle and I saw a problem with auto-hiding. But that's impossible now.

I always have the latest git LXQt.

Hence, the third question:

 3. Is the panel at the middle of the dual screen when it happens?

**Comment by guiverc** [comment] 2019-11-03 03:46
exploration of ( https://github.com/lxqt/lxqt/issues/1703#issuecomment-500111069 )

> Does it happen under KDE too? If I've understood #1703 (comment) correctly, the answer is "yes"; isn't it?

Most of the time in KDE I cannot re-produce what I described in that comment; I did in one session described here, then on same box booted again later, nope I couldn't again.

-- Details of what I did ...

what I'm doing.  KDE, `dolphin` opened & pointing to a couple of directories containing vids (different resolutions).  `vlc` open in another window.  drag & drop folders (single files appears to do the same) from `dolphin` onto `vlc` to have them play.  `vlc` adjusts window size to match resolution of new 'vid' where it differs to old. this is what I believe causes the issue..

On opensuse tumbleweed, if I'm on [my] top screen, it acts like top left-corner of window is anchored, and if different resolution vid (or folder of vids) is dropped on window, the bottom-right corner of window will change position to reflect different resolution of new playing vid.  Only exception appears to be  if bottom-right corner of vlc window is bottom-right corner of display, top-left corner of window adjusts, anywhere else top-right corner acts like anchored and window adjusts (which can cause window to go off-screen if higher-res vid dropped on window)


I did same testing in fedora (31; same hp 8200) and when dropping folders of different resolution onto vlc, it re-draws at top of display adjusting to that resolution window size.  If dolphin is on [my] top display and 'folder' dragged & dropped on vlc on my bottom display, the window re-draws not at top left-corner of my lower display, but top of window-decorations & menu drawn on my top display…  This did not occur in opensuse tumbleweed.

I rebooted & went back to tumbleweed to re-test, back in fedora & I couldn't re-create what I describe last paragraph. This session when vlc was on bottom window, top-left-corner became anchored top-left corner of my monitor as first described. If i dragged window away from corner, first 'drop' would cause it to warp to top-left-corner of my bottom display & stay anchored there (not re-positioning vertically into my top screen display as it did last time..)  (In this session the only way I could get vlc to open outside of display was opening a larger resolution than fitted, 1080p which didn't fit because of panel and thus creeped onto screen above); otherwise I couldn't re-create what I documented last paragraph!???

I booted Kubuntu (late 19.10 daily used in 'live' mode on hp 8200) and setup screens as I have them, it performed as opensuse did without issues.

**Comment by tsujan** [comment] 2019-11-03 04:02
@guiverc The question about KDE was expired ;)

The panel should never be on the boundary of two adjacent displays, unless they have a relatively big overlap, in which case, what you see will be expected.

If your screens don't have a big overlap and the panel is still at the middle, it shouldn't be with https://github.com/lxqt/lxqt-panel/pull/1261

**Comment by guiverc** [comment] 2019-11-03 04:27
> Your panel is at the middle of the dual screen. That never happens here. Actually, it's impossible because `Configure Panel → Position` has only one option starting with Bottom, namely Bottom of desktop X, where X is always the bottom desktop — even when the screens are swapped. The same is true for a top panel.
> 
> I remember that, [on Apr 12](https://github.com/lxqt/lxqt/issues/1704#issuecomment-482499928), it wasn't so: the panel was at the middle and I saw a problem with auto-hiding. But that's impossible now.
> 
> I always have the latest git LXQt.
> 
> Hence, the third question:
> 
> 1. Is the panel at the middle of the dual screen when it happens?

I booted the hp8200 and booted fedora (31); I didn't notice the bugzilla.opensuse till too late.  My fedora 31 does have the panels on the bottom of both screens; and Configure.Panel allows me to pick Top/Left/Right/Bottom of either monitor.  I'm not using the latest, but default packaged versions for Fedora (31).  (the menu button on the bottom display panel is pointless; menu doesn't show as described elsewhere https://bugs.launchpad.net/ubuntu/+source/lxqt-panel/+bug/1810079  which I'd not yet pushed upstream as I always confirm on another distro before doing that, guess I'll have to do that now..; though it's related)

Switched to opensuse tumbleweed, it still has panels bottom of both displays, and Configure.Panel allows me to pick Top/Left/Right/Bottom of either monitor.  It's bottom panel menu is just as pointless as fedora's (a few pixels appear top of display on hitting menu on lower display just as in fedora on prior launchpad bug report I've not yet filed here)

**Comment by agaida** [comment] 2019-11-03 04:35
@guiverc  - Chris, there are only two convenient (in)sane choices to test against latest git - thats the nature of the beast. These two choices are Arch (Manjaro) with a full LXQt AUR stack or Debian Sid with my experimental snapshots - all other alternatives might fall short.

Both alternatives would make sure that we talk about the same thing - and we highly appreciate your efforts - i guess the most of us don't run at multi monitor settings, for me it is impossible because lack of space and a wife - she would simply kill me for two or three 43" monitors on the desk :smile:

**Comment by guiverc** [comment] 2019-11-03 11:06
booting siduction-patience-lxqt-amd64-latest.iso 2019-11-02
adjust displays so vertical arrangement, this one I could NOT re-create using this live!

**Comment by agaida** [comment] 2019-11-03 15:36
:) - i can build a current (debian/sid) KDE/Plasma too - it's good to have someone who can test not so common cases.

**Comment by tsujan** [comment] 2019-11-10 23:30
Closed in https://github.com/lxqt/lxqt-panel/pull/1261

**Closed by tsujan** 2019-11-10 23:30 UTC

**Comment by tsujan** [comment] 2019-11-10 23:34
@guiverc Please test the latest git panel!

**Comment by guiverc** [comment] 2019-11-15 10:08
Could **NOT** re-produce on 
hp dc7700 (c2d-e6320, 5gb, nvidia quadro nvs 290)
debian-testing, with https://lxqt.debian.net/ as source (fully upgraded).
Vertically aligned screens; both top-bottom combination with default xfwm4 used by debian, plus with `openbox --replace &`

**Comment by tsujan** [comment] 2019-11-15 10:11
Thanks for your test!

So, you definitely have the latest panel patches :)

**Comment by guiverc** [comment] 2019-11-23 07:55
@agaida 

I've been looking for updated package my current, and latest I see is

```
guiverc@dc7700-deb:~$   apt-cache policy lxqt-panel
lxqt-panel:
  Installed: 0.14.2~389-g02cfca52-1
  Candidate: 0.14.2~389-g02cfca52-1
  Version table:
 *** 0.14.2~389-g02cfca52-1 500
        500 https://lxqt.debian.net/debian experimental-snapshots/main amd64 Packages
        100 /var/lib/dpkg/status
```
Am i watching for the correct package to be updated? (ie. did I miss it?)

**Comment by tsujan** [comment] 2019-11-23 08:09
@guiverc 

02cfca5 doesn't contain the needed patches. See https://github.com/lxqt/lxqt-panel/commits/master (the patches are in e9ae6d1).

**Comment by cercelcremene** [comment] 2020-01-12 09:43
I have the same issue. I switched from LXDE to LXQT. The upper part of the screen can be used only for panel, I cannot use it for any window.

**Comment by tsujan** [comment] 2020-01-12 09:46
> I have the same issue.

Fixed in git.
