### ISSUE TITLE
Panel visible on top of Chrome/Firefox in fullscreen (F11) mode

### ISSUE THREAD

**Issue by pmarks-net** [lxqt/lxqt#2369] opened 2023-01-09 19:43 UTC
##### Expected Behavior
When Chrome or Firefox is in fullscreen mode, the lxqt panel should not be visible.

##### Current Behavior
The panel is visible on top of full screen Chrome or Firefox.  This might have started after a `sudo apt dist-upgrade` that included lxqt 1.2.

This problem makes it difficult to control YouTube, for example:

![fullscreen-youtube-lxqt-panel](https://user-images.githubusercontent.com/4578188/211393481-2d3f8598-c939-4f3b-add3-027ffaef69fc.png)

##### Possible Solution
Workaround: enable the "Auto-hide" option.

##### Steps to Reproduce (for bugs)
Press F11 in Firefox or Chrome.

##### System Information
* Distribution & Version: Debian testing
* Kernel: `6.0.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64 GNU/Linux`
* Qt Version: ?
* liblxqt Version: `liblxqt1/testing,now 1.2.0-4 amd64`
* Package version: ?

**Comment by tsujan** [comment] 2023-01-09 19:53
Duplicate of https://github.com/lxqt/lxqt-panel/pull/1850

Please upgrade to lxqt-panel 1.2.1.

**Closed by tsujan** 2023-01-09 19:53 UTC

**Comment by tsujan** [comment] 2023-01-09 20:00
Yes, it's in sid.

Long story short, the cause is a change of behavior in xfwm4, which Debian uses with LXQt by default.
