### ISSUE TITLE
[Feature-Request] The ability to create a shortcut for directories and files.

### ISSUE THREAD

**Issue by Cybermaxrus** [lxqt/lxqt#1380] opened 2017-11-05 15:29 UTC
Hello! I really like lxqt, because it uses QT and has a classic interface, but isn't enough for me
the ability to create shortcuts for directories and files like in MS Windows and MATE. If you add such feature, lxqt becomes the ideal DE.

**Comment by tsujan** [comment] 2017-11-05 15:57
Could you please be more specific? Not all people have MS Windows or MATE.

**Comment by tsimonq2** [comment] 2017-11-05 15:59
I could be wrong, but I think he is referring to the ability to make desktop shortcuts that, when clicked, will take you to the specified place.

**Comment by tsujan** [comment] 2017-11-05 15:59
If by "shortcut" you mean symlink (symbolic link), it's already supported, of course.

**Comment by tsujan** [comment] 2017-11-05 16:11
> ...the ability to make desktop shortcuts...

You mean desktop files as shortcut. I would agree with that but there's a bug that causes a crash when the destination is missing. It's in libfm and it takes ages (in some cases, years) until a libfm PR is merged. Perhaps we should wait until libfm-qt is independent of libfm.

**Comment by tsujan** [comment] 2017-11-05 16:13
> Perhaps we should wait until libfm-qt is independent of libfm

That could also take a long time ;)

**Comment by agaida** [comment] 2017-11-05 16:14
could you please point me to the bug?

**Comment by tsujan** [comment] 2017-11-05 16:18
Maybe I forgot to open an issue but I'm sure I mentioned it somewhere. Will open an issue soon.

@agaida If I fix the bug in a libfm PR, could you merge it fast after it's accepted/reviewed? I think the feature that's requested here is nice.

**Comment by agaida** [comment] 2017-11-05 16:20
it is nice - and we should be  a little bit selfish - file the bug, create a PR, if it compiles and does what ist should i will approve it. And merge it after a certain amount of time (even with or without a review from the LXDE people) - hmm - we should give them enough time, but not forever ...

**Comment by tsujan** [comment] 2017-11-05 16:24
>  and we should be a little bit selfish..

I agree with a little LXQt selfishness -- at least, it's better than a stagnant lbfm. I'll look into the problem as soon as I find some free time -- as usual ;)

**Comment by agaida** [comment] 2017-11-05 16:29
btw: i have an important feature request for pcmanfm-qt - i badly want a desktop trash bin - no DE is nearly feature complete without :P - the importance of that is right before the eyes-plugin for the panel :D

**Comment by tsujan** [comment] 2017-11-05 16:38
> i badly want a desktop trash bin

Please open an issue for it if none exists. It's in my TODO list since time immemorial but always something with more priority has come up, whether inside LXQt or outside it ;)

BTW, the report: https://github.com/lxde/pcmanfm-qt/issues/592

**Comment by tsujan** [comment] 2017-11-06 11:34
Now that the libfm problem is fixed, back to the plan.

An extra item in the right-click menu of a file/folder for creating a "shortcut", while its place, icon and name are chosen by the user? Or choosing the target name and a generic icon, leaving the customization to the user?

**Comment by Cybermaxrus** [comment] 2017-11-06 18:20
Yes, under the shortcut, I mean in symlinks.
In the file manager, when you right-click on a file or directory, there are two items in the context menu:
1. Create a shortcut. Creates a symlink in this directory.
2. Send to Desktop (shortcut). Create a symlinks to the desktop.
3. On the desktop, right-click on the directory or file, and it should also have the item "create a shortcut". 
The user can change the icon and change the name of the already created shortcut.
A few screenshots.
Create a symlinks in the same folder.
https://www.tophattechs.com/windows/Graphics/ShrtctFileRC.jpg
https://www.tophattechs.com/windows/Graphics/ShrtctFileCopy.jpg
Create a symlinks to the desktop.
https://www.wikihow.com/images/thumb/5/58/Make-a-Hidden-Icon-on-Windows-XP-Step-1-Version-2.jpg/aid264573-v4-728px-Make-a-Hidden-Icon-on-Windows-XP-Step-1-Version-2.jpg
https://www.wikihow.com/images/thumb/d/d1/Make-a-Hidden-Icon-on-Windows-XP-Step-2-Version-2.jpg/aid264573-v4-728px-Make-a-Hidden-Icon-on-Windows-XP-Step-2-Version-2.jpg

One more request. Create a menu (in the lower right corner near the clock) consisting of the contents of the folder that you specify.
Screenshots
http://www.watchingthenet.com/wp-content/uploads//tbtaskbar4.jpg
https://www.groovypost.com/wp-content/uploads/2017/02/sshot-3.png
https://www.eightforums.com/attachments/customization/1746d1316186636t-add-desktop-toolbar-task-bar-additional-functionality-dsktp_toolbar.png?s=a2a8bec575ac672b12e0aeed4685b230
https://www.vistax64.com/attachments/tutorials/405d1370210584-taskbar-toolbars-desktop-jpg?s=5650690e225a39f8fba73be5432fc9d1
p.s. I understand these features are not very important, but in my opinion their introduction would improve the experience from using LXQT.

**Comment by tsujan** [comment] 2017-11-06 18:44
@Cybermaxrus As I said above, symlinks are already supported. Just drag and drop any file from anywhere inside a pcmanfm-qt's window and a menu will show up, one of  whose items is "Create symlink here". There's no need to an extra item for that.

What we talked about above was a *desktop link*, which is very different from a symlink. Adding an item for it seems good but I'm not sure if it's popular enough.

The "folder menu" you requested is quite different and is related to the panel, not to the file manager. You could open another issue and request it there.

Please also note that every OS or DE has its own tools and does things in its own way. Therefore, there's no reason for LXQt to look like MS Windows or MATE.

**Comment by LStranger** [comment] 2017-11-08 11:43
>Yes, under the shortcut, I mean in symlinks.
>In the file manager, when you right-click on a file or directory, there are two items in the context menu:
>1. Create a shortcut. Creates a symlink in this directory.
>2. Send to Desktop (shortcut). Create a symlinks to the desktop.
>3. On the desktop, right-click on the directory or file, and it should also have the item "create a shortcut". 
>The user can change the icon and change the name of the already created shortcut.

I believe you mean exactly shortcut, not symlink. Symlink cannot have own
icon or execution rights, it is just another name for already existing
file. Shortcut (or desktop entry, in other words) is an entity with own
name, icon, execution rights, tooltip, etc., which may open folder, some
application, or even execute some system command with or without desktop
representation.

**Comment by Cybermaxrus** [comment] 2017-11-08 19:35
@LStranger Thank you for correcting me. You correctly said - a shortcut. So, is there any chance that this opportunity will be realized?

**Comment by Cybermaxrus** [comment] 2017-11-08 19:37
@LStranger Thank you for correcting me. You said it right  - a shortcut. So, is there any chance that this opportunity will be realized?

**Comment by andrew-phi** [comment] 2018-02-10 19:53
Just adapt those damn .LNK files from Wandows|Wine, please! Don't reinvent more wheels.

**Comment by Vladimir-csp** [comment] 2018-02-10 20:48
> Just adapt those damn .LNK files

lol

What we need here is a generic-purpose desktop entry editor. Desktop entry spec has all the wheels already invented, just waiting to be exposed.
Creating a ~~"shortcut"~~ [Link type desktop entry](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html) out of some directory would be a matter of launching such an editor with certain fields pre-filled.

Anyway, I would like to present a concept: https://github.com/Vladimir-csp/Undefied

**Comment by tsujan** [comment] 2018-02-10 21:50
@Vladimir-csp 

You're completely right when you say this comes to editing a desktop entry. Its structure is so:
```
[Desktop Entry]
Type=Link
Name=...
URL=...
Icon=...
```
The DE knows how to open what comes after `URL`, as it knows how to open any file.

I, for one, have no motivation to implement that because, imo, the user could easily create a template for it.

However, I'm motivated to know why a template for desktop entried isn't possible under `~/Templates` and how that can be fixed.

**Comment by Vladimir-csp** [comment] 2018-02-10 22:02
> However, I'm motivated to know why a template for desktop entries isn't possible under ~/Templates and how that can be fixed.

That would be a bit tricky to do, because templates are more suitable for files which are to be edited by  associated apps. Desktop entries hardly fit into that category because they are rather "executed" (sort of) by FM, unless treated as plain text. IMHO, the concept of using ~/Templates mechanism for this is a bit of a stretch. And besides, this issue is about making an entry based on existing data (i.e. a path, type, associated icon) in one go.

**Comment by tsujan** [comment] 2018-02-10 22:17
@Vladimir-csp I didn't mean that as a solution to this but as a more interesting issue.

Are you sure that a template for desktop entries shouldn't exist? After all, a desktop entry is nothing other than a text file with a special syntax and a special handling.

**Comment by FreeSlave** [comment] 2018-02-10 22:52
Having a sane way to create desktop shortcuts is a good thing. I'm really tired of typing .desktop files myself for both Applications and Links.

As for templates, I'm not sure how you see automatic filling of fields can work when one creates a file from template.

**Comment by tsujan** [comment] 2018-02-10 23:25
Sorry to say that none of this is really possible with the current state of the code.

When people request such features, they don't know the fact -- and how could they know -- that the file management of `pcmanfm-qt` is divided between `libfm-qt` and `libfm`. This feature and the above-mentioned issue about templates are both related to `libfm`.

The problem is that no `libfm` implementation would be good for `pcmanfm-qt`. It's necessary to fix serious bugs of `libfm` -- as has been done several times -- but there's no point to adding more features to it because (1) its functioning is suboptimal in `pcmanfm-qt`, and (2) any new feature will be lost when the remaining code is added to `libfm-qt`.

If the file launching code was in `libfm-qt`, such features could be easily added and probable issues could be really fixed -- as the same thing has happened again and again in those parts of `libfm-qt` which are independent of `libfm`.

Sorry if the above explanation isn't clear enough! That was the best way I could explain the current situation, whose solution should be provided by PCMan, the author of libfm, libfm-qt and pcmanfm-qt.

**Comment by FreeSlave** [comment] 2018-02-10 23:33
I did not get your point. Templates are not connected to the topic at all really.

I don't see much trouble in adding such menu entry as all you need is to write a text file in proper format (just remember doing character escaping) and let handle it to whatever handles .desktop files launching now.

**Comment by tsujan** [comment] 2018-02-10 23:53
> I don't see much trouble in....

Yes, it's easy but ugly. That was how `pcmanfm-qt` was developed until a year ago -- in short, inconsistently. PCMan's big commit changed everything in a good direction but the change isn't complete.

**Comment by tsujan** [comment] 2018-05-10 22:57
PCMan ported the file launching code to c++/libfm-qt. Now, it should be possible to do this consistently.

**Comment by tsujan** [comment] 2018-05-11 06:18
@Vladimir-csp 
As for creating a template for shortcuts, it's possible with the latest git libfm-qt/pcmanfm-qt. The temple code is ported to c++ by PCMan and the above-mentioned issue is fixed.

**Comment by Cybermaxrus** [comment] 2019-02-17 10:17
I'm just curious, maybe there is progress in this?

**Comment by tsujan** [comment] 2019-02-17 11:05
> I'm just curious, maybe there is some progress?

None. See https://github.com/lxqt/lxqt/issues/1621. In short, a separate app should do it.

Closing this because https://github.com/lxqt/lxqt/issues/1621 exists.

**Closed by tsujan** 2019-02-17 11:05 UTC
