### ISSUE TITLE
Touchpad scrolling is "less smooth" on v0.12

### ISSUE THREAD

**Issue by githubtefo** [lxqt/lxqt#1371] opened 2017-10-30 22:31 UTC
##### System Information

* Distribution & Version: Arch 
* Kernel: 4.13
* Qt Version: 0.12

Hello! Since the last update to lxqt v0.12, the scrolling on qpdfview or pcmanfm-qt works worst. It is probably cause by insufficient resources on my tiny laptop, but the previous scroll behavior worked better. Is there any way to revert the changes on scrolling? or alternatively, is there any way to disable smooth/soft scrolling on qt applications?
Thank you!
The rest of the updates works flawlessly!

**Comment by tsujan** [comment] 2017-10-30 22:48
There has been no change in the scroll behavior: 3 lines per wheel turn, unless you change it in preferences. The only thing about smooth scrolling is a PR for libfm-qt that isn't previewed yet, let alone merged. So, there's nothing to disable.

Could you please be more specific about your problem?

**Comment by tsujan** [comment] 2017-10-30 22:53
And qpdfview doesn't support smooth scrolling -- its developer waits for a direct support in Qt.

**Comment by githubtefo** [comment] 2017-10-31 03:43
So it's not smooth scrolling. But there is a difference between the way GTK apps (like pidgin) and Qt (qpdfview, pcmanfm-qt, notepadqq) scrolls: while in the first case the scrolling is by jumps, the second is continuous. Now, I observed that in Qt applications the scrolling became less responsive (with some frames dropped) after lxqt update.
I'm wondering if Qt applications scrolling may behave like GTK applications.

**Comment by tsujan** [comment] 2017-10-31 10:12
> Now, I observed that in Qt applications the scrolling became less responsive (with some frames dropped) after lxqt update.

Unless you explain the problem in a step-by-step, reproducible way, we couldn't know what you see, let alone its cause. "Less responsive" doesn't explain anything -- you could have a graphic-driver problem, something could take a lot of CPU time in your system, etc. The report template (which you skipped) was for that.

**Comment by tsujan** [comment] 2017-10-31 10:29
> with some frames dropped

The scrolling has always been jumpy: 3 lines at a time by default, unless the app supports and implements smooth scrolling -- as Qupzilla does, for example. If you scroll a page with many files in pcmanfm-qt by using the mouse wheel, you should see that with every wheel turn, the view goes up/down by 3 rows *without any frame in between*. That isn't a bug.

**Comment by githubtefo** [comment] 2017-10-31 17:48
Well, that's weird. In my case the scroll has never been jumpy for Qt applications.
(BTW, In all the cases, GTK or Qt, I'm talking about scrolling with the touchpad of the laptop).

**Comment by tsujan** [comment] 2017-10-31 17:59
> I'm talking about scrolling with the touchpad of the laptop

LOL! That makes a great difference, of course. The touchpad scrolling is smooth. And it *is* smooth with the latest git LXQt I use (which is almost the latest release, for now). There may a problem with your touchpad settings. Anyhow, I really doubt it could be caused by LXQt.

**Comment by tsujan** [comment] 2017-10-31 18:11
You could first check which packages were updated in addition to the LXQt ones before the touchpad problem happened. If the answer is "none" and if no setting is changed, then, somehow, the cause would be in LXQt.

**Comment by githubtefo** [comment] 2017-11-06 21:44
As far as I could check, there was not other relevant updates before the touchpad problem happened.

**Comment by tsujan** [comment] 2017-11-06 21:49
Any difference under another DE?

**Comment by githubtefo** [comment] 2017-11-06 22:18
Good point.
If I start openbox DE from the login screen (and not lxqt Desktop) and then I open a Qt application, like qpdfview, now the touchpad scrolling recovers its previous behavior (before v0.12 update).

**Comment by tsujan** [comment] 2017-11-06 22:29
Strange! Then, I have no clue.

@palinek Can LXQt or its v0.12 affect touchpad scrolling?

**Comment by tsujan** [comment] 2017-11-06 22:31
@githubtefo Which compositor (Kwin's compositing, Compton,...) do you use under LXQt and what happens when you disable it?

**Comment by githubtefo** [comment] 2017-11-07 03:36
The compositor is Compton. When I stop it, the behavior doesn't change (it is still the v.012 mode) but it works a bit better (still slower scrolling, but less frame dropping).

**Comment by palinek** [comment] 2017-11-07 09:08
> Can LXQt or its v0.12 affect touchpad scrolling?

Maybe this one? ->https://github.com/lxde/lxqt-qtplugin/commit/f76caec82b1817497a8a675e2661b779786bc26c

@githubtefo try to tweak the number of "Wheel scroll lines" in `lxqt-config-input`... can you turn back your expected behavior with it?

**Comment by tsujan** [comment] 2017-11-07 09:48
@palinek But that's about *wheel* scrolling, while this is about touchpad two-finger scrolling.

**Comment by palinek** [comment] 2017-11-07 09:55
> But that's about wheel scrolling, while this is about touchpad two-finger scrolling.

The setting is applied also for touchpad scrolling for me...

**Comment by tsujan** [comment] 2017-11-07 10:10
> The setting is applied also for touchpad scrolling for me...

I don;t think so. Touchpad scrolling is smooth here, as @githubtefo wants it to be. In views that only support line-by-line scrolling (like QPlaineTextEdit), wheel scrolling is 3 lines per wheel turn while with touchpad scrolling, one line can be scrolled. In other views, like that of qpdfview, Touchpad scrolling is pixel-by-pixel and very smooth, while wheel scrolling is still 3 lines per wheel turn.

**Comment by tsujan** [comment] 2017-11-07 10:24
Or maybe the difference in behaviors is related to libinput vs. synaptics; I use the first.

**Comment by tsujan** [comment] 2017-11-07 10:54
Qt doc says explicitly about `wheelScrollLines `: "This property holds the number of lines to scroll a widget, when *the mouse wheel* is rotated" (italics are mine). I don't see how it could affect the touchpad.

**Comment by yan12125** [comment] 2017-11-07 18:26
@githubtefo: Could you run ```sudo libinput list-devices``` in both LXQt and openbox and compare the outputs?

**Comment by yan12125** [comment] 2017-11-07 18:34
And the output of ```xinput --list-props "your touchpad device name"```. Simply ```xinput``` prints device names.

**Comment by githubtefo** [comment] 2017-11-07 21:10
@yan12125, the output of both commands is the same in both LXQt and openbox. I am attaching both outputs.
[lxqt-output.txt](https://github.com/lxde/lxqt/files/1451655/lxqt-output.txt)
@palinek `lxqt-config-input` allowed me to change the touchpad scrolling speed. Indeed, if I disable Compton and increase "Wheel scroll lines" to 3, I am able to reproduce the openbox current behavior.
Nevertheless, with Compton running and wheel scroll lines to 3 in LXQt I experience a lot of frames drops while scrolling a pdf. And this didn't happen before the v0.12 update.
I feel that now in v.012 the scrolling presents an increase on "inertia", and this behavior increase the resource consumption.

**Comment by tsujan** [comment] 2017-11-07 23:13
More tests:

KWin, Compiz or Compton made no difference here: always very smooth touchpad scrolling, especially with qpdfview. A test with an old Debian stretch and an old LXQt (not updated for 2 years) showed that libinput and synaptics work equally well.

**Comment by yan12125** [comment] 2017-11-08 05:01
@githubtefo FWIW, could you try uninstalling xf86-input-synaptics, installing xf86-input-libinput and see if there's any difference? The former is no longer maintained, which might work less-than-ideal in some cases.
Beware that the libinput driver may not have as many features as the synaptics one. The last I checked (~1 year ago), it doesn't support circular scrolling.

**Comment by githubtefo** [comment] 2017-11-08 09:02
@yan12125, after uninstalling xf86-input-synaptics the touchpad click disappears, while the scrolling doesn't change (f86-input-libinput is already installed).

**Comment by agaida** [comment] 2018-08-16 20:47
not reproducible

**Closed by agaida** 2018-08-16 20:47 UTC
