### ISSUE TITLE
lxsu pcmanfm-qt  error

### ISSUE THREAD

**Issue by eirenicon** [lxqt/lxqt#1595] opened 2018-10-28 14:41 UTC
When attempting to execute the following command in qterminal:
**lxsu pcmanfm-qt** 
the following error occurs: 
                                        
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0

** (process:1136): WARNING **: 08:23:03.320: The directory '/root/Templates' doesn't exist, ignoring it

##### Expected Behavior
A Root priv. file manager window.

##### Current Behavior
the following error occurs: 
                                        
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0

** (process:1136): WARNING **: 08:23:03.320: The directory '/root/Templates' doesn't exist, ignoring it

##### Steps to Reproduce (for bugs)

1. execute the following command in qterminal: **lxsu pcmanfm-qt** 
2. 
3. 
4. 

##### System Information
System:
  Host: LXQt Kernel: 4.18.16-1-MANJARO x86_64 bits: 64 
  Desktop: LXQt 0.13.0 Distro: Manjaro Linux 
Machine:
  Type: Virtualbox System: innotek product: VirtualBox v: 1.2 
  serial: <root required> 
  Mobo: Oracle model: VirtualBox v: 1.2 serial: <root required> 
  BIOS: innotek v: VirtualBox date: 12/01/2006 
Battery:
  ID-1: BAT0 charge: 50.0 Wh condition: 50.0/50.0 Wh (100%) 
CPU:
  Topology: Single Core model: Intel Core i5-6300U bits: 64 
  type: MCP L2 cache: 3072 KiB 
  Speed: 2496 MHz min/max: N/A Core speed (MHz): 1: 2496 
Graphics:
  Device-1: InnoTek Systemberatung VirtualBox Graphics Adapter 
  driver: vboxvideo v: 5.2.20 r125813 
  Display: x11 server: X.org 1.20.3 driver: modesetting 
  resolution: <xdpyinfo missing> 
  Message: Unable to show advanced data. Required tool glxinfo 
  missing. 
Audio:
  Device-1: Intel 82801AA AC97 Audio driver: snd_intel8x0 
  Sound Server: ALSA v: k4.18.16-1-MANJARO 
Network:
  Device-1: Intel 82540EM Gigabit Ethernet driver: e1000 
  IF: enp0s3 state: up speed: 1000 Mbps duplex: full 
  mac: 08:00:27:78:c3:f2 
  Device-2: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge 
  driver: piix4_smbus 
Drives:
  Local Storage: total: 10.00 GiB used: 9.02 GiB (90.2%) 
  ID-1: /dev/sda vendor: VirtualBox model: VBOX HARDDISK 
  size: 10.00 GiB 
Partition:
  ID-1: / size: 9.78 GiB used: 9.02 GiB (92.2%) fs: ext4 
  dev: /dev/sda1 
Sensors:
  Message: No sensors data was found. Is sensors configured? 
Info:
  Processes: 130 Uptime: 1m Memory: 3.85 GiB 
  used: 421.0 MiB (10.7%) Shell: zsh inxi: 3.0.27

**Comment by tsujan** [comment] 2018-10-28 14:52
Duplicate of https://github.com/lxqt/lxqt/issues/1596 (lxsu and lxqt-sudo are the same thing).

**Closed by tsujan** 2018-10-28 14:52 UTC
