### ISSUE TITLE
lxqt-config-appearance 2.0 does not set the theme of QT5 programs properly

### ISSUE THREAD

**Issue by clementtttttttt** [lxqt/lxqt#2583] opened 2024-06-22 09:50 UTC
##### Expected Behavior
System theme being set on QT5 programs

##### Current Behavior
QT5 programs use the default fusion theme instead 

##### Steps to Reproduce (for bugs)

1.  Open lxqt-config-appearance
2.  Change the QT style
3.  Run a QT5 program

##### Context
Trying to use "gtk" as the system wide theme

##### System Information
* Distribution & Version: Gentoo 23.0 llvm profile with lto
* Kernel: 6.9.5-zen1 
* Qt Version: 6.7.2
* liblxqt Version: 2.0.0-r1
* Package version: 2.0.0

**Comment by stefonarch** [comment] 2024-06-22 10:25
See https://github.com/lxqt/lxqt/wiki/Building-from-source#qt5-support

**Comment by stefonarch** [comment] 2024-06-22 10:27
Closing this

**Closed by stefonarch** 2024-06-22 10:27 UTC

**Comment by clementtttttttt** [comment] 2024-06-22 11:03
Fixed after installing the QT5 version of lxqt-qtplugin

**Comment by Plut0nio** [comment] 2024-07-14 15:36
> Fixed after installing the QT5 version of lxqt-qtplugin

Which distro are you using? I'm trying to do this same thing on Void, but I'm having trouble. XBPS (Void's package manager) only has the latest versions of packages (in this case, 2.0.0 for lxqt-qtplugin). I tried building the 1.4.1 source, but it just gave me this error:

```
CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "FindQt5DBus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5DBus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5DBus"
  (requested version 5.15.0) with any of the following names:

    Qt5DBusConfig.cmake
    qt5dbus-config.cmake

  Add the installation prefix of "Qt5DBus" to CMAKE_PREFIX_PATH or set
  "Qt5DBus_DIR" to a directory containing one of the above files.  If
  "Qt5DBus" provides a separate development package or SDK, be sure it has
  been installed.
```

I have qt5-dbus 5.15.11 installed according to XBPS. Maybe I need a dev package instead, but that doesn't seem to exist in the official Void repo.

**Comment by stefonarch** [comment] 2024-07-14 18:37
On arch it looks like it belongs to qt5-base:
```
$ yay -Qo /usr/include/qt/QtDBus/5.15.14/QtDBus/private/qdbusinterface_p.h
/usr/include/qt/QtDBus/5.15.14/QtDBus/private/qdbusinterface_p.h is owned by qt5-base 5.15.14+kde+r141-1

**Comment by Plut0nio** [comment] 2024-07-14 23:43
I had to download and install qt5-devel on Void (along with the dependencies qtchooser, qt5-qmake, and qt5-host-tools) to fix the "no Qt5DBus" CMake error. However, when I tried it again, it couldn't find Qt5LinguistTools, which led me to download and install qt5-tools-devel which also installed qt5-tools and qt-translations. That fixed that, but then it couldn't find Qt5XdgIconLoader. Searching for this brought up libqtxdg, of which I had version 4.0.0 installed (same goes for libqtxdg-devel). I tried building version 3.12.0 of libqtxdg from GitHub, but it didn't work because I had version 2.0.0 instead of 0.13.0 of lxqt-build-tools installed. I was at least able to install and build that version of lxqt-build-tools, which then allowed me to build and install 3.12.0 of libqtxdg.

Re-trying CMake with lxqt-qtplugin, it gave me an error about not having "fm-qt" 1.4.0. I found libfm-qt 1.4.0 on GitHub, but when running CMake on it, it said it couldn't find "MenuCache" 1.1.0. I decided to build and install lxqt-menu-data 1.4.1, which didn't give me errors, but it didn't fix the MenuCache error with lxqt-qtplugin. According to xbps-query, I have both menu-cache 1.1.0 and menu-cache-devel 1.1.0 installed on my system.

I might report this as an issue in the libfm-qt GitHub page. I hope I can figure this out soon. I feel like I'm so close.

**Comment by tsujan** [comment] 2024-07-15 00:26
> I might report this as an issue in the libfm-qt GitHub page.

The problem isn't in libfm-qt. All you need is to adapt https://github.com/lxqt/lxqt/wiki/Building-from-source#qt5-support to your distro. I think you just missed lxqt-qtplugin 1.4.1 — and make sure it's 1.4.1, not 1.4.0.

We hoped that most distros would make things easy for their users by following https://github.com/lxqt/lxqt/wiki/Building-from-source#qt5-support. Apparently they didn't :( Although the procedure is easy in distros like Arch and its derivatives, it may not be so in distros that divide packages into main and dev/devel (and probably more).

**Comment by tsujan** [comment] 2024-07-15 00:37
Oh, and make sure that the names of your Qt5 packages are different from those of Qt6 ones that have installed from the repository of your distro (for example, you could add "qt5" to their names). Otherwise, the former will replace the latter, and the end result will be a damaged LXQt (the system will be intact though).

**Comment by Chiitoo** [comment] 2024-07-15 00:45
Me being the Gentoo Linux maintainer for LXQt packages, is not going to support qt5 on the side of qt6 for things LXQt, it will be one or the other, where the other (qt5) will go away as soon as possible.

**Comment by Plut0nio** [comment] 2024-07-15 00:51
> > I might report this as an issue in the libfm-qt GitHub page.
> 
> The problem isn't in libfm-qt. All you need is to adapt https://github.com/lxqt/lxqt/wiki/Building-from-source#qt5-support to your distro. I think you just missed lxqt-qtplugin 1.4.1 — and make sure it's 1.4.1, not 1.4.0.
> 
> We hoped that most distros would make things easy for their users by following https://github.com/lxqt/lxqt/wiki/Building-from-source#qt5-support. Apparently they didn't :( Although the procedure is easy in distros like Arch and its derivatives, it may not be so in distros that divide packages into main and dev/devel (and probably more).

I'm not sure what you mean by saying that I "missed" lxqt-qtplugin 1.4.1 That's the package I'm ultimately trying to build and install. I can't build and install it right now because CMake can't find "fm-qt 1.4.0", which I assume means libfm-qt 1.4.0. And I can't build and install libfm-qt 1.4.0 because CMake can't find MenuCache 1.1.0.

> Oh, and make sure that the names of your Qt5 packages are different from those of Qt6 ones that you've installed from the repository of your distro (for example, you could add "qt5" to their names). Otherwise, the former will replace the latter, and the end result will be a damaged LXQt (the system will be intact though).
> 
> The above-mentioned problem won't happen if you install them directly from the source, instead of making installable packages first, because those sources are made in such a way that they can coexist with their Qt6 counterparts. However, direct installation from sources isn't recommended.

I've been installing these packages by cloning their individual GitHub repos, checking out the desired releases for each, and then doing cmake --> make --> make install for each. Is this what you mean by "installing directly from the source instead of making installable packages first"? If that's the case then I guess I should be fine. Idk how to rename packages anyway.

**Comment by tsujan** [comment] 2024-07-15 10:05
> I've been installing these packages by ... make install for each.

That can damage your current LXQt installation. For example, in one of your comments you said, "I decided to build and install lxqt-menu-data 1.4.1". In that way, you've overwritten files belonging to xqt-menu-data-2.0.0, without your package manager knowing about it.

**Comment by Plut0nio** [comment] 2024-07-15 11:19
> > I've been installing these packages by ... make install for each.
> 
> That can damage your current LXQt installation. For example, in one of your comments you said, "I decided to build and install lxqt-menu-data 1.4.1". In that way, you've overwritten files belonging to xqt-menu-data-2.0.0, without your package manager knowing about it.

How can I make sure that this is or isn't the case? For me on Void, XBPS (the package manager) installs packages to /usr/ (/usr/bin/, /usr/lib/, etc.) while `sudo make install` installs to /usr/local/ instead, so I didn't think there would be an issue.

**Comment by tsujan** [comment] 2024-07-15 13:29
There will be no problem in the case of sources listed in https://github.com/lxqt/lxqt/wiki/Building-from-source#qt5-support. The reason is that they don't override/overwrite what the package manager has installed for LXQt 2.0.0..

But when you install another program by directly compiling from its source, there are two possibilities:

 1. You may install it inside `/usr/`, in which case, it might silently overwrite files installed by the package manager. You could fix that by re-installing the packages that provide those files with your package manager. Or
 2. You may install it inside `/usr/local/`. Then it might silently override (not overwrite) files installed by the package manager. The reason is that `/usr/local/` usually has priority. Then, re-installation won't help, and you'll need to remove those files from `/usr/local/` manually.

The second case could be very confusing later: you've installed everything correctly by using your package manager but something may not work correctly, because the system uses what's *silently* installed inside `/usr/local/`.

That's why, in general, making installable packages first is highly preferable to a direct installation from sources.

**Comment by Plut0nio** [comment] 2024-07-16 02:22
Thanks for the advice. I just did the following:

1. Re-ran `sudo make install` for libqtxdg 3.12.0, lxqt-build-tools 0.13.0, and lxqt-menu-data 1.4.1 and saved the terminal outputs listing the files that were installed/updated/checked. All of the listed files were in `/usr/local/` except for one in `/usr/lib/` and a handful in `/etc/xdg/`.
2. Re-installed libqtxdg 4.0.0, libqtxdg-devel 4.0.0, lxqt-build-tools 2.0.0, lxqt-menu-data 2.0.0, and lxqt-menu-data-devel 2.0.0 using XBPS.
3. Deleted all the aforementioned files listed by `sudo make install` except for those that were in `/etc/xdg/` (these were already overwritten by XBPS in the previous step).

I think this fixed my LXQt installation (though I didn't notice anything wrong with it beforehand), but I still need to figure out how to get lxqt-qtplugin 1.4.1 installed alongside lxqt-qtplugin 2.0.0, the latter of which I installed using XBPS. I cloned the void-packages repo and tried using xbps-src, but I haven't had luck yet. I'll take all potential further discussion and inquiries about this elsewhere. Thanks again, however.
