### ISSUE TITLE
lxpanel is leaking memory

### ISSUE THREAD

**Issue by suntong** [lxqt/lxqt#2154] opened 2021-12-14 04:42 UTC
Same issue as posted in

**lxpanel is taking too much RAM (and growing)**  
https://forums.raspberrypi.com/viewtopic.php?t=267015&sid=9cc8bddec6c80edebe8a0b7be7b2f2d4

Just that `lxpanelctl restart` is not helping in my case to free up the memory it has allocated.

Reported by `smem`:

```
  PID User     Command                         Swap      USS      PSS      RSS 
 1465 myid     /usr/bin/lxqt-panel           522704   763824   767644   786196
 1224 root     /usr/lib/xorg/Xorg -noliste   169692   828352   847767   874776 
 1461 myid     /usr/bin/pcmanfm-qt --deskt    97892    21880    32147    56488 
```

Even `pkill lxpanel` won't let it free up its memory.

Comparing to the space used by Xorg or pcmanfm-qt, the 760M+ memory (including 520M+ swap space) usage of lxpanel  is huge, while it only has few static items:

![image](https://user-images.githubusercontent.com/2840074/145932345-1e14c17a-d3b2-4f37-a9dc-f2bb5677a181.png)

Is that normal?  
How can I let it free up its memory?

This is LUbuntu 21.10:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
```

Update: 

It is surely leaking memory, otherwise, the heap won't be this big, **1.2G**!!

```
% cat /proc/1465/smaps | grep -A10 'heap'
55672ef42000-55677beb0000 rw-p 00000000 00:00 0                          [heap]
Size:            1260984 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:              749320 kB
Pss:              749320 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:      6576 kB
Private_Dirty:    742744 kB
Referenced:       747880 kB
```

_Originally posted by @suntong in https://github.com/lxqt/lxqt/discussions/2153_

**Comment by tsujan** [comment] 2021-12-14 05:24
We don't have `lxpanel` or `lxpanelctl` in LXQt and the RaspberryPi report you mentioned was about LXDE, not LXQt.

Anyway, the memory usages of both `lxqt-panel` and `Xorg` seem abnormal in your case. You might want to report it to LUbuntu/Ubuntu or, perhaps, their RaspberryPi team.

Closing this because it isn't reproducible upstream, the version of `lxqt-panel` in Ubuntu (0.17.1) is outdated, and opening of https://github.com/lxqt/lxqt/discussions/2153 was enough.

**Closed by tsujan** 2021-12-14 05:24 UTC

**Comment by suntong** [comment] 2021-12-28 22:32
Hmm... hi @tsujan, would it be possible to have lxqt-panel pre-built binary somewhere for people to download? 

I've report the issue to Ubuntu, but it seems to me that nobody would work on the new release for quite a while...

**Comment by tsujan** [comment] 2021-12-29 06:04
Binary/package making is a distro job.
