### ISSUE TITLE
[Feature request]: app menu: make the search results draggable

### ISSUE THREAD

**Issue by tuxayo** [lxqt/lxqt#1781] opened 2020-04-16 04:47 UTC
##### Expected Behavior
- open the app menu (in the panel)
- search for an application
- drag it to the desktop
- it's now on the desktop

##### Current Behavior
- open the app menu (in the panel)
- search for an application
- drag it to the desktop
- drag failed

##### Possible Solution
- make the search results draggable 

##### System Information
* Distribution & Version: Debian 10.3 and Lubuntu 19.10
* Kernel: 4.19.0 for Debian
* Qt Version: 5.11.3
* liblxqt Version: 0.14.1
* Package version: ???

**Comment by tsujan** [comment] 2020-04-16 05:06
Duplicate of https://github.com/lxqt/lxqt/issues/1626

**Closed by tsujan** 2020-04-16 05:06 UTC

**Comment by tuxayo** [comment] 2020-04-16 05:07
Thanks a lot, sorry for the dup.

**Comment by tsujan** [comment] 2020-04-16 05:13
> sorry for the dup.

It's OK. In this case, I found my old report quickly by searching "DND" in open issues. Since that report, I've been so busy with other LXQt codes that I haven't find time to investigate this problem :(
