### ISSUE TITLE
Changing Monitor.Settings and one display loses wallpaper & lxqt menu (certain arrangement of monitors only)

### ISSUE THREAD

**Issue by guiverc** [lxqt/lxqt#1925] opened 2021-02-26 08:45 UTC
On certain display configurations (one monitor above the other), clicking Apply causes one display to go black, and the other to have half the wallpaper.

Further, a right-click on the monitor that has background causes the LXQt menu to appear, however right-click on the other monitor (that is black) only has Openbox's menu appear

Filed on launchpad as https://bugs.launchpad.net/ubuntu/+source/lxqt-session/+bug/1845756

Note: if you reverse the top/bottom display, the issue does not occur. 

##### Expected Behavior
Wallpaper appear on both monitors (half on each)
LXQt menu appears on both monitors when right-click pressed

##### Current Behavior
On changing display configuration (2x displays, 1920x1080) with one display above the other, on clicking apply you get
- one monitor has no background, openbox menu appears with right-click
- other monitor has half of the wallpaper/background, LXQt menu appears with right-click

Note:  If the top/bottom monitor is in one order, the issue will not occur.  If so reversing the top/bottom will have the issue occur.

This issue occurs on OpenSuse tumblweed & Lubuntu hirsute; both are using openbox (I've not tested with anything else).

##### Steps to Reproduce (for bugs)

1.  Two monitors, 1920x1080.
2.  open Monitor.Settings and set one display above the other
3.  click Apply
4.  if issue doesn't occur, firstly I'd suggest logout & login again
5.  if issue still hadn't occurred, swap top & bottom monitors & re-apply.  logout & login may be required as well.

(note I've had the logout/login required, and not-required; can't provide clues as to how that relates (insufficient testing-sample-size for picture sorry)

##### Context
Just annoying glitch, esp. when monitors are positioned in the order (one above other) where the glitch occurs

##### System Information

* Distribution & Version:  Lubuntu hirsute, Opensuse tumbleweed & Debian Bullseye
* Kernel: 5.10.0-14, 5.10.16-1, 5.10.0-3
* Qt Version: 5.15.2 for all
* liblxqt Version: 0.16.0 for all
* Package version: lxqt-session 0.16.0-1ubuntu1  (Lubuntu)

I've only tested when used with Openbox

For pictures & more detail refer https://bugs.launchpad.net/ubuntu/+source/lxqt-session/+bug/1845756 but I'd concentrate on comments #10 & later
Top display - https://bugs.launchpad.net/ubuntu/+source/lxqt-session/+bug/1845756/+attachment/5467407/+files/screen_top_menu.jpg
Bottom display - https://bugs.launchpad.net/ubuntu/+source/lxqt-session/+bug/1845756/+attachment/5467410/+files/screen_bottom_menu.jpg

The issue may also relate to https://github.com/lxqt/lxqt/issues/1709

**Comment by guiverc** [comment] 2021-02-26 11:56
On the debian bullseye/sid box, I switched out openbox ..

I could **NOT** re-create the issue using `xfwm4`
I could **NOT** re-create the issue using `icewm`
switching back to `openbox` & issue could be created again..

it's openbox only it appears... so maybe this issue is mis-filed?

**Comment by tsujan** [comment] 2021-02-26 13:40
> it's openbox only it appears

Then, it's an openbox bug. Closing...

**Closed by tsujan** 2021-02-26 13:40 UTC

**Comment by wxl** [comment] 2021-02-26 18:14
BTW @guiverc Openbox's bug tracker is [here](https://bugzilla.icculus.org/buglist.cgi?bug_severity=blocker&bug_severity=critical&bug_severity=major&bug_severity=normal&bug_severity=minor&bug_severity=trivial&bug_severity=upstream%20issue&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&product=Openbox). Don't forget about the Openbox X session, too, if you want to remove variables.

**Comment by tsujan** [comment] 2021-02-26 18:19
@wxl 
The last time I checked, Openbox's development had been stopped for years.Is that changed?

**Comment by wxl** [comment] 2021-02-26 18:26
@tsujan it's kind of in the same state that LXDE is in: slow. Even then, that's probably not totally accurate. The picture I have been given is that Openbox is basically considered a project that has met its design goals. They don't seem to intend any new features (unless there's good reason) and simply are working on fixing bugs. You can see the newer bugs are getting near-immediate responses. That said, there hasn't been a commit or a new release in about half a decade.

**Comment by tsujan** [comment] 2021-02-26 18:40
> That said, there hasn't been a commit or a new release in about half a decade.

I don't understand. New releases aside, if there's no recent git commit, how are its bugs fixed? A project can reach its goals — no more features — but no experienced developer has the illusion of buglessness.

**Comment by wxl** [comment] 2021-02-26 19:10
Ooops, 2 years now. See [here](https://icculus.org/pipermail/openbox/2018-March/009366.html). Still, I get your point. That's a long time. It's not great.

**Comment by tsujan** [comment] 2021-02-26 19:26
The link shows that it's abandoned since 2018.

Openbox is so popular that some devs should have forked it. Which fork is really active in bug fixing, I don't know.

**Comment by wxl** [comment] 2021-02-26 21:20
Surprisingly, I've seen very few bugs in Openbox personally, so maybe that's why we've (and other distros) have kept going with it. Still, I think that there's going to come a point where we're going to need to make some kind of switch in WM. At the least, when Ubuntu starts forcing Wayland. I don't think that's going to come soon, but I'm confident it will come. When the time comes that we need to switch, Wayland or not, we are blessed to have a desktop environment that's window manager agnostic ;) I've brought up KWin a few times, so maybe that will be the future. We'll see.

**Comment by tsujan** [comment] 2021-02-26 21:33
Also, see https://github.com/lxqt/pcmanfm-qt/issues/1033

A WM is an important program, that should be constantly developed; otherwise, it might interfere with other jobs. I've used Openbox and liked it (I even included Openbox themes in Kvantum -- should remove them with the next version) but the fact is that Openbox is dead.
