### ISSUE TITLE
lxqt-panel: Running a .desktop file does not honor "Terminal=true"

### ISSUE THREAD

**Issue by RalfJung** [lxqt/lxqt#1001] opened 2016-03-28 09:09 UTC
Steps to reproduce:
- Make sure you have a .desktop file in your menu that sets "Terminal=true". For example, on Debian, install "bmon"; or jut create one.
- Start the .desktop file from the menu

Actual behavior:
Nothing seems to happen.

Expected behavior:
The application should be started in a terminal.

More information:
With the following small test application:

```
#!/usr/bin/python3
print("Hallo")
input("Name?")
```

I get the following on the stdout/stderr of lxqt-panel itself when starting the program:

```
Hallo
Name?Traceback (most recent call last):
  File "/home/r/Desktop/test.py", line 3, in <module>
    input("Name?")
EOFError: EOF when reading a line
```

**Comment by palinek** [comment] 2016-03-29 07:46
ref. #433

**Comment by luis-pereira** [comment] 2016-03-29 09:54
@RalfJung Do you have xterm installed ?

**Comment by RalfJung** [comment] 2016-03-29 10:56
Nope, I removed it. I use terminator for my terminal. I was annoyed by XTerm and UXTerm cluttering the "System Tools" menu.

Note that there is no dependency of the lxqt packages to xterm in Debian.

**Comment by pmattern** [comment] 2016-03-29 15:44
I can confirm the problem running LXQt 0.10 from the official repositories of / on Arch Linux and Debian testing but it's fixed in VCS as bmon using its desktop entry file of Debian (not provided by Arch Linux) starts flawlessly on Arch Linux using recent VCS checkouts.

LXQt seems to accept QTerminal only, though. On the said Arch Linux VCS system bmon does not get started if QTerminal lacks besides Konsole, LXTerminal, Terminator, Xfce4 Terminal and Xterm are available. On the other hand being picky about terminal emulators doesn't seem that uncommon as KDE seems to accept nothing but Konsole and LXDE LXterminal and Xterm only.
Maybe we could just display a warning when launching a desktop entry file featuring `
Terminal=true` fails due to lack of a supported terminal emulator? That's what KDE and LXDE are doing as well.

IMO issue can be considered as solved except the question which terminal emulators to support.

**Comment by LStranger** [comment] 2016-03-29 16:00
> and LXDE LXterminal and Xterm only.

This isn't true. LXDE never was and never would depend on some exact terminal emulator, it accepts any one, for example I usually use Konsole and I know people who use more exotic ones like lilyterm, etc. And if any LXDE component ever fails with some terminal emulator that is always considered a bug and gets fixed.

**Comment by pmattern** [comment] 2016-03-29 16:47
@LStranger 
You do realize the said restriction applies to launching desktop entry files featuring `Terminal=true` only?
As a matter of fact attempts to launch desktop entry files featuring the said key just trigger a warning "Failed to execute child proces..." on Arch Linux if both LXTerminal and Xterm lack while e. g. Konsole, QTerminal, Terminator and Xfce4 Terminal are available. Turned out that this particular problem disappeared on Debian testing providing the very same terminal emulators on a new user profile (Terminator was used). This may or may not be due to Debian covering terminal emulators by the alternatives system. You may want to have another look at this.
Anyway this problem is only loosely related to this issue's topic. So if you feel the need to go on discussing let's please do it elsewhere.

**Comment by palinek** [comment] 2016-03-30 01:00
> You do realize the said restriction applies to launching desktop entry files featuring Terminal=true only?
As a matter of fact attempts to launch desktop entry files featuring the said key just trigger a warning "Failed to execute child proces..." on Arch Linux if both LXTerminal and Xterm lack while e. g. Konsole, QTerminal, Terminator and Xfce4 Terminal are available. Turned out that this particular problem disappeared on a Debian testing system providing the very same terminal emulators by using a new user profile (Terminator was used). This may or may not be due to Debian covering terminal emulators by the alternatives system. You may want to have another look at this.

AFAIK `libfm` has parameter in its configuration file (e.g. `/etc/xdg/libfm/libfm.conf`) for the "terminal" and next configuration file with list of "known terminal emulators" (e.g. `/usr/share/libfm/terminals.list`). If they are misconfigured (terminal in `libfm.conf` is not found in `terminals.list`) you probably get the error.

**Comment by LStranger** [comment] 2016-03-30 07:46
>> You do realize the said restriction applies to launching desktop entry files featuring Terminal=true only?

There are no restrictions for that in LibFM. Yes, if you don't select your terminal then it uses default fallback which is Xterm and I think in your Arch the default setting is LXTerminal, it's why it searches for those two, but it's not a restriction but just your settings.

>AFAIK `libfm` has parameter in its configuration file (e.g. `/etc/xdg/libfm/libfm.conf`) for the "terminal" and next configuration file with list of "known terminal emulators" (e.g. `/usr/share/libfm/terminals.list`). If they are misconfigured (terminal in `libfm.conf` is not found in `terminals.list`) you probably get the error.

No, you will not get any error. If LibFM does not know call parameters for a terminal then it prints a warning to error output stream (which by default can be found in ~/.xsession-errors file) and applies default call parameters (-e command...).

**Comment by agaida** [comment] 2018-10-06 14:37
Runs fine here if set right in lxqt-config-session

**Closed by agaida** 2018-10-06 14:37 UTC
