### ISSUE TITLE
Lxqt-leave on the wrong monitor

### ISSUE THREAD

**Issue by Lupccs** [lxqt/lxqt#1636] opened 2018-12-10 11:28 UTC
I'm using Lubuntu 18.10 and two monitors: oddily, I need the secondary monitor to be on the left while the primary one (with panel and icons) is the one on the right. I'd prefer to keep it this way cause that's how they're phisically placed in my room. I used the "monitor" app of the distro to do it. On obconf, new windows as set to show on the primary monitor, the primary monitor is set as fixed and it's the number 1.

when I select from the menu the option to shudown, reboot, or whatever, the window always pops up on the secondary monitor. I can move it to the other monitor but even if I hit ok in that situation, next time it will show on the secondary again.

Other windows may show on the wrong monitor the very first time an app is launched, but when I move the app to the primary monitor and close it, the next time I'll show it I'll find it on the primary monitory

lxqt-leave 0.13.0
liblxqt   0.13.0
Qt        5.9.5

**Comment by ringo32** [comment] 2019-02-03 11:38
do you have it too, if you open the lxqt screen shoot, lximage-qt  you make a screenshot. its all in Screen 1,but if you select a area whatever, it popus up in second screeen ?

**Comment by Lupccs** [comment] 2019-02-04 08:51
I don't know if I understood your question. Anyway, I launched the
screenshot utility and went for the "select area" option, clicked an area
and, unlike lxqt-leave, everything appeared in the same monitor, the
current and primary one, even the final lximage-qt . Was that what you
meant?

Il giorno dom 3 feb 2019, 12:38 ringo32 <notifications@github.com> ha
scritto:

**Comment by ringo32** [comment] 2019-02-04 08:59
first i did in screen 1 but that happends not O_o  , but i go select 2d screen  now screen1 comes on  , its not permanent but want to select now it came up like https://imgur.com/a/U8ujflY

**Comment by Svalorzen** [comment] 2020-05-07 23:09
I'm having the same problem on Lubuntu 19.10. 

Additionally, I can't even seem to move the lxqt-leave window (it doesn't seem to actually be a window, it's not listed in the alt-tab menu as well). This is pretty annoying since sometime I have my second monitor turned off, and when I want to shutdown I have to turn it on in order to find the menu and click shutdown.

Has there been any news on this?

**Comment by tsujan** [comment] 2020-05-08 03:38
> Additionally, I can't even seem to move the lxqt-leave window

That's by design and isn't related to the problem.

I'm late to the party but I think the problem should be in our code and, most probably, its fix is simple. Will take a look at it.

**Comment by tsujan** [comment] 2020-05-08 06:44
OK, no wonder why I can't reproduce it. It's already fixed in 0.15.0 (https://github.com/lxqt/lxqt-session/pull/311).

**Closed by tsujan** 2020-05-08 06:44 UTC
