### ISSUE TITLE
After clicking a Qt program to move its window, program window now stuck on mouse cursor

### ISSUE THREAD

**Issue by ms6676749** [lxqt/lxqt#835] opened 2015-10-01 01:01 UTC
When I move a Qt program by clicking and holding mouse button 1 elsewhere other than its title bar, the program is not released when I release the mouse button.  Instead, the Qt program is "stuck" to my mouse cursor.  There's no effect after pressing mouse buttons 1, 2 or 3.  I have to press Esc to release the move icon.  The Qt program, unfortunately, zips back to its original position.

Expected behavior:
Clicking and holding mouse button 1 within a blank area in a Qt program, say qas, allows me to position the program whereever I choose.  Upon release mouse button 1, the Qt program is now at a new position I defined. 

Setup:
Distro - Archlinux
lxqt-desktop-git (AUR)
WM - Openbox 3.6.1-1
Compositor - Compton-git (AUR)

**Comment by pmattern** [comment] 2015-10-01 10:52
Moving windows by dragging & dropping a window component other than titlebar is actually not that common. Could you please elaborate the program you were running when you stumbled upon this problem, just "qas" seems a bit vague to me?

**Comment by stefonarch** [comment] 2015-10-01 12:57
qasmixer actually allows moving by clicking anywhere, but it releases well here, does not stick.
Other programs allow moving pressing ALT (kwin) and clicking anywhere in the window but work well too.

**Comment by pmattern** [comment] 2015-10-01 14:28
Weird. The window of `qasmixer` looks like any other ordinary window here, d&d by using mouse button one works in its title bar only, d&d by holding `Alt` plus using mouse button one works all over the window, no problems either way, same findings using either Openbox 3.6.1 or KWin 5.4.1.
Is there any magic I'm missing?

**Comment by ms6676749** [comment] 2015-10-01 15:37
The Qt "move anywhere" feature is seen below:
http://www.youtube.com/watch?v=N2PeL8WAifs
http://www.youtube.com/watch?v=qPkOjcc6wwE

This issue exists with every Qt program I tried: pcmanfm-qt (AUR git), konsole, vlc, cantata, konversation, lxqt's configuration center, qps (sorry for "qas" typo above)...  You get the picture.  Strangely, the only Qt program this feature does not work on my system is qterminal.  It is just a KDE'ism (or rather Qt'ism) I got used to over the years.  I do have Plasma 5 on my system but I boot to the terminal and start lxqt from there.

**Comment by pmattern** [comment] 2015-10-01 17:11
Confirmed.

The missing peace was that the problem can only be seen if a widget style is in use that's configured accordingly, which can apparently done in KDE only right now.
So in case anyone is interested steps to reproduce, seen with KDE Plasma 5:
* Invoke KDE System Settings and select Appearance - Application Style - Widget Style (left column) - Applications (left tab in right pane). In line "Widget style" chose an appropriate style like `Oxygen` or `Breeze`, click button `Configure...` at the right. In dialog "Configure \<Widget style chosen\>", tab General select `Drag windows from all empty areas` at the bottom. Save settings.
* Launch a KDE session and make sure d&d from empty window areas works as expected. (optional)
* Launch an LXQt session, chose one of the widget styles configured in KDE's System Settings in `lxqt-config-appearance` - Widget Style (left column), d&d from empty window area → problem as described above can be seen.

**Comment by stefonarch** [comment] 2015-10-02 11:00
I have recently cleaned up my home, erasing also ~/.kde4 so only default settings there now.

**Comment by jleclanche** [comment] 2015-10-17 14:22
I had been seeing this as well. Would really like to know where the issue is. I think it's in Qt tbh.

**Comment by stefonarch** [comment] 2016-06-28 15:01
I just retried: KDE System Settings > Application Style - Widget Style > breeze > configure button > in the drop-down at the bottom selected the 3° item "empty aera" but cannot reproduce the sticky behaviour, also not with the second option.

**Comment by palinek** [comment] 2016-07-06 10:59
Is this "wrong stick" behaviour reproducable in plain openbox session?
If so, it has nothing to do with LXQt and this issue can be closed.

**Comment by paulolieuthier** [comment] 2016-07-31 02:59
@pmattern it's been almost a year, so can you still reproduce it? I can't, using KWin and Breeze and trying to follow your steps. I agree this is probably not related to LXQt so, not high-priority. If it's no longer reproducible we should close it. If it is, and proven to be related to LXQt, I think we should move it to the next milestone.

**Comment by pmattern** [comment] 2016-08-01 23:26
@paulolieuthier
I cannot reproduce this any longer on up to date Arch Linux either. So the problem seems to have been solved what ever it was.

@ms6676749
Any chance you can verify this, too? Looks like we can close this issue.

(On a side note this once more demonstrates that a lack of suitable configuration tools for various components which basically play nicely with LXQt does represent a problem. This is affecting KWin as well. Different story, of course.)

**Comment by technic** [comment] 2016-09-09 17:44
I have feature of dragging a window by clicking on empty space enabled. Probably, it is enabled somewhere in qt settings since I was using KDE.
At the moment (Up to date arch linux and lxqt git) I don't see any issues with this too.

**Comment by pmattern** [comment] 2016-09-09 18:20
> Probably, it is enabled somewhere in qt settings since I was using KDE.

[Probably](https://github.com/lxde/lxqt/issues/835#issuecomment-144789129), indeed.

**Comment by tsujan** [comment] 2016-09-09 18:30
> I have feature of dragging a window by clicking on empty space enabled. Probably, it is enabled somewhere in qt settings since I was using KDE.

I don't know about this report but dragging a window by clicking on empty space is a feature in the style plugin (theme engine), not in the DE. Oxygen, QtCurve and Kvantum have it. Unfortunately, KDE makes its users confuse the style plugin with the style.

**Closed** 2018-07-15 03:45 UTC
Labels: high-priority, polish, upstream
