### ISSUE TITLE
LXQt on Light Locker does not unlock the session

### ISSUE THREAD

**Issue by RangHo** [lxqt/lxqt#1463] opened 2018-03-24 02:04 UTC
##### Expected Behavior

After session is locked by any means, Light Locker should be able to properly unlock and recover the LXQt session.

##### Current Behavior

Even though authentication is successful, LXQt session is visible for a less than a second, and the session locks again. (and user is dropped back to the LightDM greeter dialog.)

##### Steps to Reproduce (for bugs)

Precondition: LightDM and Light Locker are installed, and configured as the main DM.
1. Lock the current session. Method of locking the session does not matter here. (I tried closing the laptop lid, suspending the session with `Lock upon suspension` settings turned on, executing `dm-tool lock` command so far.)
2. Once the screen turns off, give some input to bring the screen up again.
3. Authenticate.
4. LXQt session should be visible, but within a second, user should see LightDM greeter dialog again.

##### Context

From a clean installation of Arch, I installed LightDM, Light Locker, and LXQt right away on my laptop. Since this bug appears whenever I close my laptop lid, it is very frustrating to force-restart the system every time.

I initially speculated that this is caused by Light Locker and LightDM, so I tried to dig into LightDM's log, but no significant information was found. LightDM authentication was successful, the locker did unlock the session, but in 0.4 seconds, the session was locked again. I tried the same steps above on LXDE and KDE also, but they had no problem recovering the session.

##### System Information

* Distribution & Version: Arch Linux (installation media was created in 03/16/2018)
* Kernel: 4.15.10-1-ARCH

**Comment by stefonarch** [comment] 2018-03-24 08:45
SDDM is the recommended display manager, and at the moment only xscreensaver is supported for locking screen.

**Comment by palinek** [comment] 2018-03-26 06:44
This seems like the `lxqt-session` is crashing. Can you see some coredumps generated?

**Comment by igordsm** [comment] 2018-05-28 23:02
I can also reproduce this with Lubuntu 17.10 with LXQt from master. I did not find any dumps in */var/crash* and it seems *lxqt-session* did not die (same pid as before locking). Any other tips that may help debugging?

**Workaround**: I can unlock by killing light-locker from a text-only virtual terminal.

**Comment by agaida** [comment] 2018-05-28 23:38
hmm - right now i'm not convinced that the bug it in LXQt - it might be helpful if someone would find the time and debug the _**xdg-screensaver**_. @stefonarch - not true, we do not hard depend on xscreensaver - at least not that i really know. I'm myself not a the biggest jwz fan, but he claimed that his xscreensaver is the only sane implementation of a xcreensaver/locker for X - and right now he seems to be right.

**Comment by tsujan** [comment] 2018-05-28 23:48
> we do not hard depend on xscreensaver - at least not that i really know

A proof: I never ever use xscreensaver ;)

**Comment by agaida** [comment] 2018-05-28 23:51
Well - that's one of our "problems" - we use xdg when ever we can - and regardless in which state (of mid) some components (-maintainers) are. And that make it even harder for users to point at bugs.

**Comment by igordsm** [comment] 2018-05-29 00:55
@tsujan Which do you use? xscreensaver works for me, but light-locker does not. Haven't tried other options yet.

**Comment by tsujan** [comment] 2018-05-29 01:10
> @tsujan Which do you use?

None -- having no use for a screen saver/locker. I just meant that @agaida was right when he said LXQt doesn't depend on xscreensaver. However, months ago, I tried xscreensaver -- just to see how it works -- and encountered no problem.

**Comment by agaida** [comment] 2018-05-29 21:51
ok, the light-locker dependency on lightdm was mentiond before- i tested it right now in a live system and it worked as expected - so i guess we should close this bug. 

https://youtu.be/I8-rfJ2cUWs - a short screencast

**Closed by agaida** 2018-05-29 21:51 UTC

**Comment by igordsm** [comment] 2018-05-30 12:00
@agaida I am using light-locker with lightdm and it still happens to me (Lubuntu 17.10, lightdm 1.24.0, light-locker 1.7.0). What version are you using?
