### ISSUE TITLE
Searched programs can not be pulled into the task bar

### ISSUE THREAD

**Issue by BaumGuard** [lxqt/lxqt#1630] opened 2018-11-24 22:32 UTC
If you search after programs and you want to add a program to the task bar, that doesn't works. Would be great, if that could be implemented, because you always have to search the program yourself to pull it into the task bar.

**Comment by tsujan** [comment] 2018-11-25 04:34
duplicate of https://github.com/lxqt/lxqt/issues/1626

**Closed by tsujan** 2018-11-25 04:34 UTC
