### ISSUE TITLE
There is no button save changes in LXQT session

### ISSUE THREAD

**Issue by aaffdd** [lxqt/lxqt#2358] opened 2022-12-28 21:54 UTC
When I shutdown Lubuntu (russian locale) system tell my that all changes will be lost. But no way to save changes. There is no button save changes in LXQT, anywhere. As result, when I restart computer I need go to "Keyboard and mouse settings" > "keyboard layout" and set to Ctrl+Shift or use Alt+Shift, by default

* Distribution & Version: Ubuntu 22.10
* Kernel: Linux 5.19.0-26-generic
* Qt Version: 5.15.6-1
* liblxqt Version: 1.1.0-0ubuntu1
* Package Version: 30ubuntu2

**Comment by stefonarch** [comment] 2022-12-29 07:58
This message refers to unsaved documents. LXQt settings are applied on closing settings  window, or  "ok" /  "apply" if present.

If I understand you well the setting for keyboard layout switching is not preserved? 

 I cannot reproduce this in VM with Lubuntu, with RU <none>, do you use a variant?

**Comment by tsujan** [comment] 2022-12-29 08:42
Yes, that message has nothing to do with LXQt settings. It just warns the user about ending the session. LXQt settings are saved once you change and apply them.

Closing this, but feel free to add comments if you have another problem.

**Closed by tsujan** 2022-12-29 08:42 UTC
