### ISSUE TITLE
Panel hover on tray with autohide: panel hide

### ISSUE THREAD

**Issue by vitaly-zdanevich** [lxqt/lxqt#1913] opened 2021-02-04 15:13 UTC
![out](https://user-images.githubusercontent.com/3514015/106912777-67001e80-6714-11eb-8acb-3d645bef4966.gif)

##### Expected Behavior
When my mouse is hover WiFi icon - do not hide the panel, the user must have enough time to click.

##### Current Behavior
When my mouse is hover WiFi icon - the panel disappear, the user sometimes does not have enough time to click.

##### System Information
* Distribution & Version: current stable Gentoo
* Kernel: 5.4.92
* Qt Version: 5.15.2
* liblxqt Version: 0.16.0
* Package version: 0.16.0

**Comment by tsujan** [comment] 2021-02-04 15:21
Duplicate of https://github.com/lxqt/lxqt/issues/1812

**Closed by tsujan** 2021-02-04 15:21 UTC
