### ISSUE TITLE
QTerminal does not save entered commands in .bash_history

### ISSUE THREAD

**Issue by Betaversiondot** [lxqt/lxqt#1432] opened 2018-01-05 15:45 UTC
##### Expected Behavior
Normally, i open any terminal and press "Up" arrow on keyboard to scroll through commands i entered in previous terminal runs.

##### Current Behavior
QTerminal does not save commands to .bash_history, so i can scroll only through commands that i entered in other terminals (UXTerm and xfce4-terminal both works as expected) or that i entered in that run. If i type "history", QTerminal shows me content of .bash_history and saves all commands entered in this run and starts to save all entered commands until i close QTerminal. When i launch it again i can scroll through commands entered in previous run, but i have to type "history" again to start saving commands in this run.
Same behavior on my old installation of Debian 10 Xfce and on fresh installation of Debian 10 LXQt. Im using QTerminal with default settings and set it to be default terminal. Xfce4-terminal and UXTerm works fine.

Debian 10 Buster (both Xfce and LXQt editions)
Linux 4.14.7
Qt Version: 5.9.2
Package version: 0.8.0

**Comment by ypnos** [comment] 2018-01-06 15:48
The history is a shell feature and not a terminal feature. We need to figure out why your shell behaves differently when run in this terminal as compared to other terminals.

If you start your session in the terminal by running `bash`, does the behavior change?

**Comment by Vladimir-csp** [comment] 2018-01-06 16:23
I am not seeing this in package 0.8.0-4 on Buster. 
Just a wild guess: if bash somehow gets killed with SIGKILL or crashes when qterminal exits, it won't save history.
May be other reason. Post output of `env` in both terminals.

**Comment by tsujan** [comment] 2018-01-06 16:43
I can confirm @Betaversiondot's observation here. Let me explain it with a simple example:

In XTerm, I enter `cd A_DIRECTORY`. When I close XTerm, `cd A_DIRECTORY` appears at the end of `~/.bash_history`. But when I do the same thing with QTerminal, that doesn't happen.

**Comment by tsujan** [comment] 2018-01-06 16:50
> If you start your session in the terminal by running bash, does the behavior change?

It does, here.

**Comment by tsujan** [comment] 2018-01-06 16:52
This is a bug in QTerminal; it doesn't happen with Konsole.

**Comment by ypnos** [comment] 2018-01-06 16:54
Does it append to the history when exiting via Ctrl+D instead of closing the terminal?

**Comment by tsujan** [comment] 2018-01-06 16:55
> Does it append to the history when exiting via Ctrl+D instead of closing the terminal?

Yes, it does!

**Comment by Betaversiondot** [comment] 2018-01-07 07:08
This is output when i close QTerminal by File->Exit or by clicking on crosshair:
```
beta@beta-version-pc:~$ qterminal
QDir::exists: Empty or null file name
QProcess: Destroyed while process ("/bin/bash") is still running.
beta@beta-version-pc:~$
```
This is output when i close QTerminal by Ctrl+D:
```
beta@beta-version-pc:~$ qterminal
QDir::exists: Empty or null file name
beta@beta-version-pc:~$
```
Exiting via Ctrl+D saves history as expected.

**Comment by ypnos** [comment] 2018-01-07 14:17
The `QProcess` destructor [kills the process](http://doc.qt.io/qt-5/qprocess.html#dtor.QProcess). The expected behavior from a terminal is to detach the shell process, such as the shell process receives a SIGPIPE when the terminal is destroyed.

**Comment by ssspacez** [comment] 2018-01-08 16:28
I can confirm this issue, I'm not using LXQt at the moment but a few days ago I gave it a try and the QTerminal was not "recording" the commands properly.

**Comment by jsm222** [comment] 2018-04-03 16:51
FWIW http://download.kde.org/stable/4.14.3/src/konsole-4.14.3.tar.xz src/Mainwindow.cpp does not set     `setAttribute(Qt::WA_DeleteOnClose);` and thus does not call the destructor of QProcess. Do not know all memory implications of skipping `setAttribute(Qt::WA_DeleteOnClose);` in qterminal but it does save history on all closeEvents when Qt::WA_DeleteOnClose is not set

**Comment by ypnos** [comment] 2018-04-03 17:16
Qt normaly quits the event loop when "the last window is closed", I assume this includes running QProcesses etc.; so I would guess that as both shell process and window are gone at this point, the application will perform the regular cleanup, at least I didn't see anything to the contrary in `main.cpp`.

In general it is also, for this very same reason, not necessary to set `Qt::WA_DeleteOnClose` on a main application window. However the problem is that one QTerminal process can hold several windows, and these would not be cleaned up before all of them are closed if `Qt::WA_DeleteOnClose` is unset.

**Comment by tsujan** [comment] 2018-04-03 17:28
> I found that if you open several tabs in a window, then close a single tab, this also destroys the shell process associated with the tab.

I haven't read this part of the code but that may mean that the tab page is the parent of the `QProcess` in question.

**Comment by tsujan** [comment] 2018-04-03 17:31
> However the problem here is that one QTerminal process can hold several windows, and these would not be cleaned up before all of them are closed if Qt::WA_DeleteOnClose is unset.

What about Konsole? If it has the same behavior, the solution should be in its code. If not, we could remove that behavior from QTerminal. Again, sorry that I can't look into the codes now!

**Closed** 2018-04-18 15:44 UTC
Labels: bug
