### ISSUE TITLE
No LibreOffice button in taskbar

### ISSUE THREAD

**Issue by aramazano** [lxqt/lxqt#1482] opened 2018-04-29 23:06 UTC
Hello,

When LibreOffice is launched without arguments (i.e. `libreoffice` or `/usr/lib/libreoffice/program/oosplash`) then it *is* visible in the task bar. But when launched with a component argument (`--calc`, `--writer`, `--impress`, `--draw`, `--math`) then nothing is placed on the task bar. Only exception is `libreoffice --base` which places a button on the task bar *only during* database creation wizard. When the wizard finishes (and db manager takes control), the LO button vanishes from task bar. It doesn't matter whether I launch it from menu, lxqt-runner, or terminal.

No problem with other programs, as far as I am aware of.

This was started about a week ago (or so) I believe. Now I have upgraded to LXQt 26 and it persists. FWIW, I am using Fusion with Light theme, though I have always been using them for a long time.

Thanks and regards.

#### System Information
* Distribution & Version: LXQt [experimental-snapshots](https://lxqt.debian.net/) on top of Debian Testing (Buster)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* lxqt version: 26
* liblxqt Version: liblxqt0 / 0.12.1~8-g80f9324-1
* lxqt-panel Version: 0.12.1~27-gd7a441cc-1
* lxqt-qtplugin Version: 0.12.1~9-g7081701-4 (FWIW)

Edit: Corrected version info.

**Comment by aramazano** [comment] 2018-04-29 23:09
Oh BTW the last time I upgraded LO was before this bug surfaced (I pinned it), so I don't think it is related to libreoffice. But I will check with the latest LO and update the thread about results.

**Comment by tsujan** [comment] 2018-04-29 23:16
Confirmed, with libreoffice-fresh 6.0.3-1 from Arch. Actually, an icon is shown for a moment and then disappears.

I don't know if this bug is new or not -- although I use Writer a lot, I never paid attention to its taskbar icon.

**Comment by tsujan** [comment] 2018-04-29 23:32
@aramazano It isn't related to the app; it's Panel's responsibility and the fix may be easy (I haven't looked into it though).

**Comment by aramazano** [comment] 2018-04-29 23:45
Could it possibly be related to the fix regarding this? https://github.com/lxqt/lxqt/issues/1468

**Comment by tsujan** [comment] 2018-04-29 23:53
> Could it possibly be related to...

No, it can't.

**Comment by tsujan** [comment] 2018-04-30 00:16
OK, this is a VERY old issue. I had time to boot into an ancient Debian on another computer and saw a sort of it (not identical) in the ancient LXQt I have there.

**Comment by tsujan** [comment] 2018-05-01 02:29
Haven't had time to look into it yet; just a little nagging instead: The worst thing happens when the window is minimized. Then you should try to open the same file to see it again.

**Comment by agaida** [comment] 2018-05-01 02:31
Alt-Tab works fine in that case

**Comment by tsujan** [comment] 2018-05-01 02:37
Yes! Forgot it.

**Comment by tsujan** [comment] 2018-05-01 02:45
A fast look before closing the laptop lid: the problem can be in `LXQtTaskBar::acceptWindow()`.

**Comment by tsujan** [comment] 2018-05-01 03:41
OK, my guess was wrong. The problem is in `LXQtTaskGroup::onWindowChanged` → below this comment:
```c++
// if class is changed the window won't belong to our group any more
```
I should see whether its removal has side effects and if yes, how it can be changed.

Now, really closing the lid.

**Comment by aramazano** [comment] 2018-05-01 15:34
And I just remembered that, before this problem surfaced, there was another minor glitch with LO icon in task bar, which might be related to this one.

LO icon was good when LO is in the foreground, but it was getting distorted when some other program is brought to foreground (or LO is pushed back to background). Just the small icon in the LO button at the taskbar was being distorted. The LO taskbar button itself, or the text on the button was OK.

**Comment by tsujan** [comment] 2018-05-01 17:12
> LO icon was good when LO is in the foreground, but it was getting distorted...

That's exactly what I saw in that old Debian of mine. Anyhow, the fix is here: https://github.com/lxqt/lxqt-panel/pull/465

**Comment by lxdeadmin** [comment] 2018-05-01 17:47
yes - after searching the existing bugs if maybe one has filed a bug before

**Comment by tsujan** [comment] 2018-05-01 17:52
@aramazano No problem is minor. Please report any issue you find.

@lxdeadmin If you find a similar report, please close it. Sometimes it isn't easy to find a similar report because of titles.

**Comment by tsujan** [comment] 2018-05-01 17:54
> So, would you recommend me to report even trivial glitches such as this one (distorted icon)?

If it's about LibreOffice, this report covers it. If not and you think it's an LXQt bug and not related to your graphic card or compositor (if any), yes. You'll know such matters after a while.

**Comment by lxdeadmin** [comment] 2018-05-01 17:56
i do this every time if i find one - one can call me @agaida - only some administrative work, therefor the not usual login :D

**Comment by tsujan** [comment] 2018-05-01 17:58
> one can call me @agaida 

I guessed but wasn't sure :D

**Closed** 2018-05-01 21:09 UTC
Labels: lxqt-panel

**Comment by aramazano** [comment] 2018-05-01 21:41
I have tried 0.12.1~30-g577e7113-1 and the original problem is solved now. But "distorted LO icon" rpoblme persists. Do I file a new bug for that?

**Comment by tsujan** [comment] 2018-05-01 21:45
I don't see any distorted icon here but yes, please open an issue with a concise explanation, the way to reproduce the problem and, preferably, an attached screenshot.

**Comment by tsujan** [comment] 2018-05-01 22:26
@aramazano 
(1) Do you have compositing? 
(2) What LXQt theme do you use? (Configuration center → Appearance → LXQt Theme)

**Comment by aramazano** [comment] 2018-05-01 22:29
No compositing at all. Using "Light" theme.
