### ISSUE TITLE
Drag&Drop from mainmenu panel plugin not working

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1821] opened 2020-07-02 19:50 UTC
Trying to put a entry into the quicklaunch plugin from the mainmenu plugin doesn't work.
It worked the last I used it (probably before upgrading to 5.15)

##### Expected Behavior
Working as usual

##### Current Behavior
The cross indicating that a drag is in progress doesn't even show up.
It indicates that the issue must be in either mainmenu or libqtxdg.
Maybe a Qt 5.15 regression

##### Steps to Reproduce (for bugs)
1. Try to drag something from the mainmenu to the quicklaunch plugin

##### System Information

* Distribution & Version: Manjaro
* Kernel: Not relevant
* Qt Version: 5.15
* liblxqt Version: git
* Package version: git

**Comment by luis-pereira** [comment] 2020-07-02 19:51
@tsujan Can you check ?

**Comment by tsujan** [comment] 2020-07-02 20:09
@luis-pereira 
It works fine here. Are you sure the panel isn't locked?

**Comment by tsujan** [comment] 2020-07-02 20:26
@luis-pereira 
Strange! It works on my second computer (from which I wrote the above comment) but, when I came to my main computer, I couldn't drag anything from Main Menu, regardless of Quick Launch. Is that what you see there?

I have the same version of LXQt Panel on both systems but my second system, where dragging works fine, has Qt 5.14.X.

**Comment by stefonarch** [comment] 2020-07-02 20:43
Hm, here on arch and github checkout it is as described: doesn't work and no indicator.

**Comment by tsujan** [comment] 2020-07-02 20:54
Let be explain exactly what I see on my main system with Qt 5.15:

 1. Drag from the main menu does NOT work.
 2. Drag and drop from pcmanfm-qt (/usr/share/applications) to Quick Launch works without problem.

Please tell me about 1 and 2 on your systems!

**Comment by stefonarch** [comment] 2020-07-02 22:09
Testing draging from pcmanfm-qt I get a strange window...
![schermata-03-00-07-09](https://user-images.githubusercontent.com/10681413/86413358-4aed5800-bcc1-11ea-888d-f81fd0a834c6.png) saying "in this moment the <item> cannot be added to quicklaunch", never saw that.

**Comment by tsujan** [comment] 2020-07-02 22:16
OK, we may be dealing with different problems here.

Since I have the same versions of panel and libqtxdg on both systems — my panel is  https://github.com/lxqt/lxqt-panel/commit/a736e13cc6ff787ba57b8706a15b0325e863c61c and my libqtxdg is 3.5.0 (only 3 commits have been added after it) — I think something may have changed in Qt 5.15.

When Qt 5.15 came here, I recompiled libqtxdg, liblxqt and lxqt-qtplugin. I'll recompile the panel now and report back, although, IMO, it shouldn't make a difference.

**Comment by tsujan** [comment] 2020-07-02 22:28
I recompiled the panel but no change: in the system with Qt 5.15, panel items cannot be dragged but items can be added to Quick Launch from pcmanfm-qt and can be removed from it with Ctrl+Drag and dropping outside it.

**Comment by tsujan** [comment] 2020-07-02 22:31
@stefonarch 
Try to drop items from `/usr/share/applications`, not from pcmanfm-qt's Applications directory (I don't think the second one has ever been possible).

**Comment by tsujan** [comment] 2020-07-02 23:42
@luis-pereira 

I'm almost sure this is a bug in Qt 5.15. `QMouseEvent::buttons()` always gives `Qt::NoButton` inside this block https://github.com/lxqt/libqtxdg/blob/73b63a7aa5e86ea585b49b58e6ba6335d829e494/src/qtxdg/xdgmenuwidget.cpp#L149.

I also tested with a subclassed menu in FeatherPad's code and got the same result: whether the left mouse button was pressed or not,  `Qt::NoButton` was returned with mouse move event.

I think it's be easy to make a simple test code but I'm so tired now; should sleep.

I added the "qt5" label; remove it if I was wrong.

**Comment by luis-pereira** [comment] 2020-07-03 16:04
@tsujan 

> Strange! It works on my second computer (from which I wrote the above comment) but, when I came to my main computer, I couldn't drag anything from Main Menu, regardless of Quick Launch. Is that what you see there?

Yes.
> I have the same version of LXQt Panel on both systems but my second system, where dragging works fine, has Qt 5.14.X.

Yes, With 5.14 worked Ok. Qt 5.15 seems to be the culprit here,

**Comment by tsujan** [comment] 2020-07-03 18:27
Everything is all right now. We know that the bug is in Qt 5.15 and we have a [simple workaround](https://github.com/lxqt/libqtxdg/pull/214), which we could use if the bug isn't fixed in Qt.

**Comment by yan12125** [comment] 2020-09-11 03:00
As a record, an Arch Linux user gets confused due to this issue https://bbs.archlinux.org/viewtopic.php?id=258876

By the way, has the issue been reported to https://bugreports.qt.io/ ?

**Comment by tsujan** [comment] 2020-09-11 06:19
> By the way, has the issue been reported to https://bugreports.qt.io/ ?

I neither searched for nor reported it. Quite frankly, Qt5 devs get on my nerves…

**Comment by luis-pereira** [comment] 2020-09-11 16:06
I did not report it.

**Comment by jeremywh7** [comment] 2020-09-11 23:33
This was fixed in qt5 5.15.1; I tested qt5-base (and the other 5 qt5-* packages in my system) yesterday from the (Archlinux) testing repo.
https://www.archlinux.org/packages/testing/x86_64/qt5-base/

**Comment by yan12125** [comment] 2020-09-12 03:12
Thanks for testing! I can confirm the issue is gone with 5.15.1, too. Closing as upstream issue has been fixed.

**Closed by yan12125** 2020-09-12 03:12 UTC
Labels: qt5
